/// <reference types="node" />
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import {
  DEFAULT_SCHEDULER_OPTIONS, measurePlacement, placementBudget, placementGraph, simulate, type CourseShare, type PlacementMeasure, type SimResult,
} from '@learnhub/mastery';
import { courseById, courseTargets, coursesClosure, coursesTopics } from './courses';
import { topics as allTopics } from './topics';

/**
 * Design decision 14: IA Probability and CST Discrete Mathematics at once, an even split of
 * new-lesson minutes. Simulation results, not real-learner data; the learner model is the
 * one SIMULATION.md describes.
 */
const ia = courseById('ia-probability');
const dm = courseById('cst-discrete-maths');
// The union of the two closures, in graph order. It was the whole graph until Cambridge batch 2
// added topics that are not course targets yet; restricting to it keeps these runs unchanged.
const topics = coursesTopics(allTopics, [ia, dm]);
const courses: CourseShare[] = [ia, dm].map((c) => ({ id: c.id, targets: courseTargets(topics, c) }));
const SEEDS = [1, 2, 3, 4, 5];
const DAYS = 120;
const runs = SEEDS.map((seed) => simulate({ topics, courses, seed, days: DAYS }));
const lessonMinutes = (r: SimResult): number => r.days.reduce((a, d) => a + d.lessonMinutes, 0);
const firstDone = (r: SimResult): number => Math.min(...Object.values(r.dayCourseMastered ?? {}).map((d) => d ?? Infinity));
// The runs are deterministic, so a shorter run is a prefix: it shows the split while both courses were open.
const beforeFirst = runs.map((r, i) => simulate({ topics, courses, seed: SEEDS[i] as number, days: firstDone(r) - 1 }));

describe('two courses at an even split (simulation)', { timeout: 120_000 }, () => {
  it('masters both slices on every seed within 80 days', () => {
    for (const r of runs) {
      for (const c of courses) {
        expect(r.dayCourseMastered?.[c.id], c.id).not.toBeNull();
        expect(r.dayCourseMastered?.[c.id] as number, c.id).toBeLessThanOrEqual(80);
      }
      expect(r.dayAllMastered).toBe(Math.max(...Object.values(r.dayCourseMastered ?? {}).map((d) => d as number)));
    }
  });

  // Each choice keeps the gap within one lesson, but a course with no lesson that fits that
  // day yields its time, so the gap can drift: measured at most 35 of about 1,950 minutes.
  it('splits lesson minutes evenly while both courses are open, within 5%', () => {
    for (const r of beforeFirst) {
      const m = r.courseLessonMinutes ?? {};
      const a = m[ia.id] ?? 0;
      const b = m[dm.id] ?? 0;
      expect(Math.abs(a - b)).toBeLessThanOrEqual(0.05 * (a + b));
    }
  });

  it('charges every lesson minute to exactly one course, and never exceeds the budget', () => {
    for (const r of runs) {
      const m = r.courseLessonMinutes ?? {};
      expect((m[ia.id] ?? 0) + (m[dm.id] ?? 0)).toBe(lessonMinutes(r));
      for (const d of r.days) expect(d.lessonMinutes + d.reviewMinutes + d.quizMinutes).toBeLessThanOrEqual(DEFAULT_SCHEDULER_OPTIONS.budgetMinutes);
    }
  });

  it('SIMULATION-two-courses.md is regenerated from these runs (checked, not written, under CI)', () => {
    const targets = courses.flatMap((c) => [...c.targets]);
    const scaled = placementBudget(placementGraph(topics, { targets }).order.length);
    const placement = [30, 40, scaled].map((budget) => measurePlacement(topics, { learners: 1000, errorRate: 0, budget, strategy: 'split', seed: 1, targets }));
    const md = render(runs, beforeFirst, placement);
    expect(md).not.toMatch(/[\u2013\u2014]/);
    const path = new URL('../SIMULATION-two-courses.md', import.meta.url);
    let current = '';
    try { current = readFileSync(path, 'utf8'); } catch { /* first run */ }
    if (process.env.CI) expect(current, 'SIMULATION-two-courses.md is stale; run npm test locally and commit it').toBe(md);
    else if (current !== md) writeFileSync(path, md);
  });
});

function render(rs: readonly SimResult[], early: readonly SimResult[], placement: readonly PlacementMeasure[]): string {
  const f1 = (x: number): string => x.toFixed(1);
  const pct = (x: number): string => `${(100 * x).toFixed(1)}%`;
  const mean = (xs: readonly number[]): number => xs.reduce((a, b) => a + b, 0) / xs.length;
  const sizeOf = (id: string): number => coursesClosure(topics, [courseById(id)]).size;
  const minutesOf = (id: string): number => [...coursesClosure(topics, [courseById(id)])]
    .reduce((a, t) => a + (topics.find((x) => x.id === t)?.estMinutes ?? 0), 0);
  const lines: string[] = [];
  const p = (s = ''): void => { lines.push(s); };
  p('# Two courses at once: simulation results');
  p();
  p('**Simulation results, not real-learner data.** Generated by `src/two-courses.test.ts` (`npm test` in `graph`); do not edit by hand. Same learner model and engine settings as `SIMULATION.md`.');
  p();
  p('## Setup');
  p();
  p(`- Courses: ${courses.map((c) => `\`${c.id}\` (${sizeOf(c.id)} topics, ${minutesOf(c.id)} lesson minutes in its closure)`).join(' and ')}; ${topics.length} topics in the union, each learned once.`);
  p(`- ${DAYS} days, one ${DEFAULT_SCHEDULER_OPTIONS.budgetMinutes}-minute session a day, starting from nothing, no placement. \`planSession\` with both courses and no weights: an even split of new-lesson minutes, reviews unsplit.`);
  p(`- Seeds: ${SEEDS.join(', ')}.`);
  p();
  p('## Days and minutes per course');
  p();
  p('Lesson minutes are charged to the course that took the lesson (a shared foundation counts once, for one course), failed lessons included. Once one course is done, the other gets all the lesson time.');
  p();
  p(`| seed | days to master ${ia.id} | days to master ${dm.id} | days to master both | lesson min, ${ia.id} | lesson min, ${dm.id} | review and quiz min | split before the first course is done |`);
  p('|---|---|---|---|---|---|---|---|');
  rs.forEach((r, i) => {
    const m = r.courseLessonMinutes ?? {};
    const e = early[i]?.courseLessonMinutes ?? {};
    p(`| ${SEEDS[i]} | ${r.dayCourseMastered?.[ia.id] ?? 'not reached'} | ${r.dayCourseMastered?.[dm.id] ?? 'not reached'} | ${r.dayAllMastered ?? 'not reached'} | ${m[ia.id] ?? 0} | ${m[dm.id] ?? 0} | ${r.totalReviewMinutes} | ${e[ia.id] ?? 0} / ${e[dm.id] ?? 0} |`);
  });
  const d = (id: string): number => mean(rs.map((r) => r.dayCourseMastered?.[id] ?? Infinity));
  p();
  p(`Means over ${SEEDS.length} seeds: ${f1(d(ia.id))} days to master \`${ia.id}\`, ${f1(d(dm.id))} days to master \`${dm.id}\`, ${f1(mean(rs.map((r) => r.dayAllMastered ?? Infinity)))} days for both.`);
  p();
  p('## Placement over both courses');
  p();
  p(`Truthful random learners (the \`SIMULATION.md\` model), split strategy. Unclassified topics at the budget count as not known. The last row is the default budget, \`placementBudget\` of the ${topics.length}-topic union: max(30, ceil(${topics.length} / 2)).`);
  p();
  p('| budget | learners | placed exactly | mean over-placed | mean under-placed | mean questions | max questions |');
  p('|---|---|---|---|---|---|---|');
  for (const m of placement) {
    p(`| ${m.budget} | ${m.learners} | ${pct(m.exact)} | ${m.meanOverPlaced.toFixed(2)} | ${m.meanUnderPlaced.toFixed(2)} | ${f1(m.meanQuestions)} | ${m.maxQuestions} |`);
  }
  p();
  return lines.join('\n');
}
