/**
 * prob.event-spaces: Events and sigma-algebras (batch 1 decision 4). IA Probability Example
 * Sheet 1 Q4 asks for the definition of a sigma-algebra and for proofs from it, although
 * the schedule says only "Axioms (countable case)"; no lecture notes are in the batch, so
 * the lesson is written from the sheet's Q4 and Q6 and the schedule. The worked example is
 * Q4(a), worked in full; Q4's definitions and Q6(b) are set for supervision.
 */
import { cite, supervision } from '../cambridge';
import { int, sample, upTo } from '../math';
import { generator, type ChoiceOption, type Misconception } from '../problem';
import { computedTex, dmath, math, setOf, t, type Span } from '../rich';
import { quickCheck, worked, workedProof, type TopicContent } from '../topic';

const [mO, mF] = [math`\Omega`, math`\mathcal{F}`];

/** Subsets of {1, ..., n} as bit masks: bit i - 1 set means i is in the set. */
const elems = (m: number, n: number): number[] => upTo(n).filter((i) => ((m >> (i - 1)) & 1) === 1);
const maskOf = (xs: readonly number[]): number => xs.reduce((m, i) => m | (1 << (i - 1)), 0);
const full = (n: number): number => (1 << n) - 1;
const setTex = (m: number, n: number): Span => (m === 0 ? math`\varnothing` : setOf(elems(m, n)));

/** The smallest collection containing `gens`, the empty set, and the whole set, closed under complement and union: brute force to a fixed point. */
function closure(gens: readonly number[], n: number): Set<number> {
  const out = new Set<number>([0, full(n), ...gens]);
  for (let changed = true; changed;) {
    changed = false;
    for (const a of [...out]) {
      for (const b of [a ^ full(n), ...[...out].map((x) => a | x)]) {
        if (!out.has(b)) { out.add(b); changed = true; }
      }
    }
  }
  return out;
}

/** The nonempty atoms of the events: the sets of points that no event separates. */
function atoms(events: readonly number[], n: number): number {
  const sig = new Set(upTo(n).map((i) => events.map((e) => (e >> (i - 1)) & 1).join('')));
  return sig.size;
}

// ---------------------------------------------------------------- generators

interface PartP { n: number; blocks: number[][] }

/** A random partition of {1, ..., n} into k nonempty blocks. */
function partition(rng: () => number, n: number, k: number): number[][] {
  const shuffled = sample(rng, upTo(n), n);
  const cuts = sample(rng, upTo(n - 1), k - 1).sort((a, b) => a - b);
  const bounds = [0, ...cuts, n];
  return upTo(k).map((j) => (shuffled.slice(bounds[j - 1], bounds[j]) as number[]).sort((a, b) => a - b)).sort((a, b) => (a[0] as number) - (b[0] as number));
}

const partitionCount = generator<PartP>({
  id: 'partition-count',
  skill: 'Count the events of the sigma-algebra generated by a partition: every union of blocks.',
  params: (rng) => {
    const n = int(rng, 5, 9);
    return { n, blocks: partition(rng, n, int(rng, 2, Math.min(5, n - 1))) };
  },
  sane: ({ n, blocks }) => (blocks.flat().length === n && new Set(blocks.flat()).size === n && blocks.length >= 2 && blocks.length <= 5 ? null : 'not a partition'),
  problem: ({ n, blocks }) => {
    const k = blocks.length;
    return {
      prompt: t`Let ${math`\Omega = ${setOf(upTo(n))}`}, split into the blocks ${computedTex(blocks.map((b) => setOf(b).text).join(',\\ '))}. Let ${mF} be the collection of all unions of blocks, the empty union ${math`\varnothing`} included. It is a [[sigma-algebra|sigma-algebra]]. How many events does ${mF} contain?`,
      answer: { kind: 'exact', expected: String(2 ** k) },
      solution: [
        t`An event in ${mF} is fixed by which blocks it contains: each of the ${k} blocks is in or out.`,
        t`By the product rule that is ${math`${2}^{${k}} = ${2 ** k}`} events, from ${math`\varnothing`} (no blocks) to ${mO} (all of them).`,
        t`It is closed under complement (swap in and out) and under unions (take every block in either), so it is a sigma-algebra.`,
      ],
    };
  },
  solve: ({ n, blocks }) => String(closure(blocks.map(maskOf), n).size),
  misconceptions: ({ n, blocks }): Misconception[] => [
    { response: String(blocks.length + 2), why: t`Unions of blocks are events too, not only the blocks, ${math`\varnothing`}, and ${mO}.` },
    { response: String(2 ** n), why: t`That counts every subset of ${mO}. Here an event must be a union of whole blocks: it cannot split a block.` },
    { response: String(2 ** blocks.length - 1), why: t`The empty union, ${math`\varnothing`}, is an event as well: it is the complement of ${mO}.` },
  ],
});

interface GenP { n: number; a: number; b: number }

const generated = generator<GenP>({
  id: 'generated',
  skill: 'Count the events of the smallest sigma-algebra containing two given events, through its atoms.',
  params: (rng) => {
    for (;;) {
      const n = int(rng, 4, 7);
      const a = int(rng, 1, full(n) - 1);
      const b = int(rng, 1, full(n) - 1);
      if (a !== b && a !== (b ^ full(n))) return { n, a, b };
    }
  },
  sane: ({ n, a, b }) => (a > 0 && b > 0 && a < full(n) && b < full(n) && a !== b && a !== (b ^ full(n)) ? null : 'out of range'),
  problem: ({ n, a, b }) => {
    const k = atoms([a, b], n);
    const parts: [string, number][] = [
      ['A \\cap B', a & b], ['A \\cap B^{c}', a & ~b & full(n)], ['A^{c} \\cap B', ~a & b & full(n)], ['A^{c} \\cap B^{c}', ~a & ~b & full(n)],
    ];
    return {
      prompt: t`Let ${math`\Omega = ${setOf(upTo(n))}`}, ${math`A = ${setTex(a, n)}`}, and ${math`B = ${setTex(b, n)}`}. How many events are in the smallest sigma-algebra on ${mO} that contains ${math`A`} and ${math`B`}?`,
      answer: { kind: 'exact', expected: String(2 ** k) },
      solution: [
        t`The sigma-algebra must contain the pieces ${math`A \cap B`}, ${math`A \cap B^{c}`}, ${math`A^{c} \cap B`}, and ${math`A^{c} \cap B^{c}`}: ${computedTex(parts.map(([name, m]) => `${name} = ${setTex(m, n).text}`).join(',\\ '))}.`,
        t`The nonempty pieces, ${k} of them, form a partition, and the smallest sigma-algebra is every union of them: ${math`${2}^{${k}} = ${2 ** k}`} events.`,
      ],
    };
  },
  solve: ({ n, a, b }) => String(closure([a, b], n).size),
  misconceptions: ({ n }): Misconception[] => [
    { response: '4', why: t`${math`\varnothing`}, ${math`A`}, ${math`B`}, and ${mO} are not closed: complements and unions must be in too.` },
    { response: '6', why: t`Adding the complements is not enough: unions such as ${math`A \cup B`} and the intersections they lead to are needed too.` },
    { response: String(2 ** n), why: t`Not every subset is needed: only unions of the pieces that ${math`A`} and ${math`B`} cut ${mO} into.` },
  ],
});

interface MissP { gens: number[] }

const N4 = 4;
const missing = generator<MissP>({
  id: 'missing',
  skill: 'Find what must be added to a collection of events to close it under complements and unions.',
  params: (rng) => {
    for (;;) {
      // Two events, so that unions are needed as well as complements, and not everything is forced.
      const gens = sample(rng, upTo(full(N4) - 1), 2);
      const given = new Set([0, full(N4), ...gens]);
      const need = [...closure(gens, N4)].filter((m) => !given.has(m));
      const comps = new Set(gens.map((g) => g ^ full(N4)).filter((m) => !given.has(m)));
      if (need.length > comps.size && need.length < full(N4) - 1 - gens.length) return { gens };
    }
  },
  sane: ({ gens }) => (gens.every((g) => g > 0 && g < full(N4)) ? null : 'out of range'),
  problem: ({ gens }) => {
    const given = [...new Set([0, ...gens, full(N4)])].sort((x, y) => x - y);
    const all = [...closure(gens, N4)];
    const need = all.filter((m) => !given.includes(m)).sort((x, y) => x - y);
    const options: ChoiceOption[] = upTo(full(N4) - 1).filter((m) => !given.includes(m)).map((m) => ({ id: `s${m}`, label: [setTex(m, N4)] }));
    return {
      prompt: t`Let ${math`\Omega = ${setOf(upTo(N4))}`} and let ${mF} start as ${computedTex(given.map((m) => setTex(m, N4).text).join(',\\ '))}. Choose every set that must be added so that ${mF} is the smallest sigma-algebra containing these.`,
      answer: { kind: 'choice', options, correct: need.map((m) => `s${m}`) },
      solution: [
        t`Add complements: each event's complement must be an event. Then add unions of everything present, and repeat until nothing new appears.`,
        t`The result has ${all.length} events. The ones to add are ${computedTex(need.map((m) => setTex(m, N4).text).join(',\\ '))}.`,
      ],
    };
  },
  solve: ({ gens }) => {
    // The sigma-algebra generated by the events is every union of their atoms.
    const given = new Set([0, ...gens, full(N4)]);
    const groups = new Map<string, number>();
    for (const i of upTo(N4)) {
      const key = gens.map((g) => (g >> (i - 1)) & 1).join('');
      groups.set(key, (groups.get(key) ?? 0) | (1 << (i - 1)));
    }
    const blocks = [...groups.values()];
    const unions = new Set<number>();
    for (let s = 0; s < 1 << blocks.length; s++) unions.add(blocks.reduce((u, b, j) => (((s >> j) & 1) === 1 ? u | b : u), 0));
    return [...unions].filter((m) => !given.has(m)).map((m) => `s${m}`);
  },
  misconceptions: ({ gens }): Misconception[] => {
    const given = new Set([0, ...gens, full(N4)]);
    const comps = gens.map((g) => g ^ full(N4)).filter((m) => !given.has(m));
    const everything = upTo(full(N4) - 1).filter((m) => !given.has(m));
    return [
      { response: [...new Set(comps)].map((m) => `s${m}`), why: t`Complements are needed, but so are unions, and then the complements of those.` },
      { response: everything.map((m) => `s${m}`), why: t`Not every subset is forced: only unions of the pieces the given events cut ${mO} into.` },
    ];
  },
});

// ---------------------------------------------------------------- Cambridge problems

const S1 = 'ia-prob-sheet-1';

const q4a = workedProof({
  title: t`Events built from the definition`,
  prompt: t`Let ${mF} be a sigma-algebra on ${mO} and ${math`(A_n : n \in \mathbb{N})`} a sequence of events. Show, starting from the definition, that ${math`\varnothing`}, ${math`A_{${1}} \cup A_{${2}}`}, and ${math`\bigcap_{n = ${1}}^{\infty} A_n`} are events.`,
  steps: [
    t`${math`\varnothing`}: ${math`\Omega \in \mathcal{F}`}, and ${mF} is closed under complements, so ${math`\varnothing = \Omega^{c} \in \mathcal{F}`}.`,
    t`${math`A_{${1}} \cup A_{${2}}`}: the definition only gives countable unions, so pad the pair into a sequence, ${math`A_{${1}}, A_{${2}}, \varnothing, \varnothing, \ldots`}. Every term is an event (${math`\varnothing`} by the first part), so the union of the sequence is an event, and it equals ${math`A_{${1}} \cup A_{${2}}`}.`,
    t`${math`\bigcap_{n} A_n`}: by De Morgan's law, ${math`\bigcap_{n} A_n = \left(\bigcup_{n} A_n^{c}\right)^{c}`}. Each ${math`A_n^{c}`} is an event (complements), so their countable union is (unions), and so is its complement (complements again).`,
  ],
  answer: t`All three are events, using only ${math`\Omega \in \mathcal{F}`}, closure under complements, and closure under countable unions.`,
  source: cite(S1, 'Q4(a)'),
});

const q4def = supervision({
  id: 'q4-definitions',
  source: cite(S1, 'Q4, first sentence'),
  title: t`State the definitions`,
  prompt: t`State what it means for ${mF} to be a sigma-algebra on ${mO}, and for ${math`\mathbb{P}`} to be a probability measure on ${math`(\Omega, \mathcal{F})`}. Say why the definition asks for countable unions, not only unions of two events.`,
  writeUp: 'explanation',
});

const q4aSecond = supervision({
  id: 'q4-a-finite',
  source: cite(S1, 'Q4(a)', true),
  title: t`Finite unions and intersections`,
  prompt: t`From the definition of a sigma-algebra alone, show that if ${math`A_{${1}}, \ldots, A_{n}`} are events then so are ${math`A_{${1}} \cup \cdots \cup A_n`}, ${math`A_{${1}} \cap \cdots \cap A_n`}, and ${math`A_{${1}} \setminus A_{${2}}`}.`,
  writeUp: 'proof',
});

const q6b = supervision({
  id: 'q6-b-event',
  source: cite(S1, 'Q6(a) and the first part of Q6(b)'),
  title: t`"Infinitely often" is an event`,
  prompt: t`Let ${math`(A_n : n \in \mathbb{N})`} be events in ${math`(\Omega, \mathcal{F}, \mathbb{P})`}, and let ${math`A = \{\omega \in \Omega : \omega \in A_n \text{ infinitely often}\}`} and ${math`B = \{\omega \in \Omega : \omega \in A_n \text{ for all sufficiently large } n\}`}. Show that ${math`B = \bigcup_{n = ${1}}^{\infty} \bigcap_{k = n}^{\infty} A_k`}, write ${math`A`} in the same way, and show that ${math`A`} is an event.`,
  writeUp: 'proof',
});

// ---------------------------------------------------------------- lesson

const D = 6;
const parity = [[1, 3, 5], [2, 4, 6]] as const;

const [mA, mk] = [math`A`, math`k`];
const evenSet = setOf([...parity[1]]);
const oddSet = setOf([...parity[0]]);

export const eventSpaces: TopicContent = {
  topicId: 'prob.event-spaces',
  goal: t`State the definition of a sigma-algebra of events, and deduce from it that the empty set, finite unions, and countable intersections of events are events.`,
  objective: t`State the definition of a sigma-algebra, check it on examples, and deduce new events from it.`,
  why: t`Events are where probabilities live; next come the axioms of a probability measure.`,
  minutes: 25,
  lesson: [
    { kind: 'section', title: t`Which sets are events?` },
    { kind: 'hook', text: t`Roll a die. "The roll is even" is an event, and so is "the roll is not even". What about "the roll is even, or it is a ${6}, or it is a ${4}, or ..." with infinitely many clauses? Probability needs to know, in advance, exactly which sets it may assign a number to.` },
    { kind: 'narrative', text: t`A probability space has three parts: the sample space ${mO} of outcomes, a collection ${mF} of subsets of ${mO} called events, and the probability ${math`\mathbb{P}`}, which gives each event a number. IA Probability Example Sheet ${1} begins by asking what ${mF} must satisfy. The answer is three closure rules.` },
    {
      kind: 'definition',
      name: t`Sigma-algebra`,
      formal: t`A collection ${mF} of subsets of ${mO} is a [[sigma-algebra|sigma-algebra]] on ${mO} if (i) ${math`\Omega \in \mathcal{F}`}; (ii) if ${math`A \in \mathcal{F}`} then ${math`A^{c} \in \mathcal{F}`}; and (iii) if ${math`A_{${1}}, A_{${2}}, \ldots \in \mathcal{F}`} then ${math`\bigcup_{n = ${1}}^{\infty} A_n \in \mathcal{F}`}. Its members are called events.`,
      plain: t`"something happens" is an event; "not ${mA}" is an event whenever ${mA} is; and "at least one of a sequence of events happens" is an event. ${math`A^{c}`}, the complement, is everything in ${mO} not in ${mA}.`,
    },
    {
      kind: 'p',
      text: t`Rule (iii) is about a whole sequence of events, countably many, not just two. That is what makes limits of events, such as "${math`A_n`} happens infinitely often", into events whose probability can be asked for.`,
      why: { q: t`Why not simply make every subset an event?`, a: t`For a countable ${mO}, the schedule's "countable case", that is exactly what is usually done. For ${math`\Omega = [${0}, ${1}]`}, not every subset can be given a length consistently, so the definition asks only for these closure rules.` },
    },
    { kind: 'section', title: t`Small sigma-algebras` },
    { kind: 'narrative', text: t`On a die, ${math`\Omega = ${setOf(upTo(D))}`}. The smallest sigma-algebra is ${math`\{\varnothing, \Omega\}`}: you can only say whether something happened. Add the single event ${math`A = ${evenSet}`}, "even". Rule (ii) forces ${math`A^{c} = ${oddSet}`} in too. Is that enough?` },
    { kind: 'theorem', statement: t`For any ${math`A \subseteq \Omega`}, the collection ${math`\mathcal{F} = \{\varnothing, A, A^{c}, \Omega\}`} is a sigma-algebra on ${mO}.` },
    {
      kind: 'steps',
      proof: true,
      steps: [
        { label: t`Rule (i)`, text: t`${math`\Omega \in \mathcal{F}`} by construction.`, plain: t`It is one of the four sets listed.` },
        { label: t`Rule (ii)`, text: t`The complements are ${math`\varnothing^{c} = \Omega`}, ${math`A^{c}`}, ${math`(A^{c})^{c} = A`}, and ${math`\Omega^{c} = \varnothing`}, all in ${mF}.`, plain: t`Complementing swaps ${math`\varnothing`} with ${mO} and ${mA} with ${math`A^{c}`}.` },
        {
          label: t`Rule (iii)`, text: t`Let ${math`A_{${1}}, A_{${2}}, \ldots \in \mathcal{F}`} and ${math`U = \bigcup_{n} A_n`}. If some ${math`A_n = \Omega`}, or both ${mA} and ${math`A^{c}`} occur among them, then ${math`U = \Omega`}. Otherwise every ${math`A_n`} is ${math`\varnothing`} or ${mA} (so ${math`U`} is ${math`\varnothing`} or ${mA}), or every ${math`A_n`} is ${math`\varnothing`} or ${math`A^{c}`} (so ${math`U`} is ${math`\varnothing`} or ${math`A^{c}`}).`,
          plain: t`A union of sets from the list can only be one of the four, however many sets are in it.`,
          why: { q: t`Why do ${mA} and ${math`A^{c}`} together give ${mO}?`, a: t`Every outcome is either in ${mA} or not in ${mA}, that is, in ${math`A^{c}`}. So ${math`A \cup A^{c} = \Omega`}.` },
        },
        { label: t`Conclude`, text: t`All three rules hold, so ${mF} is a sigma-algebra.`, plain: t`On the die: ${math`\{\varnothing, ${evenSet}, ${oddSet}, \Omega\}`}.` },
      ],
    },
    {
      kind: 'p',
      text: t`The same idea scales up. Split ${mO} into ${mk} non-overlapping blocks that cover it, a [[partition|partition]]. All the unions of blocks form a sigma-algebra with ${math`${2}^{k}`} events, one for each choice of blocks to include. Every finite sigma-algebra has this form.`,
    },
    quickCheck({
      prompt: t`The die's outcomes are split into the blocks ${setOf([1, 2])}, ${setOf([3, 4])}, ${setOf([5, 6])}. How many events are in the sigma-algebra of all unions of blocks?`,
      answer: { kind: 'exact', expected: String(2 ** 3) },
      reference: String(2 ** 3),
      why: t`Each of the ${3} blocks is in or out of a union: ${math`${2}^{${3}} = ${2 ** 3}`}, counting the empty union ${math`\varnothing`} and the full union ${mO}.`,
    }),
    {
      kind: 'pitfall',
      claim: t`${math`\{\varnothing, ${setOf([1])}, ${setOf([2])}, \Omega\}`} is a sigma-algebra on the die.`,
      counterexample: t`The complement of ${setOf([1])} is ${setOf([2, 3, 4, 5, 6])}, which is missing, and so is the union ${setOf([1, 2])}. Rules (ii) and (iii) both fail.`,
    },
    { kind: 'section', title: t`New events from old` },
    { kind: 'narrative', text: t`The definition lists only three rules, but many more sets follow. Part (a) of the sheet's fourth question asks for three: ${math`\varnothing = \Omega^{c}`} is an event by rules (i) and (ii); ${math`A_{${1}} \cup A_{${2}}`} is the union of the sequence ${math`A_{${1}}, A_{${2}}, \varnothing, \varnothing, \ldots`}; and countable intersections follow from De Morgan's law, ${math`\bigcap_n A_n = \left(\bigcup_n A_n^{c}\right)^{c}`}. The first example below writes these out in full.` },
    { kind: 'takeaway', text: t`A sigma-algebra contains ${mO} and is closed under complements and countable unions; everything else, the empty set, finite unions, and intersections, follows from those three rules.` },
  ],
  examples: [
    { ...q4a, examiner: t`Each new set written explicitly as a complement or a countable union of known events, with the rule used named at every step.` },
    worked(partitionCount, { n: 6, blocks: [[1, 2], [3, 4], [5, 6]] }, t`Events from a partition`),
    worked(generated, { n: 5, a: maskOf([1, 2, 3]), b: maskOf([3, 4]) }, t`The events two events generate`),
  ],
  generators: [partitionCount, generated, missing],
  mastery: { correctInARow: 3, maxProblems: 10 },
  terms: ['sigma-algebra', 'partition'],
  cambridge: [q4def, q4aSecond, q6b],
  // Q6(b) first: it needs the limit events built from countable unions and intersections. Then Q4(a)'s
  // finite case. Q4's definitions are recall, not a test, so they do not gate.
  gate: ['q6-b-event', 'q4-a-finite'],
  recall: [
    { front: t`Define a sigma-algebra on ${mO}.`, back: t`A collection ${mF} of subsets with ${math`\Omega \in \mathcal{F}`}, closed under complements and under countable unions.` },
    { front: t`Why is ${math`\varnothing`} an event?`, back: t`${math`\varnothing = \Omega^{c}`}, and complements of events are events.` },
    { front: t`Why is a countable intersection of events an event?`, back: t`${math`\bigcap_n A_n = \left(\bigcup_n A_n^{c}\right)^{c}`}, by De Morgan.` },
    { front: t`How many events in the sigma-algebra from a partition into ${mk} blocks?`, back: t`${math`${2}^{k}`}, one per choice of blocks.` },
  ],
  proofOrder: [
    {
      title: t`Intersections of events are events`,
      steps: [
        t`Each ${math`A_n^{c}`} is an event, by closure under complements.`,
        t`So ${math`\bigcup_n A_n^{c}`} is an event, by closure under countable unions.`,
        t`So its complement is an event.`,
        t`By De Morgan, that complement is ${math`\bigcap_n A_n`}.`,
      ],
    },
  ],
};
