/**
 * comb.factorial: Factorials and arranging n objects. From STEP Support Assignment 6
 * (Q5(i): Claire's 6 x 5 x ... x 1 = 6!; Q2(i): Ben, Elsa, and Charlie) and the change
 * ringing discussion of Assignment 12 Q4 (an extent on 5 bells is 5! = 120 changes).
 */
import { auto, cite, same } from '../cambridge';
import { factorial, int, pick } from '../math';
import { generator, type Misconception } from '../problem';
import { computed, computedMath as cm, dmath, ident, math, t } from '../rich';
import { quickCheck, worked, workedCambridge, type TopicContent } from '../topic';

/** Every ordering of 0 .. n - 1, generated by Heap's algorithm. */
function permutations(n: number): number[][] {
  const a = Array.from({ length: n }, (_, i) => i);
  const out: number[][] = [[...a]];
  const c = Array.from({ length: n }, () => 0);
  for (let i = 1; i < n;) {
    if ((c[i] as number) < i) {
      const j = i % 2 === 0 ? 0 : (c[i] as number);
      [a[j], a[i]] = [a[i] as number, a[j] as number];
      out.push([...a]);
      c[i] = (c[i] as number) + 1;
      i = 1;
    } else {
      c[i] = 0;
      i++;
    }
  }
  return out;
}

const productText = (hi: number, lo = 1): string => Array.from({ length: hi - lo + 1 }, (_, i) => hi - i).join(' * ');
const mn = math`n`;

// ---------------------------------------------------------------- generators

interface ArrangeP { n: number; what: 'books' | 'runners' | 'letters' }

const arrange = generator<ArrangeP>({
  id: 'arrange',
  skill: 'Count the orderings of n different objects.',
  params: (rng) => ({ n: int(rng, 3, 7), what: pick(rng, ['books', 'runners', 'letters'] as const) }),
  sane: ({ n }) => (n >= 3 && n <= 7 ? null : 'out of range'),
  problem: ({ n, what }) => ({
    prompt: what === 'books'
      ? t`In how many different orders can ${n} different books stand on a shelf?`
      : what === 'runners'
        ? t`${n} runners finish a race with no ties. How many different finishing orders are possible?`
        : t`How many different arrangements are there of ${n} different letters, using each letter once?`,
    answer: { kind: 'exact', expected: String(factorial(n)) },
    solution: [
      t`The first place can be filled in ${n} ways, the second in ${n - 1} (one object is used), and so on down to ${1}.`,
      t`By the product rule that is ${cm(`${productText(n)} = ${factorial(n)}`)}, written ${math`${n}!`}.`,
    ],
  }),
  solve: ({ n }) => String(permutations(n).length),
  misconceptions: ({ n }): Misconception[] => [
    { response: String(n ** n), why: t`That allows the same object in several places. Each object is used once, so each place has one fewer choice than the one before.` },
    { response: String((n * (n + 1)) / 2), why: t`That adds ${math`${n} + ${n - 1} + \cdots + ${1}`}. The choices happen one after another, so multiply them.` },
    { response: String(n), why: t`There are ${n} choices for the first place alone. Multiply by the choices for every later place too.` },
  ],
});

interface RatioP { n: number; k: number }

const ratio = generator<RatioP>({
  id: 'ratio',
  skill: 'Simplify a ratio of factorials by cancelling.',
  params: (rng) => ({ n: int(rng, 2, 10), k: int(rng, 1, 3) }),
  sane: ({ n, k }) => (n >= 2 && n <= 10 && k >= 1 && k <= 3 ? null : 'out of range'),
  problem: ({ n, k }) => {
    const value = factorial(n + k) / factorial(n);
    return {
      prompt: t`Work out ${math`\frac{${n + k}!}{${n}!}`} without a calculator.`,
      answer: { kind: 'exact', expected: String(value) },
      solution: [
        t`Write the top as ${math`${n + k}! = ${cm(productText(n + k, n + 1))} \times ${n}!`}.`,
        t`The ${math`${n}!`} cancels, leaving ${cm(`${productText(n + k, n + 1)} = ${value}`)}.`,
      ],
    };
  },
  solve: ({ n, k }) => {
    let top = 1n;
    for (let i = 2n; i <= BigInt(n + k); i++) top *= i;
    let bottom = 1n;
    for (let i = 2n; i <= BigInt(n); i++) bottom *= i;
    return (top / bottom).toString();
  },
  misconceptions: ({ n, k }): Misconception[] => [
    { response: String(factorial(k)), why: t`Factorials do not cancel like that: ${math`\frac{${n + k}!}{${n}!}`} is not ${math`\left(\frac{${n + k}}{${n}}\right)!`} or ${math`${k}!`}. Write out the top until ${math`${n}!`} appears, then cancel it.` },
    { response: String(n + k), why: t`That keeps only the first factor. The top is ${math`${n + k} \times ${n + k - 1} \times \cdots`}; cancel ${math`${n}!`} and multiply every factor that is left.` },
    { response: String(factorial(n + k) - factorial(n)), why: t`A fraction bar means divide, not subtract. Cancel ${math`${n}!`} from the top and the bottom.` },
  ],
});

interface FixedP { n: number; rule: 'first' | 'ends' }

const fixed = generator<FixedP>({
  id: 'fixed',
  skill: 'Count orderings when some positions are fixed.',
  params: (rng) => ({ n: int(rng, 4, 7), rule: pick(rng, ['first', 'ends'] as const) }),
  sane: ({ n }) => (n >= 4 && n <= 7 ? null : 'out of range'),
  problem: ({ n, rule }) => {
    if (rule === 'first') {
      return {
        prompt: t`${n} friends, including Ana, stand in a line for a photo. Ana must stand first. How many orders are possible?`,
        answer: { kind: 'exact', expected: String(factorial(n - 1)) },
        solution: [
          t`Ana's place is fixed, so only the other ${n - 1} people are arranged.`,
          t`That is ${math`${n - 1}! = ${factorial(n - 1)}`}.`,
        ],
      };
    }
    return {
      prompt: t`${n} friends, including Ana and Ben, stand in a line. Ana and Ben must stand at the two ends. How many orders are possible?`,
      answer: { kind: 'exact', expected: String(2 * factorial(n - 2)) },
      solution: [
        t`Ana and Ben fill the two ends in ${2} ways: Ana left and Ben right, or the other way round.`,
        t`The other ${n - 2} people fill the middle in ${math`${n - 2}! = ${factorial(n - 2)}`} ways.`,
        t`By the product rule: ${math`${2} \times ${factorial(n - 2)} = ${2 * factorial(n - 2)}`}.`,
      ],
    };
  },
  solve: ({ n, rule }) => {
    // Person 0 is Ana, person 1 is Ben; count the orderings that obey the rule.
    const ok = (p: number[]): boolean => (rule === 'first' ? p[0] === 0 : (p[0] === 0 && p[n - 1] === 1) || (p[0] === 1 && p[n - 1] === 0));
    return String(permutations(n).filter(ok).length);
  },
  misconceptions: ({ n, rule }): Misconception[] => rule === 'first'
    ? [
      { response: String(factorial(n)), why: t`That counts every order, including those where Ana is not first. Fix Ana and arrange only the others.` },
      // Not n times (n - 1)!: that is n! again, the slip above.
      { response: String(factorial(n) - factorial(n - 1)), why: t`That counts the orders where Ana is not first: all orders less those with Ana first. The question asks for the orders with Ana first.` },
    ]
    : [
      { response: String(factorial(n - 2)), why: t`That fixes Ana on the left and Ben on the right. They can also swap ends, which doubles the count.` },
      { response: String(factorial(n)), why: t`That counts every order. Place Ana and Ben at the ends first, then arrange the others in the middle.` },
    ],
});

/** Names whose letters are all different, so every arrangement is distinct. */
const NAMES = ['Ben', 'Kate', 'Elsa', 'Oscar', 'Freya', 'Jacob', 'Claire', 'Sophie', 'Daniel', 'Harvey', 'Charlie'] as const;
const distinctLetters = (w: string): boolean => new Set(w.toLowerCase()).size === w.length;

interface NameP { name: (typeof NAMES)[number] }

const names = generator<NameP>({
  id: 'names',
  skill: 'Count the arrangements of a name whose letters are all different, as in STEP Support Assignment 6 Q2(i).',
  params: (rng) => ({ name: pick(rng, NAMES) }),
  sane: ({ name }) => (distinctLetters(name) ? null : 'repeated letters'),
  problem: ({ name }) => ({
    prompt: t`In how many ways can ${name} arrange the letters of the name ${name}?`,
    answer: { kind: 'exact', expected: String(factorial(name.length)) },
    solution: [
      t`${name} has ${name.length} letters, all different, so every ordering is a different arrangement.`,
      t`That is ${math`${name.length}! = ${factorial(name.length)}`}.`,
    ],
  }),
  solve: ({ name }) => String(permutations(name.length).length),
  misconceptions: ({ name }): Misconception[] => [
    { response: String(name.length), why: t`That is the number of letters. Each ordering of them is an arrangement: there are ${math`${name.length}!`}.` },
    { response: String(name.length ** name.length), why: t`That lets a letter be used more than once. Each letter is used exactly once.` },
  ],
});

// ---------------------------------------------------------------- Cambridge problems

const BEC = ['Ben', 'Elsa', 'Charlie'] as const;
const a6Names = auto({
  id: 'a6-q2-i',
  source: cite('step-f06', 'Q2(i)'),
  title: t`Ben, Elsa, and Charlie`,
  prompt: t`In how many ways can Ben, Elsa, and Charlie each arrange the letters in their names? Fill in the table.`,
  answer: { kind: 'table', columns: [t`name`, t`arrangements`], cell: 'exact', rows: BEC.map((n) => [t`${n}`, null]), expected: BEC.map((n) => String(factorial(n.length))) },
  solution: [
    t`Each name has all its letters different, so its arrangements are the orderings of its letters.`,
    ...BEC.map((n) => t`${n} has ${n.length} letters: ${math`${n.length}! = ${factorial(n.length)}`}.`),
  ],
  reference: BEC.map((n) => String(permutations(n.length).length)),
  verify: () => same('A6 Q2(i): the letters are all different', BEC.every(distinctLetters), true),
  official: { source: cite('step-f06-hints', 'Q2(i)'), answer: ['6', '24', '5040'], agrees: true },
});

/** An extent rings every change (every ordering of the bells) once. */
const extent = (bells: number, id: string, at: string) => auto({
  id,
  source: cite('step-f12', at, true),
  title: t`An extent on ${bells} bells`,
  prompt: t`In change ringing, a change is one ordering of the bells, and an extent rings every possible change exactly once. How many changes are in an extent on ${bells} bells?`,
  answer: { kind: 'exact', expected: String(factorial(bells)) },
  solution: [
    t`The changes are the orderings of ${bells} different bells: ${bells} choices for the first position, ${bells - 1} for the second, and so on.`,
    t`So an extent has ${math`${bells}! = ${factorial(bells)}`} changes.`,
  ],
  reference: String(factorial(bells)),
  verify: () => same(`an extent on ${bells} bells`, permutations(bells).length, factorial(bells)),
  misconceptions: [{ response: String(bells * bells), why: t`Each change is a full ordering of all ${bells} bells: multiply ${bells} by every smaller number, not by itself.` }],
});
const extent6 = extent(6, 'a12-q4-extent-6', 'Q4, discussion of change ringing (six bells, as in Plain Bob Minor)');
const extent8 = extent(8, 'a12-q4-extent-8', 'Q4, discussion of change ringing (the extent on 8 bells rung in 1963)');

// ---------------------------------------------------------------- lesson

const letters = ['A', 'B', 'C'];
const orders = permutations(3).map((p) => p.map((i) => letters[i]).join(''));

const four = permutations(4).length;
/** The number of decimal digits of 52 factorial, computed exactly. */
const digits52 = String(Array.from({ length: 52 }, (_, i) => BigInt(i + 1)).reduce((a, b) => a * b, 1n)).length;

export const factorialTopic: TopicContent = {
  topicId: 'comb.factorial',
  goal: t`Count the orderings of ${mn} different objects as ${math`n!`}, and know why ${ident('0!', '1')}.`,
  objective: t`Count the orderings of ${mn} different objects as ${math`n!`}, and prove it by induction.`,
  why: t`Factorials are the raw material of permutations, combinations, and the binomial theorem, which come next.`,
  minutes: 15,
  lesson: [
    { kind: 'section', title: t`Putting things in order` },
    { kind: 'hook', text: t`A shuffled deck of ${52} cards is almost certainly in an order no deck has ever been in before. How can that be, when people have shuffled cards for centuries? The number of possible orders is so large that the answer has ${digits52} digits.` },
    { kind: 'narrative', text: t`Start small. How many ways can the letters ${letters.join(', ')} be put in order? Listing them: ${computed(orders.join(', '))}. That is ${orders.length} [[arrangement|arrangements]].` },
    { kind: 'narrative', text: t`Listing gets out of hand fast: four letters already give ${four}. So count without listing. The first place can be any of the ${3} letters. Whichever you chose, ${2} remain for the second place, and then ${1} for the last. By the product rule, ${math`${3} \times ${2} \times ${1} = ${factorial(3)}`}.` },
    {
      kind: 'definition',
      name: t`Factorial`,
      formal: t`The [[factorial|factorial]] of a natural number is defined by ${ident('0!', '1')} and ${math`n! = n \times (n - ${1})!`} for ${math`n \ge ${1}`}. So for ${math`n \ge ${1}`}, ${math`n! = n \times (n - ${1}) \times \cdots \times ${2} \times ${1}`}.`,
      plain: t`multiply all the whole numbers from ${mn} down to ${1}. ${math`${4}! = ${4} \times ${3} \times ${2} \times ${1} = ${factorial(4)}`}.`,
    },
    {
      kind: 'table', caption: t`Factorials grow fast.`,
      head: [[mn], [math`n!`]],
      rows: [1, 2, 3, 4, 5, 6, 10].map((n) => [t`${n}`, t`${factorial(n)}`]),
    },
    { kind: 'section', title: t`Why ${math`n!`} counts orderings` },
    { kind: 'theorem', statement: t`For every natural number ${mn}, there are exactly ${math`n!`} ways to arrange ${mn} different objects in a row.` },
    {
      kind: 'steps',
      proof: true,
      steps: [
        { label: t`Base case`, text: t`With ${0} objects there is exactly one arrangement, the empty row, and ${ident('0!', '1')}.`, plain: t`Doing nothing is one way of arranging nothing.` },
        { label: t`Inductive hypothesis`, text: t`Let ${math`n \ge ${1}`}, and assume ${math`n - ${1}`} different objects have ${math`(n - ${1})!`} arrangements.`, plain: t`We use the count for one object fewer.` },
        { label: t`Choose the first place`, text: t`An arrangement of ${mn} objects is a choice of the object in the first place (${mn} ways) followed by an arrangement of the other ${math`n - ${1}`} (${math`(n - ${1})!`} ways, by the hypothesis).`, plain: t`For ${math`n = ${3}`}: pick the first letter, then order the other two.` },
        { label: t`Multiply`, text: t`By the product rule there are ${math`n \times (n - ${1})! = n!`} arrangements.`, plain: t`Each first choice combines with each arrangement of the rest, and different combinations give different rows.` },
      ],
    },
    {
      kind: 'p',
      text: t`The step ${math`n! = n \times (n - ${1})!`} also makes ratios easy: ${math`\frac{${10}!}{${8}!} = ${10} \times ${9} = ${factorial(10) / factorial(8)}`}, because ${math`${10}! = ${10} \times ${9} \times ${8}!`} and the ${math`${8}!`} cancels.`,
      why: { q: t`Why is ${math`${0}!`} equal to ${1} and not ${0}?`, a: t`Two reasons that agree. There is one way to arrange nothing. And the rule ${math`n! = n \times (n - ${1})!`} at ${math`n = ${1}`} says ${ident('1!', '1 * 0!')}, which forces ${ident('0!', '1')}.` },
    },
    quickCheck({
      prompt: t`Work out ${math`\frac{${7}!}{${5}!}`}.`,
      answer: { kind: 'exact', expected: String(factorial(7) / factorial(5)) },
      reference: String(factorial(7) / factorial(5)),
      why: t`${math`${7}! = ${7} \times ${6} \times ${5}!`}, so the ratio is ${math`${7} \times ${6} = ${factorial(7) / factorial(5)}`}.`,
    }),
    {
      kind: 'pitfall',
      claim: t`${math`(${2}n)! = ${2} \times n!`}.`,
      counterexample: t`At ${math`n = ${2}`}: ${math`${4}! = ${factorial(4)}`}, but ${math`${2} \times ${2}! = ${2 * factorial(2)}`}. A factorial multiplies every number up to its argument, so doubling the argument adds many factors.`,
    },
    { kind: 'section', title: t`Bells` },
    { kind: 'p', text: t`Factorials count orderings of real things. In change ringing, a change is one ordering of the bells, and an extent rings every change exactly once. STEP Support Assignment ${12} notes that an extent on ${5} bells is ${math`${5}! = ${factorial(5)}`} changes.` },
    { kind: 'takeaway', text: t`${mn} different objects can be ordered in ${math`n! = n \times (n - ${1}) \times \cdots \times ${1}`} ways, with ${ident('0!', '1')}; use ${math`n! = n \times (n - ${1})!`} to cancel.` },
  ],
  examples: [
    { ...workedCambridge(a6Names), examiner: t`Each count justified by the number of choices for each position, and repeated letters noticed before multiplying.` },
    worked(fixed, { n: 6, rule: 'ends' }, t`Two people at the ends`),
    worked(ratio, { n: 7, k: 2 }, t`Cancelling factorials`),
  ],
  generators: [arrange, ratio, fixed, names],
  mastery: { correctInARow: 3, maxProblems: 10 },
  terms: ['arrangement', 'factorial'],
  cambridge: [extent6, extent8],
  // None fits: the two extents are each one factorial, not a Cambridge-standard problem. A multi-part
  // counting problem from STEP is needed before this topic can be mastered.
  gate: [],
  recall: [
    { front: t`Define ${math`n!`}.`, back: t`${ident('0!', '1')}, and ${math`n! = n \times (n - ${1})!`} for ${math`n \ge ${1}`}.` },
    { front: t`How many orderings have ${mn} different objects?`, back: t`${math`n!`}.` },
    { front: t`Why is ${ident('0!', '1')}?`, back: t`There is one way to arrange nothing, and it keeps ${math`n! = n \times (n - ${1})!`} true at ${math`n = ${1}`}.` },
  ],
  proofOrder: [
    {
      title: t`${mn} objects have ${math`n!`} orderings`,
      steps: [
        t`Base case: ${0} objects have one ordering, and ${ident('0!', '1')}.`,
        t`Assume ${math`n - ${1}`} objects have ${math`(n - ${1})!`} orderings.`,
        t`Choose the first object in ${mn} ways, then order the rest in ${math`(n - ${1})!`} ways.`,
        t`By the product rule that is ${math`n!`} orderings.`,
      ],
    },
  ],
};
