/** comb.factorial: Factorials and arranging n objects. */
import { factorial, int, pick } from '../math';
import { generator, type Misconception } from '../problem';
import { computed, computedMath as cm, dmath, ident, math, t } from '../rich';
import { worked, type TopicContent } from '../topic';

/** Every ordering of 0 .. n - 1, generated by Heap's algorithm. */
function permutations(n: number): number[][] {
  const a = Array.from({ length: n }, (_, i) => i);
  const out: number[][] = [[...a]];
  const c = Array.from({ length: n }, () => 0);
  for (let i = 1; i < n;) {
    if ((c[i] as number) < i) {
      const j = i % 2 === 0 ? 0 : (c[i] as number);
      [a[j], a[i]] = [a[i] as number, a[j] as number];
      out.push([...a]);
      c[i] = (c[i] as number) + 1;
      i = 1;
    } else {
      c[i] = 0;
      i++;
    }
  }
  return out;
}

const productText = (hi: number, lo = 1): string => Array.from({ length: hi - lo + 1 }, (_, i) => hi - i).join(' * ');
const mn = math`n`;

// ---------------------------------------------------------------- generators

interface ArrangeP { n: number; what: 'books' | 'runners' | 'letters' }

const arrange = generator<ArrangeP>({
  id: 'arrange',
  skill: 'Count the orderings of n different objects.',
  params: (rng) => ({ n: int(rng, 3, 7), what: pick(rng, ['books', 'runners', 'letters'] as const) }),
  sane: ({ n }) => (n >= 3 && n <= 7 ? null : 'out of range'),
  problem: ({ n, what }) => ({
    prompt: what === 'books'
      ? t`In how many different orders can ${n} different books stand on a shelf?`
      : what === 'runners'
        ? t`${n} runners finish a race with no ties. How many different finishing orders are possible?`
        : t`How many different arrangements are there of ${n} different letters, using each letter once?`,
    answer: { kind: 'exact', expected: String(factorial(n)) },
    solution: [
      t`The first place can be filled in ${n} ways, the second in ${n - 1} (one object is used), and so on down to ${1}.`,
      t`By the product rule that is ${cm(`${productText(n)} = ${factorial(n)}`)}, written ${math`${n}!`}.`,
    ],
  }),
  solve: ({ n }) => String(permutations(n).length),
  misconceptions: ({ n }): Misconception[] => [
    { response: String(n ** n), why: t`That allows the same object in several places. Each object is used once, so each place has one fewer choice than the one before.` },
    { response: String((n * (n + 1)) / 2), why: t`That adds ${math`${n} + ${n - 1} + \cdots + ${1}`}. The choices happen one after another, so multiply them.` },
    { response: String(n), why: t`There are ${n} choices for the first place alone. Multiply by the choices for every later place too.` },
  ],
});

interface RatioP { n: number; k: number }

const ratio = generator<RatioP>({
  id: 'ratio',
  skill: 'Simplify a ratio of factorials by cancelling.',
  params: (rng) => ({ n: int(rng, 2, 10), k: int(rng, 1, 3) }),
  sane: ({ n, k }) => (n >= 2 && n <= 10 && k >= 1 && k <= 3 ? null : 'out of range'),
  problem: ({ n, k }) => {
    const value = factorial(n + k) / factorial(n);
    return {
      prompt: t`Work out ${math`\frac{${n + k}!}{${n}!}`} without a calculator.`,
      answer: { kind: 'exact', expected: String(value) },
      solution: [
        t`Write the top as ${math`${n + k}! = ${cm(productText(n + k, n + 1))} \times ${n}!`}.`,
        t`The ${math`${n}!`} cancels, leaving ${cm(`${productText(n + k, n + 1)} = ${value}`)}.`,
      ],
    };
  },
  solve: ({ n, k }) => {
    let top = 1n;
    for (let i = 2n; i <= BigInt(n + k); i++) top *= i;
    let bottom = 1n;
    for (let i = 2n; i <= BigInt(n); i++) bottom *= i;
    return (top / bottom).toString();
  },
  misconceptions: ({ n, k }): Misconception[] => [
    { response: String(factorial(k)), why: t`Factorials do not cancel like that: ${math`\frac{${n + k}!}{${n}!}`} is not ${math`\left(\frac{${n + k}}{${n}}\right)!`} or ${math`${k}!`}. Write out the top until ${math`${n}!`} appears, then cancel it.` },
    { response: String(n + k), why: t`That keeps only the first factor. The top is ${math`${n + k} \times ${n + k - 1} \times \cdots`}; cancel ${math`${n}!`} and multiply every factor that is left.` },
    { response: String(factorial(n + k) - factorial(n)), why: t`A fraction bar means divide, not subtract. Cancel ${math`${n}!`} from the top and the bottom.` },
  ],
});

interface FixedP { n: number; rule: 'first' | 'ends' }

const fixed = generator<FixedP>({
  id: 'fixed',
  skill: 'Count orderings when some positions are fixed.',
  params: (rng) => ({ n: int(rng, 4, 7), rule: pick(rng, ['first', 'ends'] as const) }),
  sane: ({ n }) => (n >= 4 && n <= 7 ? null : 'out of range'),
  problem: ({ n, rule }) => {
    if (rule === 'first') {
      return {
        prompt: t`${n} friends, including Ana, stand in a line for a photo. Ana must stand first. How many orders are possible?`,
        answer: { kind: 'exact', expected: String(factorial(n - 1)) },
        solution: [
          t`Ana's place is fixed, so only the other ${n - 1} people are arranged.`,
          t`That is ${math`${n - 1}! = ${factorial(n - 1)}`}.`,
        ],
      };
    }
    return {
      prompt: t`${n} friends, including Ana and Ben, stand in a line. Ana and Ben must stand at the two ends. How many orders are possible?`,
      answer: { kind: 'exact', expected: String(2 * factorial(n - 2)) },
      solution: [
        t`Ana and Ben fill the two ends in ${2} ways: Ana left and Ben right, or the other way round.`,
        t`The other ${n - 2} people fill the middle in ${math`${n - 2}! = ${factorial(n - 2)}`} ways.`,
        t`By the product rule: ${math`${2} \times ${factorial(n - 2)} = ${2 * factorial(n - 2)}`}.`,
      ],
    };
  },
  solve: ({ n, rule }) => {
    // Person 0 is Ana, person 1 is Ben; count the orderings that obey the rule.
    const ok = (p: number[]): boolean => (rule === 'first' ? p[0] === 0 : (p[0] === 0 && p[n - 1] === 1) || (p[0] === 1 && p[n - 1] === 0));
    return String(permutations(n).filter(ok).length);
  },
  misconceptions: ({ n, rule }): Misconception[] => rule === 'first'
    ? [
      { response: String(factorial(n)), why: t`That counts every order, including those where Ana is not first. Fix Ana and arrange only the others.` },
      { response: String(n * factorial(n - 1)), why: t`Ana's place is fixed: there is ${1} way to place her, not ${n}. Arrange only the other ${n - 1}.` },
    ]
    : [
      { response: String(factorial(n - 2)), why: t`That fixes Ana on the left and Ben on the right. They can also swap ends, which doubles the count.` },
      { response: String(factorial(n)), why: t`That counts every order. Place Ana and Ben at the ends first, then arrange the others in the middle.` },
    ],
});

// ---------------------------------------------------------------- lesson

const letters = ['A', 'B', 'C'];
const orders = permutations(3).map((p) => p.map((i) => letters[i]).join(''));

export const factorialTopic: TopicContent = {
  topicId: 'comb.factorial',
  goal: t`Count the orderings of ${mn} different objects as ${math`n!`}, and know why ${ident('0!', '1')}.`,
  lesson: [
    { kind: 'p', text: t`How many ways can the letters ${letters.join(', ')} be put in order? Listing them: ${computed(orders.join(', '))}. That is ${orders.length} [[arrangement|arrangements]].` },
    { kind: 'p', text: t`The product rule explains the count. The first place has ${3} choices, the second has ${2} left, and the last has ${1}: ${math`${3} \times ${2} \times ${1} = ${factorial(3)}`}.` },
    { kind: 'rule', text: t`The [[factorial|factorial]] of ${mn}, written ${math`n!`}, is ${dmath`n! = n \times (n - ${1}) \times \cdots \times ${2} \times ${1}.`} It counts the orderings of ${mn} different objects.` },
    {
      kind: 'table', caption: t`Factorials grow fast.`,
      head: [[mn], [math`n!`]],
      rows: [1, 2, 3, 4, 5, 6, 10].map((n) => [t`${n}`, t`${factorial(n)}`]),
    },
    { kind: 'p', text: t`Each factorial is the one before it times ${mn}: ${math`n! = n \times (n - ${1})!`}. For example ${math`${5}! = ${5} \times ${4}! = ${5} \times ${factorial(4)} = ${factorial(5)}`}. This makes ratios easy: ${math`\frac{${10}!}{${8}!} = ${10} \times ${9} = ${factorial(10) / factorial(8)}`}.` },
    { kind: 'p', text: t`By definition ${ident('0!', '1')}. There is exactly one way to arrange nothing, and it keeps the rule above true at ${math`n = ${1}`}: ${ident('1!', '1 * 0!')}.` },
  ],
  examples: [
    worked(arrange, { n: 5, what: 'books' }, t`Books on a shelf`),
    worked(fixed, { n: 6, rule: 'ends' }, t`Two people at the ends`),
    worked(ratio, { n: 7, k: 2 }, t`Cancelling factorials`),
  ],
  generators: [arrange, ratio, fixed],
  mastery: { correctInARow: 3, maxProblems: 10 },
  terms: ['arrangement', 'factorial'],
};
