/**
 * alg.recurrence-sequences: sequences generated by u_(n+1) = f(u_n) (and u_(n+2) = f(u_(n+1),
 * u_n)), and whether they converge, are periodic, or diverge; a limit found as a fixed point.
 * From the STEP specification ("sequences generated by a simple relation of the form
 * x_(n+1) = f(x_n) ... periodic sequences") and STEP Support Assignments 11, Q1(i) and 15,
 * Q2 and Q3 (2006 STEP II Q1: the periods in (i), the limit 36 in (ii)), all checked against
 * the hints and by iterating.
 */
import { auto, cite, same, supervision, withUses } from '../cambridge';
import { add, div, int, pick, q, str, sub, type Rational } from '../math';
import { generator, type Misconception } from '../problem';
import { listOf, math, t } from '../rich';
import { checkFrom, worked, workedCambridge, type TopicContent } from '../topic';

const [mn, ml, mk] = [math`n`, math`l`, math`k`];

// ---------------------------------------------------------------- generators

interface LinP { a: number; b: number; u1: number; k: number }
const linTerms = ({ a, b, u1 }: LinP, n: number): number[] => {
  const u = [u1];
  while (u.length < n) u.push(a * (u[u.length - 1] as number) + b);
  return u;
};

const iterGen = generator<LinP>({
  id: 'iterate',
  skill: 'Generate terms of u_(n+1) = a u_n + b from u_1, keeping count of the index.',
  quick: true,
  params: (rng) => {
    for (;;) {
      const p = { a: pick(rng, [2, 3, -2, 4]), b: int(rng, -5, 5), u1: int(rng, -3, 4), k: int(rng, 4, 6) };
      // Not stuck at a fixed point, so neighbouring terms differ.
      if (new Set(linTerms(p, p.k + 1).slice(p.k - 2)).size === 3) return p;
    }
  },
  sane: (p) => (p.k >= 4 && p.k <= 6 && new Set(linTerms(p, p.k + 1).slice(p.k - 2)).size === 3 ? null : 'out of range'),
  problem: (p) => {
    const u = linTerms(p, p.k + 1);
    return {
      prompt: t`A sequence has ${math`u_{${1}} = ${p.u1}`} and ${math`u_{n + ${1}} = ${p.a}u_{n} ${p.b < 0 ? '-' : '+'} ${Math.abs(p.b)}`}. Find ${math`u_{${p.k}}`}.`,
      answer: { kind: 'exact', expected: String(u[p.k - 1]) },
      solution: [t`Apply the rule ${p.k - 1} times from ${math`u_{${1}}`}: ${math`${listOf(u.slice(0, p.k))}`}. So ${math`u_{${p.k}} = ${u[p.k - 1] as number}`}.`],
    };
  },
  solve: (p) => {
    let x = p.u1;
    for (let i = 1; i < p.k; i++) x = p.a * x + p.b;
    return String(x);
  },
  misconceptions: (p): Misconception[] => {
    const u = linTerms(p, p.k + 1);
    return [
      { response: String(u[p.k - 2]), why: t`That is ${math`u_{${p.k - 1}}`}. From ${math`u_{${1}}`} to ${math`u_{${p.k}}`} takes ${p.k - 1} steps.` },
      { response: String(u[p.k]), why: t`That is ${math`u_{${p.k + 1}}`}, one step too many: ${math`u_{${1}}`} is the first term.` },
    ];
  },
});

interface FixP { a: Rational; b: number }

const fixGen = generator<FixP>({
  id: 'fixed-point',
  skill: 'Find the limit of u_(n+1) = a u_n + b with |a| < 1 as the fixed point b/(1 - a).',
  params: (rng) => ({ a: pick(rng, [q(1, 2), q(1, 3), q(2, 3), q(-1, 2), q(3, 4), q(-1, 3), q(1, 4)]), b: int(rng, 1, 12) }),
  sane: ({ a }) => (Math.abs(Number(a.num)) < Number(a.den) ? null : 'need |a| < 1'),
  problem: ({ a, b }) => {
    const l = div(q(b), sub(q(1), a));
    return {
      prompt: t`The sequence ${math`u_{${1}} = ${0}`}, ${math`u_{n + ${1}} = ${a}u_{n} + ${b}`} converges. Find its limit.`,
      answer: { kind: 'exact', expected: str(l) },
      solution: [
        t`If ${math`u_{n} \to l`}, then also ${math`u_{n + ${1}} \to l`}, and by the limit laws ${math`${a}u_{n} + ${b} \to ${a}l + ${b}`}. So ${math`l = ${a}l + ${b}`}.`,
        t`Then ${math`l\left(${1} - ${a}\right) = ${b}`}, so ${math`l = \frac{${b}}{${sub(q(1), a)}} = ${l}`}.`,
      ],
    };
  },
  solve: ({ a, b }) => {
    let x = 0;
    const af = Number(a.num) / Number(a.den);
    for (let i = 0; i < 300; i++) x = af * x + b;
    const l = div(q(b), sub(q(1), a));
    return Math.abs(x - Number(l.num) / Number(l.den)) < 1e-9 ? str(l) : 'x';
  },
  misconceptions: ({ a, b }): Misconception[] => [
    { response: String(b), why: t`${b} is added each step, but the ${math`${a}u_{n}`} part also contributes. Solve ${math`l = ${a}l + ${b}`}.` },
    { response: str(div(q(b), sub(q(1), q(-a.num, a.den)))), why: t`Move ${math`${a}l`} to the left: ${math`l - ${a}l = ${b}`}, so divide by ${math`${1} - a`}, not ${math`${1} + a`}.` },
  ],
});

type PerKind = 'diff' | 'recip' | 'mobius';
interface PerP { kind: PerKind; x: number; y: number }

function perTerms({ kind, x, y }: PerP, n: number): Rational[] {
  const u: Rational[] = [q(x)];
  if (kind === 'diff') u.push(q(y));
  while (u.length < n) {
    const last = u[u.length - 1] as Rational;
    if (kind === 'diff') u.push(sub(last, u[u.length - 2] as Rational));
    else if (kind === 'recip') u.push(div(q(y), last));
    else u.push(div(q(1), sub(q(1), last)));
  }
  return u;
}
const periodOf = (u: Rational[]): number => {
  for (let p = 1; p <= 12; p++) if (u.slice(0, 24).every((v, i) => i + p >= u.length || str(v) === str(u[i + p] as Rational))) return p;
  return 0;
};

const perGen = generator<PerP>({
  id: 'period',
  skill: 'Find the period of a periodic sequence by computing terms until they repeat.',
  params: (rng) => {
    for (;;) {
      const kind = pick(rng, ['diff', 'recip', 'mobius'] as const);
      const p: PerP = kind === 'diff' ? { kind, x: int(rng, -5, 6), y: int(rng, -5, 6) } : kind === 'recip' ? { kind, x: int(rng, 2, 7), y: pick(rng, [6, 10, 12, 24, 30]) } : { kind, x: int(rng, 2, 9), y: 0 };
      const per = periodOf(perTerms(p, 40));
      if (per > 1) return p;
    }
  },
  sane: (p) => (periodOf(perTerms(p, 40)) > 1 ? null : 'must be periodic but not constant'),
  problem: (p) => {
    const u = perTerms(p, 8);
    const rule = p.kind === 'diff' ? math`u_{${1}} = ${p.x},\ u_{${2}} = ${p.y},\ u_{n + ${2}} = u_{n + ${1}} - u_{n}` : p.kind === 'recip' ? math`u_{${1}} = ${p.x},\ u_{n + ${1}} = \frac{${p.y}}{u_{n}}` : math`u_{${1}} = ${p.x},\ u_{n + ${1}} = \frac{${1}}{${1} - u_{n}}`;
    const per = periodOf(perTerms(p, 40));
    return {
      prompt: t`The sequence ${rule} is periodic. What is its period (the smallest ${math`p \ge ${1}`} with ${math`u_{n + p} = u_{n}`} for all ${mn})?`,
      answer: { kind: 'exact', expected: String(per) },
      solution: [
        t`Compute terms: ${u.map((v) => t`${math`${v}`}`).flatMap((r, i) => (i === 0 ? [...r] : [...t`, `, ...r]))}, ...`,
        t`The values return to the start after ${per} steps${p.kind === 'diff' ? t` (and so do the pairs of consecutive values, which is what the two-term rule needs)` : t``}, and not sooner. So the period is ${per}.`,
      ],
    };
  },
  solve: (p) => {
    // Compare the sequence with its shifts numerically.
    const u = perTerms(p, 50).map((v) => Number(v.num) / Number(v.den));
    for (let s = 1; s < 20; s++) if (u.slice(0, 30).every((v, i) => Math.abs(v - (u[i + s] as number)) < 1e-12)) return String(s);
    return '0';
  },
  misconceptions: (p): Misconception[] => {
    const per = periodOf(perTerms(p, 40));
    return [2, 3, 6].filter((x) => x !== per).map((x) => ({
      response: String(x),
      why: x === 2 ? t`Two terms repeating is period ${2}; check further: compute until the first value comes back and then the next one matches too.` : t`Write out more terms; the values return to the start after ${per} steps.`,
    }));
  },
});

interface KP { c: number; m: number }

const kGen = generator<KP>({
  id: 'constant-k',
  skill: 'Choose the constant in u_(n+1) = k - m/u_n so that the sequence from u_1 is constant: k = u_1 + m/u_1.',
  params: (rng) => {
    const c = pick(rng, [1, 2, 3, 4, 6]);
    return { c, m: c * int(rng, 2, 12) };
  },
  sane: ({ c, m }) => (m % c === 0 ? null : 'c must divide m'),
  problem: ({ c, m }) => ({
    prompt: t`The sequence ${math`u_{${1}} = ${c}`}, ${math`u_{n + ${1}} = k - \frac{${m}}{u_{n}}`} is constant. Find ${mk}.`,
    answer: { kind: 'exact', expected: String(c + m / c) },
    solution: [
      t`Constant means ${math`u_{${2}} = u_{${1}}`} (then every later term repeats the step): ${math`k - \frac{${m}}{${c}} = ${c}`}.`,
      t`So ${math`k = ${c} + ${m / c} = ${c + m / c}`}.`,
    ],
  }),
  solve: ({ c, m }) => {
    for (let k = -100; k <= 200; k++) if (k - m / c === c) return String(k);
    return 'x';
  },
  misconceptions: ({ c, m }): Misconception[] => [
    { response: String(c - m / c), why: t`Solve ${math`k - \frac{${m}}{${c}} = ${c}`}: add ${math`\frac{${m}}{${c}}`} to both sides.` },
    { response: String(m / c), why: t`Set ${math`u_{${2}}`} equal to ${math`u_{${1}} = ${c}`}, then solve for ${mk}: ${math`k = ${c} + ${m / c}`}.` },
  ],
});

// ---------------------------------------------------------------- Cambridge problems

const F15 = 'step-f15';
const F15H = 'step-f15-hints';

/** The terms of u_(n+1) = (2/u_n + u_n)/2 from u_1 = 1, exactly: Newton's method for sqrt 2. */
const newtonTerms = (n: number): Rational[] => {
  const u: Rational[] = [q(1)];
  while (u.length < n) {
    const x = u[u.length - 1] as Rational;
    u.push(div(add(div(q(2), x), x), q(2)));
  }
  return u;
};
const A15IV = newtonTerms(5);
const [n1, n2, n3, n4, n5] = A15IV as [Rational, Rational, Rational, Rational, Rational];
const a15iv = auto({
  id: 'a15-q2-iv',
  source: cite(F15, 'Assignment 15, Q2(iv)'),
  title: t`A sequence that homes in on ${math`\sqrt{${2}}`}`,
  prompt: t`Find the first ${5} terms of the convergent sequence defined by ${math`u_{${1}} = ${1}`} and ${math`u_{n + ${1}} = \frac{${1}}{${2}}\left(\frac{${2}}{u_{n}} + u_{n}\right)`} for ${math`n \ge ${1}`}. By setting ${math`u_{n} = u_{n + ${1}} = l`}, find the limit ${ml} of the sequence. (Type a square root as sqrt(${2}).)`,
  answer: { kind: 'expression', expected: 'sqrt(2)', variables: [] },
  solution: [
    t`Compute: ${math`u_{${1}} = ${n1}`}, ${math`u_{${2}} = \frac{${1}}{${2}}\left(\frac{${2}}{${1}} + ${1}\right) = ${n2}`}, ${math`u_{${3}} = \frac{${1}}{${2}}\left(\frac{${4}}{${3}} + \frac{${3}}{${2}}\right) = ${n3}`}, ${math`u_{${4}} = ${n4}`}, ${math`u_{${5}} = ${n5} \approx ${Number((Number(n5.num) / Number(n5.den)).toFixed(9))}`}.`,
    t`If ${math`u_{n} \to l`} with ${math`l \neq ${0}`}, the theorem on limits gives ${math`l = \frac{${1}}{${2}}\left(\frac{${2}}{l} + l\right)`}. Multiply both sides by ${math`${2}l`}: ${math`${2}l^{${2}} = ${2} + l^{${2}}`}, so ${math`l^{${2}} = ${2}`} and ${math`l = \pm\sqrt{${2}}`}.`,
    t`Every term is positive: ${math`u_{${1}} > ${0}`}, and if ${math`u_{n} > ${0}`} then ${math`\frac{${2}}{u_{n}}`} and ${math`u_{n}`} are positive, so ${math`u_{n + ${1}} > ${0}`}. No term after the first is below ${math`\frac{${1}}{${2}}`}: if ${math`u_{n} \ge ${1}`}, then ${math`u_{n + ${1}} \ge \frac{u_{n}}{${2}} \ge \frac{${1}}{${2}}`}; if ${math`${0} < u_{n} < ${1}`}, then ${math`\frac{${2}}{u_{n}} > ${2}`}, so ${math`u_{n + ${1}} > ${1}`}.`,
    t`So ${math`l \ge \frac{${1}}{${2}}`}: it is not ${0}, and of ${math`\pm\sqrt{${2}}`} it must be ${math`\sqrt{${2}}`}. Already ${math`u_{${5}}`} agrees with ${math`\sqrt{${2}}`} to ${11} decimal places.`,
  ],
  reference: 'sqrt(2)',
  verify: () => {
    const e = same('the first five terms', A15IV.map(str).join(' '), '1 3/2 17/12 577/408 665857/470832');
    if (e !== null) return e;
    const u5 = Number(n5.num) / Number(n5.den);
    return Math.abs(u5 - Math.SQRT2) < 1e-11 && Math.abs(u5 - Math.SQRT2) > 1e-13 ? null : `u5 = ${u5}`;
  },
  misconceptions: [{ response: '-sqrt(2)', why: t`Both ${math`\pm\sqrt{${2}}`} solve ${math`l^{${2}} = ${2}`}, but every term is positive, so the limit cannot be negative.` }],
  official: { source: cite(F15H, 'Assignment 15, Q2(iv)'), answer: 'sqrt(2)', agrees: true },
});

const a15q3c = auto({
  id: 'a15-q3-i-c',
  source: cite(F15, 'Assignment 15, Q3(i)(c)'),
  title: t`Period four`,
  prompt: t`For ${math`u_{${1}} = ${2}`}, ${math`u_{n + ${1}} = k - \frac{${36}}{u_{n}}`}, the condition ${math`u_{${5}} = u_{${1}}`} works out to ${math`k^{${4}} - ${20}k^{${3}} - ${72}k^{${2}} + ${1440}k = ${0}`}. Find the positive value of ${mk} for which the sequence has period ${4}. Type a square root as sqrt(${2}).`,
  answer: { kind: 'expression', expected: '6*sqrt(2)', variables: [] },
  solution: [
    t`${math`k = ${0}`} and ${math`k = ${20}`} are roots (periods ${2} and ${1} also satisfy ${math`u_{${5}} = u_{${1}}`}), so ${math`k`} and ${math`k - ${20}`} are factors: ${math`k(k - ${20})(k^{${2}} - ${72}) = ${0}`}.`,
    t`Period exactly ${4} needs ${math`k^{${2}} = ${72}`}, so ${math`k = \pm ${6}\sqrt{${2}}`}; the positive one is ${math`${6}\sqrt{${2}}`}.`,
  ],
  reference: '6 sqrt(2)',
  verify: () => {
    const k = 6 * Math.SQRT2;
    const u = [2];
    for (let i = 0; i < 8; i++) u.push(k - 36 / (u[u.length - 1] as number));
    const ok = Math.abs((u[4] as number) - 2) < 1e-9 && Math.abs((u[2] as number) - 2) > 1;
    const poly = k ** 4 - 20 * k ** 3 - 72 * k ** 2 + 1440 * k;
    return ok && Math.abs(poly) < 1e-6 ? null : `u = ${u.join(', ')}, polynomial ${poly}`;
  },
  misconceptions: [{ response: 'sqrt(72)/2', why: t`${math`k^{${2}} = ${72}`} gives ${math`k = \sqrt{${72}} = ${6}\sqrt{${2}}`}; there is no halving.` }],
  official: { source: cite(F15H, 'Assignment 15, Q3(i)(c)'), answer: '6 sqrt(2)', agrees: true },
});

const a15q3sup = supervision({
  id: 'a15-q3-i',
  source: cite(F15, 'Assignment 15, Q3(i)'),
  title: t`Constant, period two, period four`,
  prompt: t`(${2006} STEP II, Question ${1}(i).) The sequence of real numbers is defined by ${math`u_{${1}} = ${2}`} and ${math`u_{n + ${1}} = k - \frac{${36}}{u_{n}}`}. Determine the values of ${mk} for which the sequence is (a) constant; (b) periodic with period ${2}; (c) periodic with period ${4}. Explain why ${math`u_{${3}} = u_{${1}}`} (respectively ${math`u_{${5}} = u_{${1}}`}) is enough, and how you exclude the smaller periods.`,
  writeUp: 'proof',
  official: cite(F15H, 'Assignment 15, Q3(i)'),
});

const a11 = auto({
  id: 'a11-q1-i',
  source: cite('step-f11', 'Assignment 11, Q1(i)'),
  title: t`The first triangular number over ${100}`,
  prompt: t`A function ${math`T`} is defined on positive integers by ${math`T(k + ${1}) = T(k) + k + ${1}`} and ${math`T(${1}) = ${1}`}. Find, by calculating the values, the smallest ${mn} such that ${math`T(n) > ${100}`}.`,
  answer: { kind: 'exact', expected: '14' },
  solution: [
    t`${math`T(${2}) = ${1} + ${2} = ${3}`}, ${math`T(${3}) = ${6}`}, ... each adds the next whole number, so ${math`T(n) = ${1} + ${2} + \cdots + n = \frac{n(n + ${1})}{${2}}`}.`,
    t`${math`T(${13}) = ${91}`} and ${math`T(${14}) = ${105}`}, so the smallest ${mn} is ${14}.`,
  ],
  reference: '14',
  verify: () => {
    let T = 1;
    let k = 1;
    while (T <= 100) { T += k + 1; k++; }
    return same('first n', k, 14);
  },
  misconceptions: [{ response: '105', why: t`${105} is the value ${math`T(${14})`}; the question asks for ${mn}.` }, { response: '13', why: t`${math`T(${13}) = ${91}`}, not over ${100}.` }],
  official: { source: cite('step-f11-hints', 'Assignment 11, Q1(i)'), answer: '14', agrees: true },
});

const a15ii = auto({
  id: 'a15-q2-ii',
  source: cite(F15, 'Assignment 15, Q2(ii)'),
  title: t`A two-term rule`,
  prompt: t`Write down the first ${10} terms of ${math`u_{${1}} = ${4}`}, ${math`u_{${2}} = ${1}`}, ${math`u_{n + ${2}} = u_{n + ${1}} - u_{n}`}, and give the period of the sequence.`,
  answer: { kind: 'exact', expected: '6' },
  solution: [t`${math`${4}, ${1}, -${3}, -${4}, -${1}, ${3}, ${4}, ${1}, -${3}, -${4}, \ldots`}: after ${6} terms the pair ${math`${4}, ${1}`} recurs, and a pair of consecutive terms fixes everything after it. So the period is ${6}.`],
  reference: '6',
  verify: () => same('period', periodOf(perTerms({ kind: 'diff', x: 4, y: 1 }, 40)), 6),
  misconceptions: [{ response: '3', why: t`${math`u_{${4}} = -${4}`}, not ${4}: the signs flip after three terms, and return after six.` }],
  official: { source: cite(F15H, 'Assignment 15, Q2(ii)'), answer: '6', agrees: true },
});

const a15iii = auto({
  id: 'a15-q2-iii',
  source: cite(F15, 'Assignment 15, Q2(iii)'),
  title: t`When does the third term return?`,
  prompt: t`For ${math`u_{${1}} = ${2}`} and ${math`u_{n + ${1}} = u_{n}^{${2}} - b`}, find the possible values of ${math`b`} for which ${math`u_{${3}} = u_{${1}}`}. Give both, separated by a comma.`,
  answer: {
    kind: 'witness', count: 2, unordered: true, example: '2, 7',
    check: (vals) => {
      const xs = vals.map((v) => (v.den === 1n ? Number(v.num) : NaN)).sort((x, y) => x - y);
      return xs[0] === 2 && xs[1] === 7 ? null : 'Those are not the values: solve u_3 = 2.';
    },
  },
  solution: [
    t`${math`u_{${2}} = ${4} - b`} and ${math`u_{${3}} = (${4} - b)^{${2}} - b = b^{${2}} - ${9}b + ${16}`}.`,
    t`${math`u_{${3}} = ${2}`} gives ${math`b^{${2}} - ${9}b + ${14} = ${0}`}, so ${math`(b - ${2})(b - ${7}) = ${0}`}: ${math`b = ${2}`} (the sequence is constant at ${2}) or ${math`b = ${7}`} (it alternates ${math`${2}, -${3}, ${2}, \ldots`}, period ${2}).`,
  ],
  reference: '2, 7',
  verify: () => same('roots', [2, 7].every((b) => ((2 * 2 - b) ** 2 - b) === 2), true),
  misconceptions: [{ response: '2, -7', why: t`Expand ${math`(${4} - b)^{${2}} - b - ${2} = b^{${2}} - ${9}b + ${14}`}; its roots are ${2} and ${7}.` }],
  official: { source: cite(F15H, 'Assignment 15, Q2(iii)'), answer: '2, 7', agrees: true },
});

/** Iterate u_(n+1) = f(u_n) from u_1, n times. */
const iterate = (f: (x: number) => number, u1: number, n: number): number => {
  let u = u1;
  for (let i = 0; i < n; i++) u = f(u);
  return u;
};

const a15q3ii = auto({
  id: 'a15-q3-ii',
  source: cite(F15, 'Assignment 15, Q3(ii)'),
  title: t`The limit when ${math`k = ${37}`}`,
  prompt: t`(${2006} STEP II, Question ${1}.) The sequence is defined by ${math`u_{${1}} = ${2}`} and ${math`u_{n + ${1}} = ${37} - \frac{${36}}{u_{n}}`}. Given that it converges to a limit ${math`l`}, and that ${math`u_{n} \ge ${2}`} for all ${mn}, find ${math`l`}.`,
  answer: { kind: 'exact', expected: '36' },
  solution: [
    t`${math`l = ${37} - \frac{${36}}{l}`}, so ${math`l^{${2}} - ${37}l + ${36} = ${0}`}, that is ${math`(l - ${36})(l - ${1}) = ${0}`}.`,
    t`Since ${math`u_{n} \ge ${2}`} for every ${mn}, the limit satisfies ${math`l \ge ${2}`}, which excludes ${1}. So ${math`l = ${36}`}.`,
  ],
  reference: '36',
  verify: () => {
    const l = iterate((x) => 37 - 36 / x, 2, 400);
    return Math.abs(l - 36) < 1e-9 ? null : `iterated to ${l}`;
  },
  misconceptions: [{ response: '1', why: t`${1} solves the fixed-point equation, but every term is at least ${2}, so the limit is too.` }],
  official: { source: cite(F15H, 'Assignment 15, Q3(ii)'), answer: '36', agrees: true },
});

const a15q3iiSup = supervision({
  id: 'a15-q3-ii-proof',
  source: cite(F15, 'Assignment 15, Q3(ii)'),
  title: t`Why the limit is ${36}`,
  prompt: t`(${2006} STEP II, Question ${1}(ii).) For ${math`u_{${1}} = ${2}`}, ${math`u_{n + ${1}} = ${37} - \frac{${36}}{u_{n}}`}, show that ${math`u_{n} \ge ${2}`} for all ${mn}. Given that the sequence converges to a limit ${math`l`}, find ${math`l`}, justifying the choice between the roots, and explain why a limit of terms that are all at least ${2} is itself at least ${2}.`,
  writeUp: 'proof',
  official: cite(F15H, 'Assignment 15, Q3(ii)'),
});

// ---------------------------------------------------------------- lesson

const EXU = linTerms({ a: 2, b: -1, u1: 3, k: 0 }, 6);
// The hook's 1 + 2/u from 1: 1, 3, 5/3, 11/5, 21/11, tending to the fixed point 2.
const EXH: Rational[] = [q(1)];
while (EXH.length < 5) EXH.push(add(q(1), div(q(2), EXH[EXH.length - 1] as Rational)));
const [h1, h2, h3, h4, h5] = EXH as [Rational, Rational, Rational, Rational, Rational];

export const recurrenceSequences: TopicContent = {
  topicId: 'alg.recurrence-sequences',
  goal: t`Generate a sequence from ${math`u_{n + ${1}} = f(u_{n})`}, decide whether it converges, is periodic, or diverges, and find a limit as a fixed point.`,
  objective: t`Run a recurrence, tell convergent, periodic, and divergent behaviour apart, and find limits as fixed points.`,
  why: t`STEP sets recurrences every year, and fixed points reappear in iteration, dynamics, and numerical methods.`,
  minutes: 30,
  lesson: [
    { kind: 'section', title: t`A rule for the next term` },
    { kind: 'hook', text: t`Start at ${1}, and repeatedly replace the number ${math`u`} by ${math`${1} + \frac{${2}}{u}`}. You get ${math`${h1}, ${h2}, ${h3}, ${h4}, ${h5}, \ldots`}, closing in on ${2} from either side. Replace ${math`u`} by ${math`${6} - u`} instead and the numbers bounce between ${1} and ${5} forever. Two tiny rules, very different fates.` },
    {
      kind: 'definition',
      name: t`Recurrence, fixed point, periodic`,
      formal: t`A sequence is defined by a [[recurrence-relation|recurrence relation]] when ${math`u_{${1}}`} is given and ${math`u_{n + ${1}} = f(u_{n})`} for ${math`n \ge ${1}`} (or ${math`u_{n + ${2}} = f(u_{n + ${1}}, u_{n})`}, with two starting terms). A [[fixed-point|fixed point]] of ${math`f`} is a number ${ml} with ${math`f(l) = l`}. The sequence is [[periodic-sequence|periodic]] with period ${math`p`} if ${math`u_{n + p} = u_{n}`} for all ${mn}, with ${math`p`} the smallest such positive integer; it is increasing if ${math`u_{n + ${1}} \ge u_{n}`} for all ${mn}, decreasing if ${math`u_{n + ${1}} \le u_{n}`}.`,
      plain: t`Each term is made from the one before. With ${math`u_{${1}} = ${3}`} and ${math`u_{n + ${1}} = ${2}u_{n} - ${1}`}: ${math`${listOf(EXU)}, \ldots`}, increasing and diverging. A fixed point is a value the rule leaves alone: here ${math`l = ${2}l - ${1}`} gives ${math`l = ${1}`}; start at ${1} and you stay at ${1}.`,
    },
    { kind: 'section', title: t`Limits are fixed points` },
    { kind: 'theorem', statement: t`Suppose ${math`u_{n + ${1}} = f(u_{n})`}, where ${math`f`} is built from ${math`u`} by adding, multiplying and dividing (so the limit laws apply), and ${math`u_{n} \to l`} with ${math`f`} defined at ${ml}. Then ${math`f(l) = l`}.` },
    {
      kind: 'steps',
      proof: true,
      steps: [
        { label: t`Shift the index`, text: t`If ${math`u_{n} \to l`} then ${math`u_{n + ${1}} \to l`}: it is the same list of numbers, starting one later.` },
        { label: t`Apply the limit laws`, text: t`${math`f(u_{n})`} is built from ${math`u_{n}`} by sums, products and quotients (with non-zero limits underneath), so ${math`f(u_{n}) \to f(l)`}.`, plain: t`For ${math`f(u) = ${1} + \frac{${2}}{u}`}: if ${math`u_{n} \to l \neq ${0}`}, then ${math`\frac{${2}}{u_{n}} \to \frac{${2}}{l}`}, so ${math`f(u_{n}) \to ${1} + \frac{${2}}{l} = f(l)`}.` },
        { label: t`Limits are unique`, text: t`The sequence ${math`u_{n + ${1}} = f(u_{n})`} tends to both ${ml} and ${math`f(l)`}, so ${math`f(l) = l`}.` },
      ],
    },
    { kind: 'p', text: t`So to find a limit, solve ${math`l = f(l)`}. But the theorem only says a limit, if there is one, is a fixed point. It does not say the sequence converges, nor which fixed point it picks. For ${math`${1} + \frac{${2}}{u}`} the fixed points solve ${math`l = ${1} + \frac{${2}}{l}`}; multiply by ${ml}: ${math`l^{${2}} - l - ${2} = ${0}`}, that is ${math`(l - ${2})(l + ${1}) = ${0}`}, so ${math`l = ${2}`} or ${math`l = -${1}`}. Which one? Every term from ${1} is at least ${1}, because a positive ${math`u`} makes ${math`\frac{${2}}{u}`} positive and so ${math`${1} + \frac{${2}}{u} > ${1}`}. A limit of terms that are all at least ${1} is at least ${1}, so if the sequence converges, its limit is ${2}, not ${math`-${1}`}.` },
    checkFrom(fixGen, { a: q(1, 2), b: 3 }, t`${math`l = \frac{${1}}{${2}}l + ${3}`} gives ${math`\frac{${1}}{${2}}l = ${3}`}, so ${math`l = ${6}`}.`),
    { kind: 'section', title: t`Periodic sequences` },
    { kind: 'narrative', text: t`If some term equals an earlier one, a one-term rule repeats everything after it: if ${math`u_{m + p} = u_{m}`} then ${math`u_{m + p + ${1}} = f(u_{m + p}) = f(u_{m}) = u_{m + ${1}}`}, and so on. So for a period ${math`p`} it is enough to show ${math`u_{${1} + p} = u_{${1}}`}. For a two-term rule, one repeated value is not enough: a repeated consecutive pair is needed, since the next term depends on two terms. For example, ${math`u_{n + ${1}} = c - u_{n}`} has period ${2} unless ${math`u_{${1}} = \frac{c}{${2}}`}: ${math`u_{${2}} = c - u_{${1}}`} and ${math`u_{${3}} = c - (c - u_{${1}}) = u_{${1}}`}, while ${math`u_{${2}} = u_{${1}}`} only when ${math`u_{${1}} = \frac{c}{${2}}`}.` },
    { kind: 'section', title: t`Where it breaks` },
    { kind: 'pitfall', claim: t`${math`u_{${1}} = ${5}`}, ${math`u_{n + ${1}} = \frac{${1}}{${4}}(u_{n}^{${2}} + ${2})`} converges, to a root of ${math`l = \frac{l^{${2}} + ${2}}{${4}}`}.`, counterexample: t`The terms are ${math`${5}, ${q(27, 4)}, \ldots`} and grow without bound: they start above the fixed point ${math`${2} + \sqrt{${2}}`} and are pushed away from it. Fixed points exist, but the sequence diverges. Solving ${math`l = f(l)`} finds candidates, not a proof of convergence.` },
    { kind: 'pitfall', claim: t`A sequence with ${math`u_{${3}} = u_{${1}}`} has period ${2}.`, counterexample: t`It has period ${2} or ${1}: with ${math`u_{${1}} = ${3}`} and ${math`u_{n + ${1}} = ${6} - u_{n}`}, every term is ${3}, so ${math`u_{${3}} = u_{${1}}`} but the period is ${1}. Rule out the smaller periods separately.` },
    { kind: 'pitfall', claim: t`A periodic sequence converges, since it keeps returning to the same values.`, counterexample: t`${math`${1}, ${5}, ${1}, ${5}, \ldots`} has no limit: the values are ${4} apart, so no number is within ${2} of both, and the terms never settle near one number. A periodic sequence converges only if it is constant.` },
    { kind: 'takeaway', text: t`Compute terms to see the behaviour; a limit, if it exists, solves ${math`l = f(l)`}, and bounds on the terms pick the right root.` },
  ],
  examples: [
    workedCambridge(a15iv),
    worked(perGen, { kind: 'mobius', x: 2, y: 0 }, t`Period three`),
    worked(kGen, { c: 3, m: 12 }, t`The constant sequence`),
  ],
  generators: [iterGen, fixGen, perGen, kGen],
  mastery: { correctInARow: 3, maxProblems: 10 },
  terms: ['recurrence-relation', 'fixed-point', 'periodic-sequence'],
  cambridge: withUses([a15q3c, a15q3sup, a15q3ii, a15q3iiSup, a11, a15ii, a15iii], {
    'a15-q3-i': { sections: ['Periodic sequences'], note: t`Constant, period two, and period four sequences, excluding smaller periods` },
    'a15-q3-i-c': { sections: ['Periodic sequences'], note: t`The value of a parameter for period four, by factorising a quartic` },
    'a15-q3-ii': { sections: ['Limits are fixed points'], note: t`The limit of a recurrence as a fixed point, the root chosen by a bound on the terms` },
    'a15-q3-ii-proof': { sections: ['Limits are fixed points'], note: t`A bound on every term by induction, then the limit of the recurrence as a fixed point` },
  }),
  gate: ['a15-q3-i', 'a15-q3-i-c', 'a15-q3-ii-proof', 'a15-q3-ii'],
  recall: [
    { front: t`If ${math`u_{n + ${1}} = f(u_{n})`} and ${math`u_{n} \to l`}, what equation does ${ml} satisfy, and why?`, back: t`${math`l = f(l)`}: both ${math`u_{n + ${1}}`} and ${math`f(u_{n})`} tend to it.` },
    { front: t`What makes a sequence periodic with period ${math`p`}?`, back: t`${math`u_{n + p} = u_{n}`} for all ${mn}, with ${math`p`} the smallest such positive integer.` },
  ],
  proofOrder: [
    {
      title: t`A limit of ${math`u_{n + ${1}} = f(u_{n})`} is a fixed point`,
      steps: [
        t`Suppose ${math`u_{n} \to l`}.`,
        t`Then ${math`u_{n + ${1}} \to l`}, the same terms one step later.`,
        t`By the limit laws, ${math`f(u_{n}) \to f(l)`}.`,
        t`Since ${math`u_{n + ${1}} = f(u_{n})`} and limits are unique, ${math`l = f(l)`}.`,
      ],
    },
  ],
};

