/** Area `analysis`. Limits and series from Analysis I and Numbers and Sets, plus the two exponential facts. */
import type { Topic } from '@learnhub/mastery';
import { IA_LIMITS, M1_PURE, STEP, STEP_SS, TRIPOS } from '../sources';

export const analysis: Topic[] = [
  {
    id: 'an.sequence-limits',
    title: 'Limits of sequences',
    summary: 'Say what $x_n \\to a$ means and find simple limits such as $1/n$ and $r^n$.',
    level: 'step',
    area: 'analysis',
    prereqs: ['alg.proof-by-induction'],
    encompasses: { 'pre.sequences': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'The limit-of-a-sequence line is a STEP addition (bold italics).', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'an.epsilon-limit',
    title: 'The epsilon definition of convergence',
    summary: 'Prove that a sequence converges straight from the definition, using $|x_n - a| < \\varepsilon$.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.sequence-limits'],
    encompasses: { 'an.sequence-limits': 0.5 },
    sources: [{ doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Covers the modulus inequalities the definition needs, rather than a separate topic.', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'an.limit-algebra',
    title: 'Limits of sums, products, and quotients',
    summary: 'Combine limits of sequences under sums, products, and quotients, with proofs.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.epsilon-limit'],
    encompasses: { 'an.epsilon-limit': 0.6 },
    sources: [{ doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Schedule: "Sums, products and quotients."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'an.monotone-convergence',
    title: 'Bounded monotone sequences converge',
    summary: 'An increasing sequence that is bounded above converges to its least upper bound.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.epsilon-limit'],
    encompasses: { 'an.epsilon-limit': 0.5 },
    sources: [{ doc: TRIPOS, course: 'IA Numbers and Sets', section: 'The real numbers', note: 'Schedule: "convergence of bounded monotonic sequences".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'an.series-convergence',
    title: 'Convergence of an infinite series',
    summary: 'Define the sum of a series as the limit of its partial sums.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.limit-algebra', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'an.limit-algebra': 0.4, 'alg.geometric-sum-to-infinity': 0.5, 'alg.sigma-notation': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Schedule: "Sequences and series in R and C."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'an.nonnegative-series',
    title: 'Series of nonnegative terms',
    summary: 'A nonnegative series converges if its partial sums are bounded; compare and reorder freely.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.series-convergence', 'an.monotone-convergence'],
    encompasses: { 'an.series-convergence': 0.5, 'an.monotone-convergence': 0.5 },
    sources: [{
      doc: TRIPOS,
      course: 'IA Analysis I',
      section: IA_LIMITS,
      note: 'Schedule lists "Comparison and ratio tests". That a nonnegative series has the same sum in any order is not named; countable additivity needs it.',
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'an.exp-series',
    title: 'The exponential series',
    summary: 'Use $e^x = \\sum_{k \\ge 0} \\frac{x^k}{k!}$, for example to sum Poisson probabilities.',
    level: 'step',
    area: 'analysis',
    prereqs: ['comb.factorial', 'alg.geometric-sum-to-infinity', 'calc.differentiation-rules'],
    encompasses: { 'alg.exp-and-ln': 0.3, 'comb.factorial': 0.3, 'alg.geometric-sum-to-infinity': 0.2 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: 'Section A: Pure Mathematics, Further algebra and functions', note: 'Spec: "Recognise and use the series expansion of e^x."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'an.exp-limit',
    title: 'The limit of (1 + x/n)^n',
    summary: 'Show $(1 + x/n)^n \\to e^x$ by taking logs and using the derivative of $\\ln$ at $1$.',
    level: 'step',
    area: 'analysis',
    prereqs: ['calc.derivatives', 'an.sequence-limits'],
    encompasses: { 'calc.derivatives': 0.4, 'alg.exp-and-ln': 0.4, 'an.sequence-limits': 0.4 },
    sources: [{
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PURE}, Exponentials and logarithms`,
      note: 'The spec names "the use of e in continuous compound interest", which is this limit; the limit itself is not stated.',
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'an.absolute-convergence',
    title: 'Absolute convergence',
    summary: 'Show that a series converges if $\\sum |a_n|$ does, and that an absolutely convergent series has the same sum in any order.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.nonnegative-series'],
    encompasses: { 'an.nonnegative-series': 0.6, 'an.series-convergence': 0.5 },
    sources: [{ doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Schedule: "Absolute convergence; absolute convergence implies convergence." Rearrangement is not named; expectation on a countable space needs it.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'an.power-series',
    title: 'Power series and radius of convergence',
    summary: 'Find the radius of convergence of $\\sum a_n x^n$, and differentiate a power series term by term inside it.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.absolute-convergence'],
    encompasses: { 'an.absolute-convergence': 0.6 },
    sources: [{ doc: TRIPOS, course: 'IA Analysis I', section: 'Power series', note: 'Schedule: "Complex power series and radius of convergence." Term-by-term differentiation is the starred item of the schedule.', verified: true }],
    estMinutes: 25,
  },
];
