/**
 * Area `calculus`. Only the calculus that the log n! proof and the exponential limit need,
 * and what Part V's densities, transformations, and Jensen's inequality need (cambridge-batch-2.md).
 */
import type { Topic } from '@learnhub/mastery';
import {
  M1_DIFFERENTIATION, M1_INTEGRATION, M1_PURE, M2_FURTHER_CALCULUS, M3_HYPERBOLIC, STEP, TRIPOS,
} from '../sources';

export const calculus: Topic[] = [
  {
    id: 'calc.derivatives',
    title: 'Differentiating powers, e^x, and ln x',
    summary: 'Differentiate $x^n$, $e^{kx}$, and $\\ln x$, with sums and constant multiples.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['alg.exp-and-ln', 'pre.algebraic-manipulation'],
    encompasses: { 'alg.exp-and-ln': 0.5, 'pre.indices': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Differentiation`, verified: true }],
    estMinutes: 25,
  },
  {
    id: 'calc.definite-integrals',
    title: 'Definite integrals and the fundamental theorem',
    summary: 'Evaluate a definite integral from an antiderivative and read it as an area.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.derivatives'],
    encompasses: { 'calc.derivatives': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Integration`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.integration-by-parts',
    title: 'Integration by parts',
    summary: 'Integrate a product by reversing the product rule, for example the integral of $\\ln x$.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.definite-integrals'],
    encompasses: { 'calc.definite-integrals': 0.6, 'calc.derivatives': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Integration`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.differentiation-rules',
    title: 'The chain, product, and quotient rules',
    summary: 'Differentiate composites, products, and quotients, such as $e^{-x^2/2}$ and $x e^{-x}$.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.derivatives'],
    encompasses: { 'calc.derivatives': 0.7 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Differentiation`, note: 'Spec: "Differentiate using the product rule, the quotient rule, and the chain rule".', verified: true },
      { doc: TRIPOS, course: 'IA Analysis I', section: 'Differentiability', note: 'Schedule: "Derivative of sums and products. The chain rule."', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'calc.substitution',
    title: 'Integration by substitution',
    summary: 'Change the variable of a definite integral, with its limits, to turn it into one you can evaluate.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.definite-integrals', 'calc.differentiation-rules', 'alg.partial-fractions'],
    encompasses: { 'calc.definite-integrals': 0.6, 'calc.differentiation-rules': 0.5 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Integration`, note: 'Spec: "Carry out simple and more complex cases of integration by substitution".', verified: true },
      { doc: TRIPOS, course: 'IA Differential Equations', section: 'Basic calculus', note: 'Schedule: "integration by substitution and parts."', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'calc.improper-integrals',
    title: 'Integrals over infinite ranges',
    summary: 'Evaluate $\\int_a^\\infty f(x) \\, dx$ as the limit of $\\int_a^R f(x) \\, dx$ as $R \\to \\infty$, and decide when it converges.',
    level: 'step',
    area: 'calculus',
    prereqs: ['an.sequence-limits', 'calc.substitution'],
    encompasses: { 'calc.definite-integrals': 0.6, 'an.sequence-limits': 0.4 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 2', section: M2_FURTHER_CALCULUS, note: 'Spec: "Evaluate improper integrals where ... the range of integration extends to infinity."', verified: true },
      { doc: TRIPOS, course: 'IA Analysis I', section: 'Integration', note: 'Schedule: "Improper integrals."', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'calc.convexity',
    title: 'Convex functions',
    summary: 'Recognise a convex function by $f\'\' \\ge 0$ or by its chords lying above the graph, and use that its tangents lie below it.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.stationary-points'],
    encompasses: { 'calc.derivatives': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Differentiation`, note: 'Spec: "the second derivative as the rate of change of gradient; connection to convex and concave sections of curves".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'calc.double-integrals',
    title: 'Double integrals',
    summary: 'Evaluate an integral over a region of the plane as repeated single integrals, including over infinite regions.',
    level: 'tripos-ia',
    area: 'calculus',
    prereqs: ['calc.improper-integrals'],
    encompasses: { 'calc.improper-integrals': 0.5, 'calc.definite-integrals': 0.6 },
    sources: [{ doc: TRIPOS, course: 'IA Vector Calculus', section: 'Integration in R2 and R3', note: 'Schedule: "Surface and volume integrals: definitions, examples using Cartesian, cylindrical and spherical coordinates".', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'calc.jacobians',
    title: 'Change of variables and the Jacobian',
    summary: 'Change variables in a double integral with the Jacobian determinant, as in polar coordinates $dx \\, dy = r \\, dr \\, d\\theta$.',
    level: 'tripos-ia',
    area: 'calculus',
    prereqs: ['calc.double-integrals'],
    encompasses: { 'calc.double-integrals': 0.6, 'calc.substitution': 0.5 },
    sources: [{ doc: TRIPOS, course: 'IA Vector Calculus', section: 'Integration in R2 and R3', note: 'Schedule: "change of variables."', verified: true }],
    estMinutes: 25,
  },
  // Preparation, Stage A (graph/reviews/cambridge-prep.md).
  {
    id: 'calc.stationary-points',
    title: 'Stationary points',
    summary: 'Find where $f\'(x) = 0$ and tell maxima from minima by the sign of $f\'$ either side or by $f\'\'$.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.derivatives'],
    encompasses: { 'calc.derivatives': 0.7 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_DIFFERENTIATION, note: 'Spec: "Apply differentiation to find gradients, tangents and normals, maxima and minima and stationary points".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.curve-sketching',
    title: 'Sketching polynomial curves',
    summary: 'Sketch a cubic or quartic from its roots, turning points, intercept, and end behaviour, and count the real roots of $f(x) = k$ from the sketch.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.stationary-points'],
    encompasses: { 'calc.stationary-points': 0.7, 'calc.derivatives': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_DIFFERENTIATION, note: 'Spec: "Apply the above to curve sketching."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.inflection-points',
    title: 'Points of inflection',
    summary: 'Find where a curve changes between concave and convex, and see why $f\'\'(x) = 0$ is necessary but not sufficient, as for $y = (x - 1)^4$.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.convexity'],
    encompasses: { 'calc.convexity': 0.6, 'calc.derivatives': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_DIFFERENTIATION, note: 'Spec: "Understand and use the second derivative as the rate of change of gradient; connection to convex and concave sections of curves and points of inflection."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'calc.first-principles',
    title: 'Differentiation from first principles',
    summary: 'Differentiate from $\\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}$, using the small angle approximations for $\\sin x$ and $\\cos x$ and series for $\\ln x$.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.derivatives', 'trig.small-angles', 'alg.proof-by-induction'],
    encompasses: { 'calc.derivatives': 0.5, 'trig.small-angles': 0.6, 'trig.compound-angles': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_DIFFERENTIATION, note: 'Spec: "the gradient of the tangent as a limit ... differentiation from first principles for small positive integer powers of x, and for sin x and cos x."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.hyperbolic',
    title: 'Hyperbolic functions',
    summary: 'Define $\\cosh x$ and $\\sinh x$ from $e^x$ and $e^{-x}$, prove $\\cosh^2 x - \\sinh^2 x = 1$ and the addition formulae, and differentiate them.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.first-principles'],
    encompasses: { 'calc.first-principles': 0.4, 'alg.exp-and-ln': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 3', section: M3_HYPERBOLIC, note: 'Spec: "Know, understand and use the definitions of hyperbolic functions" and "Differentiate and integrate hyperbolic functions." STEP Support Assignment 21 builds them from a^x, before STEP 3.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.standard-integrals',
    title: 'Integrating standard functions',
    summary: 'Integrate $e^{kx}$, $\\sin kx$, $\\cos kx$, and $\\frac{f\'(x)}{f(x)}$ by recognising each as a derivative.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.definite-integrals', 'calc.differentiation-rules', 'calc.first-principles'],
    encompasses: { 'calc.definite-integrals': 0.6, 'calc.differentiation-rules': 0.4, 'calc.first-principles': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_INTEGRATION, note: 'Spec: "Know and use the Fundamental Theorem of Calculus, including applications to integration by inspection" and "Integrate e^(kx), sin kx, and cos kx".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.symmetry-integrals',
    title: 'Definite integrals by symmetry',
    summary: 'Evaluate integrals such as $\\int_0^a \\frac{f(x)}{f(x) + f(a - x)} \\, dx = \\frac{a}{2}$ with the substitution $x \\mapsto a - x$.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.substitution', 'calc.standard-integrals'],
    encompasses: { 'calc.substitution': 0.7, 'calc.standard-integrals': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_INTEGRATION, note: 'Spec: "(Integration by substitution includes finding a suitable substitution ...)".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'calc.implicit-differentiation',
    title: 'Implicit differentiation',
    summary: 'Differentiate an equation such as $x^2 + y^2 = 25$ term by term, treating $y$ as a function of $x$, to find gradients and tangents.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.differentiation-rules'],
    encompasses: { 'calc.differentiation-rules': 0.7 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_DIFFERENTIATION, note: 'Spec: "Differentiate simple functions and relations defined implicitly or parametrically, for first and higher derivatives."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'calc.separable-odes',
    title: 'Separable differential equations',
    summary: 'Solve $\\frac{dy}{dx} = f(x)g(y)$ by separating the variables and integrating, and fix the constant from a condition.',
    level: 'step',
    area: 'calculus',
    prereqs: ['calc.standard-integrals', 'alg.partial-fractions'],
    encompasses: { 'calc.standard-integrals': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_INTEGRATION, note: 'Spec: "Evaluate the analytical solution of simple first order differential equations with separable variables, including finding particular solutions."', verified: true }],
    estMinutes: 20,
  },
];
