/**
 * Area `continuous`. Continuous random variables: STEP's densities and the normal
 * distribution (STEP 2 and STEP 3 Statistics), then IA Probability "Continuous random
 * variables" (graph/reviews/cambridge-batch-2.md).
 */
import type { Topic } from '@learnhub/mastery';
import {
  IA_CONTINUOUS_RV, IA_PROB_PART_V, M1_STAT_DIST, M2_PROB_DIST, M3_ALGEBRA_OF_EXPECTATION, STEP, TRIPOS,
} from '../sources';

const M2_DENSITIES = 'Spec: "Understand and use the mathematics of continuous probability density functions and cumulative distribution functions".';

export const continuous: Topic[] = [
  {
    id: 'rv.pdf',
    title: 'Continuous random variables and density functions',
    summary: 'Find probabilities as areas under a density $f$, with $\\int_{-\\infty}^{\\infty} f(x) \\, dx = 1$, and relate $f$ to the distribution function by $f = F\'$.',
    level: 'step',
    area: 'continuous',
    prereqs: ['prob.discrete-distributions', 'calc.improper-integrals', 'calc.integration-by-parts'],
    encompasses: { 'calc.improper-integrals': 0.5, 'calc.definite-integrals': 0.6, 'prob.discrete-distributions': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: M2_PROB_DIST, note: M2_DENSITIES, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.continuous-summaries',
    title: 'Mean, variance, median, and mode of a density',
    summary: 'Compute $E(X) = \\int x f(x) \\, dx$, $E(g(X))$, the variance, the median, and the mode of a given density.',
    level: 'step',
    area: 'continuous',
    prereqs: ['rv.pdf', 'rv.variance'],
    encompasses: { 'rv.pdf': 0.6, 'rv.variance': 0.4, 'calc.definite-integrals': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: M2_PROB_DIST, note: 'Spec: "the calculation of mean, variance, median, mode, and expectation by explicit integration for a given (possibly unfamiliar) distribution".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.cdf-method',
    title: 'Finding densities by the distribution function',
    summary: 'Find the density of $Y = g(X)$ by writing $F_Y(y)$ in terms of $F_X$ and differentiating.',
    level: 'step',
    area: 'continuous',
    prereqs: ['rv.pdf'],
    encompasses: { 'rv.pdf': 0.6, 'calc.differentiation-rules': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 3', section: M3_ALGEBRA_OF_EXPECTATION, note: 'Spec: "Use cumulative distribution functions to calculate the probability density function of a related random variable; for example, X^2 from X."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.normal-distribution',
    title: 'The normal distribution and standardising',
    summary: 'Use the $N(\\mu, \\sigma^2)$ density, standardise to $Z = (X - \\mu)/\\sigma$, and read probabilities from $\\Phi$.',
    level: 'step',
    area: 'continuous',
    prereqs: ['rv.continuous-summaries'],
    encompasses: { 'rv.continuous-summaries': 0.5, 'alg.exp-and-ln': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_STAT_DIST, note: 'Spec: "Understand and use the Normal distribution; find probabilities using the Normal distribution; convert to the standard Normal distribution by translation and scaling."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.normal-approximation',
    title: 'Approximating binomial and Poisson by a normal',
    summary: 'Approximate binomial and Poisson probabilities by a normal with the same mean and variance, with a continuity correction.',
    level: 'step',
    area: 'continuous',
    prereqs: ['prob.normal-distribution', 'prob.binomial-distribution', 'prob.poisson-distribution'],
    encompasses: { 'prob.normal-distribution': 0.6, 'prob.binomial-distribution': 0.4, 'prob.poisson-distribution': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: M2_PROB_DIST, note: 'Spec: "Use the Normal distribution as an approximation to the Binomial distribution or the Poisson distribution".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.exponential-distribution',
    title: 'The exponential distribution and memorylessness',
    summary: 'Use the $\\mathrm{Exp}(\\lambda)$ density $\\lambda e^{-\\lambda x}$ and its memoryless property $P(X > s + t \\mid X > s) = P(X > t)$.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.continuous-summaries', 'prob.conditional-formula'],
    encompasses: { 'rv.continuous-summaries': 0.5, 'prob.conditional-formula': 0.4, 'alg.exp-and-ln': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "Uniform, normal and exponential random variables. Memoryless property of exponential distribution."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'rv.joint-densities',
    title: 'Joint densities, marginals, and independence',
    summary: 'Find probabilities from a joint density by double integrals, find the marginals, and test independence by factorising.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.pdf', 'rv.independence', 'calc.double-integrals'],
    encompasses: { 'calc.double-integrals': 0.6, 'rv.pdf': 0.5, 'rv.independence': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "Joint distributions".', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'rv.transformations',
    title: 'Transforming random variables with Jacobians',
    summary: 'Find the joint density of $(U, V) = T(X, Y)$ by the change of variables formula with the Jacobian.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.joint-densities', 'rv.cdf-method', 'calc.jacobians'],
    encompasses: { 'calc.jacobians': 0.6, 'rv.joint-densities': 0.6, 'rv.cdf-method': 0.3 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "transformation of random variables (including Jacobians), examples."', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'prob.geometric-probability',
    title: 'Geometrical probability',
    summary: 'Compute probabilities as areas for uniform points, as in Buffon\'s needle and Bertrand\'s paradox.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.joint-densities'],
    encompasses: { 'rv.joint-densities': 0.5, 'calc.double-integrals': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "Geometrical probability: Bertrand\'s paradox, Buffon\'s needle."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.simulation',
    title: 'Simulating continuous random variables',
    summary: 'Generate samples by inverting the distribution function, by the Box-Muller transform, and by rejection sampling.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.transformations'],
    encompasses: { 'rv.cdf-method': 0.5, 'rv.transformations': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "Simulation: generating continuous random variables, Box-Muller transform, rejection sampling." No sheet problem (batch 2, question 5).', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.bivariate-normal',
    title: 'Correlation and the bivariate normal',
    summary: 'Define the correlation coefficient and the bivariate normal, and show that jointly normal variables are independent exactly when uncorrelated.',
    level: 'tripos-ia',
    area: 'continuous',
    prereqs: ['rv.transformations', 'rv.covariance', 'prob.normal-distribution'],
    encompasses: { 'rv.covariance': 0.5, 'prob.normal-distribution': 0.5, 'rv.transformations': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_CONTINUOUS_RV, note: 'Schedule: "Correlation coefficient, bivariate normal random variables."', verified: true }],
    estMinutes: 25,
  },
];
