/** Area `coordinate-geometry`. Lines, circles, loci, Euclidean proof, and vectors, for STEP Support Foundation and the NST Maths Workbook (graph/reviews/cambridge-prep.md). */
import type { Topic } from '@learnhub/mastery';
import { M1_ALGEBRA_FUNCTIONS, M1_COORDINATES, M1_VECTORS, M2_FURTHER_VECTORS, STEP } from '../sources';

export const coordinateGeometry: Topic[] = [
  {
    id: 'geom.straight-lines',
    title: 'Straight lines',
    summary: 'Find the equation of a line from a point and a gradient, test for parallel and perpendicular lines, and find the distance between two points.',
    level: 'pre-a-level',
    area: 'coordinate-geometry',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_COORDINATES, note: 'Spec: "the equation of a straight line, including the forms y - y1 = m(x - x1) and ax + by + c = 0; gradient conditions for two straight lines to be parallel or perpendicular."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'geom.euclidean-proof',
    title: 'Proof in Euclidean geometry',
    summary: 'Prove facts about triangles and circles from congruent and isosceles triangles, such as the angle at the centre being twice the angle at the circumference.',
    level: 'pre-a-level',
    area: 'coordinate-geometry',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_COORDINATES, note: 'Spec: "know, understand and use basic circle theorems", starting with "The angle subtended by an arc at the centre is twice the angle it subtends at the circumference."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'geom.circles',
    title: 'Equations of circles',
    summary: 'Write a circle as $(x - a)^2 + (y - b)^2 = r^2$, and find its centre and radius by completing the square.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['geom.straight-lines', 'pre.quadratic-equations'],
    encompasses: { 'geom.straight-lines': 0.4, 'pre.quadratic-equations': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_COORDINATES, note: 'Spec: "the coordinate geometry of the circle including using the equation of a circle in the form (x - a)^2 + (y - b)^2 = r^2; completing the square to find the centre and radius".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'geom.intersections',
    title: 'Intersections of lines and curves',
    summary: 'Find where lines, circles, and ellipses meet by substitution, and use the discriminant to tell crossing, touching, and missing apart.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['geom.circles'],
    encompasses: { 'geom.circles': 0.6, 'pre.quadratic-equations': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "interpret the algebraic solution of equations graphically; use intersection points of graphs to solve equations."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'geom.loci',
    title: 'Loci in coordinates',
    summary: 'Find the equation of the set of points satisfying a distance condition, such as the perpendicular bisector or the circle $AP = 2BP$.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['geom.circles'],
    encompasses: { 'geom.circles': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_COORDINATES, note: 'Spec: "Know, understand and use the coordinate geometry of the circle". STEP Support Assignment 19 (2005 STEP I Q6) sets a circle of Apollonius.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'geom.3d-coordinates',
    title: 'Coordinates in three dimensions',
    summary: 'Find distances, angles, areas, and volumes for points in space, as for the tetrahedron with vertices on the axes.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['trig.sine-cosine-rules'],
    encompasses: { 'trig.sine-cosine-rules': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_VECTORS, note: 'Spec: "Use vectors in two dimensions and in three dimensions" and "calculate the distance between two points represented by position vectors."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'geom.vectors',
    title: 'Vectors and the scalar product',
    summary: 'Add and scale vectors in two and three dimensions, find magnitudes, and use the scalar product for angles and perpendicularity.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['geom.3d-coordinates'],
    encompasses: { 'geom.3d-coordinates': 0.5 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_VECTORS, note: 'Spec: "Calculate the magnitude and direction of a vector" and "Add vectors diagrammatically and perform the algebraic operations of vector addition and multiplication by scalars".', verified: true },
      { doc: STEP, course: 'STEP Mathematics 2', section: M2_FURTHER_VECTORS, note: 'Spec: "Understand and use the scalar product of two vectors, including geometrical interpretation".', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'geom.vector-lines',
    title: 'Vector equations of lines',
    summary: 'Write a line as $\\mathbf{r} = \\mathbf{a} + t\\mathbf{d}$, and decide whether two lines in space meet, are parallel, or are skew.',
    level: 'a-level',
    area: 'coordinate-geometry',
    prereqs: ['geom.vectors', 'geom.straight-lines'],
    encompasses: { 'geom.vectors': 0.6, 'geom.straight-lines': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: M2_FURTHER_VECTORS, note: 'Spec: "Understand and use the vector and Cartesian forms of an equation of a straight line in 3-D."', verified: true }],
    estMinutes: 20,
  },
];
