/** Area `counting`. From the product rule to the binomial theorem. */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_DM, CST_NUMBERS, GCSE, GCSE_NUMBER, STEP, STEP_SS, STEP_SUPPORT_6 } from '../sources';

export const counting: Topic[] = [
  {
    id: 'pre.product-rule',
    title: 'The product rule for counting',
    summary: 'Count outcomes of a sequence of choices by multiplying the number of options at each step.',
    level: 'pre-a-level',
    area: 'counting',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 5: "systematic listing strategies including use of the product rule for counting".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'comb.factorial',
    title: 'Factorials and arranging n objects',
    summary: 'Count the orderings of n distinct objects as n!, with 0! = 1.',
    level: 'a-level',
    area: 'counting',
    prereqs: ['pre.product-rule'],
    encompasses: { 'pre.product-rule': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec: "the notations n! and nCr ... and their algebraic definitions".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'comb.permutations',
    title: 'Permutations of r objects from n',
    summary: 'Count ordered selections of r objects from n as n!/(n - r)!.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.factorial'],
    encompasses: { 'comb.factorial': 0.6, 'pre.product-rule': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec, in bold italics: "Use n! and nCr in the context of permutations and combinations."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'comb.combinations',
    title: 'Combinations and the binomial coefficient',
    summary: 'Count unordered selections of r objects from n as n!/(r!(n - r)!).',
    level: 'a-level',
    area: 'counting',
    prereqs: ['comb.factorial', 'pre.fractions'],
    encompasses: { 'comb.factorial': 0.6, 'pre.product-rule': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'A level states the nCr notation and definition; its use in counting is the bold STEP line.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'comb.repeated-arrangements',
    title: 'Arrangements with repeated objects',
    summary: 'Count arrangements of a word with repeated letters as n! divided by the repeats.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.combinations'],
    encompasses: { 'comb.combinations': 0.6, 'comb.factorial': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: STEP_SUPPORT_6, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'comb.binomial-identities',
    title: 'Symmetry and Pascal\'s rule',
    summary: 'Prove nCr = nC(n - r) and Pascal\'s rule both by algebra and by counting.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.combinations', 'pre.algebraic-manipulation'],
    encompasses: { 'comb.combinations': 0.7, 'pre.fractions': 0.3, 'pre.algebraic-manipulation': 0.3 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
      { doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Pascal\'s Triangle", listed under "Mathematical induction".', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'comb.binomial-theorem',
    title: 'The binomial theorem',
    summary: 'Expand (a + b)^n for a positive integer n and read off sums such as the total 2^n.',
    level: 'a-level',
    area: 'counting',
    prereqs: ['comb.combinations', 'pre.indices', 'pre.algebraic-manipulation'],
    encompasses: { 'comb.combinations': 0.6, 'pre.indices': 0.3, 'pre.algebraic-manipulation': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec: "the binomial expansion of (a + bx)^n for positive integer n".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'comb.binomial-theorem-proof',
    title: 'Proving the binomial theorem by induction',
    summary: 'Prove the binomial theorem by induction on n, with Pascal\'s rule in the inductive step.',
    level: 'tripos-ia',
    area: 'counting',
    prereqs: ['comb.binomial-theorem', 'comb.binomial-identities', 'alg.proof-by-induction'],
    encompasses: { 'comb.binomial-identities': 0.6, 'alg.proof-by-induction': 0.5, 'comb.binomial-theorem': 0.5, 'alg.sigma-notation': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Mathematical induction: Binomial Theorem".', verified: true }],
    estMinutes: 20,
  },
];
