/** Area `elementary-probability`. GCSE, A-level, and STEP probability before the axioms. */
import type { Topic } from '@learnhub/mastery';
import { GCSE, GCSE_PROB, M1_PROB, STEP, STEP_SUPPORT_6 } from '../sources';

export const elementaryProbability: Topic[] = [
  {
    id: 'pre.probability-scale',
    title: 'Probability of equally likely outcomes',
    summary: 'Give a probability on the 0 to 1 scale as favourable over total, and use $P(\\text{not } A) = 1 - P(A)$.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.fractions'],
    encompasses: { 'pre.fractions': 0.3 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Items 2 to 4.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.sample-spaces',
    title: 'Sample spaces for combined experiments',
    summary: 'List or tabulate every outcome of two or more experiments and count the favourable ones.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.probability-scale', 'pre.product-rule'],
    encompasses: { 'pre.probability-scale': 0.5, 'pre.product-rule': 0.4 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 7.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.mutually-exclusive',
    title: 'Mutually exclusive events',
    summary: 'Add probabilities of events that cannot happen together; an exhaustive set sums to one.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.probability-scale', 'pre.set-notation'],
    encompasses: { 'pre.probability-scale': 0.4, 'pre.set-notation': 0.3 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 4.', verified: true }],
    estMinutes: 10,
  },
  {
    id: 'pre.tree-diagrams',
    title: 'Tree diagrams',
    summary: 'Multiply along branches and add across them, with and without replacement.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.sample-spaces'],
    encompasses: { 'pre.sample-spaces': 0.5, 'pre.fractions': 0.3 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 8.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'pre.two-way-tables',
    title: 'Conditional probability from tables and Venn diagrams',
    summary: 'Find a probability given that an event happened by restricting a table or diagram to it.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.tree-diagrams', 'pre.set-notation'],
    encompasses: { 'pre.tree-diagrams': 0.4, 'pre.set-notation': 0.3 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 9.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.addition-rule',
    title: 'The addition rule for two events',
    summary: 'Use $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$ for any two events.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.mutually-exclusive'],
    encompasses: { 'pre.mutually-exclusive': 0.5, 'pre.set-notation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.inclusion-exclusion-three',
    title: 'Inclusion-exclusion for three events',
    summary: 'Find $P(A \\cup B \\cup C)$ by adding singles, subtracting pairs, and adding back the triple.',
    level: 'step',
    area: 'elementary-probability',
    prereqs: ['prob.addition-rule'],
    encompasses: { 'prob.addition-rule': 0.7, 'pre.set-notation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, note: 'The spec states the two-event formula; the three-event case extends it.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.independent-events',
    title: 'Independent events',
    summary: 'Test and use independence of two events through $P(A \\cap B) = P(A)P(B)$.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.tree-diagrams'],
    encompasses: { 'pre.tree-diagrams': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.conditional-formula',
    title: 'The conditional probability formula',
    summary: 'Compute $P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}$ and rearrange it as a multiplication rule.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.two-way-tables'],
    encompasses: { 'pre.two-way-tables': 0.5, 'pre.tree-diagrams': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.counting-probability',
    title: 'Probability by counting',
    summary: 'Find probabilities of equally likely outcomes by counting with permutations and combinations.',
    level: 'step',
    area: 'elementary-probability',
    prereqs: ['comb.permutations', 'comb.combinations', 'pre.sample-spaces'],
    encompasses: { 'comb.combinations': 0.6, 'comb.permutations': 0.5, 'pre.sample-spaces': 0.4 },
    sources: [{
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PROB}, Probability`,
      note: `Spec, in bold italics: "Use combinatorial arguments, including the use of n! and nCr in the context of calculating probabilities." ${STEP_SUPPORT_6}`,
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'prob.discrete-distributions',
    title: 'Discrete probability distributions',
    summary: 'Describe a discrete random variable by a table of values and probabilities that sum to one.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.sample-spaces'],
    encompasses: { 'pre.sample-spaces': 0.4, 'pre.probability-scale': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Statistical distributions`, verified: true }],
    estMinutes: 15,
  },
];
