/** Area `functions-and-graphs`. Functions, curve sketching, inequalities, and the modulus function, as STEP Support Foundation teaches them (graph/reviews/cambridge-prep.md). */
import type { Topic } from '@learnhub/mastery';
import { M1_ALGEBRA_FUNCTIONS, M1_PROOF, STEP } from '../sources';

export const functionsAndGraphs: Topic[] = [
  {
    id: 'ineq.linear-quadratic',
    title: 'Linear and quadratic inequalities',
    summary: 'Solve a quadratic inequality from the sketch of $y = (x - a)(x - b)$, and never multiply by a quantity whose sign you do not know.',
    level: 'a-level',
    area: 'functions-and-graphs',
    prereqs: ['pre.quadratic-equations'],
    encompasses: { 'pre.quadratic-equations': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Solve linear and quadratic inequalities in a single variable and interpret such inequalities graphically".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fn.quadratic-graphs',
    title: 'Graphs of quadratics',
    summary: 'Complete the square to find the vertex of a parabola, and find the greatest and least values of a quadratic on an interval.',
    level: 'a-level',
    area: 'functions-and-graphs',
    prereqs: ['pre.quadratic-equations', 'geom.straight-lines'],
    encompasses: { 'pre.quadratic-equations': 0.6, 'geom.straight-lines': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Work with quadratic functions and their graphs; the discriminant of a quadratic function ... completing the square".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fn.floor-function',
    title: 'The floor function',
    summary: 'Use $[x]$, the greatest integer at most $x$, sketch step graphs, and find areas under them as sums of rectangles.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['pre.remainders'],
    encompasses: { 'pre.remainders': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Understand and use graphs of functions". The floor function is defined in the question (STEP Support Assignment 3, 2004 STEP I Q2); no spec line names it.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'ineq.polynomial-regions',
    title: 'Polynomial inequalities and regions',
    summary: 'Solve $f(x) \\ge 0$ for a factorised polynomial, and shade the regions of the plane where a product of linear factors in $x$ and $y$ has a given sign.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['alg.polynomials', 'ineq.linear-quadratic'],
    encompasses: { 'alg.polynomials': 0.5, 'ineq.linear-quadratic': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Represent linear and quadratic inequalities such as y > x + 1 and y > ax^2 + bx + c graphically."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fn.rational-functions',
    title: 'Sketching rational functions',
    summary: 'Sketch curves such as $y = x + \\frac{1}{x}$ and $y = \\frac{x^2}{x - 1}$ from asymptotes, behaviour near the poles, and turning points.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['calc.stationary-points'],
    encompasses: { 'calc.stationary-points': 0.5, 'calc.derivatives': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "sketch curves defined by simple equations including ... other rational functions ... (including their vertical and horizontal asymptotes); behaviour as x -> infinity".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'ineq.rational',
    title: 'Inequalities with fractions',
    summary: 'Solve inequalities such as $x - \\frac{1}{x} \\ge \\frac{3}{2}$ by multiplying by a square or by splitting into sign cases.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['ineq.linear-quadratic', 'fn.rational-functions', 'trig.right-triangle'],
    encompasses: { 'ineq.linear-quadratic': 0.6, 'fn.rational-functions': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Solve inequalities and interpret them graphically; including, but not limited to, those involving rational algebraic expressions".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'ineq.am-gm',
    title: 'The AM-GM inequality',
    summary: 'Prove $\\frac{a + b}{2} \\ge \\sqrt{ab}$ from $(\\sqrt{a} - \\sqrt{b})^2 \\ge 0$, extend it to four and then three numbers, and say when equality holds.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['proof.direct', 'pre.indices'],
    encompasses: { 'proof.direct': 0.5, 'pre.indices': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "proceeding from given assumptions through a series of logical steps to a conclusion". STEP Support Assignment 8 Q1 proves AM-GM; IA Probability proves the general case from Jensen (ineq.jensen).', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fn.functions',
    title: 'Functions, domain, and range',
    summary: 'Treat a function as a rule with a domain and a range, compose and invert functions, and work with functions defined piecewise, periodically, or by an equation such as $f(x + y) = f(x)f(y)$.',
    level: 'a-level',
    area: 'functions-and-graphs',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Understand and use composite functions; inverse functions and their graphs."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fn.graph-transformations',
    title: 'Transforming graphs',
    summary: 'Sketch $y = af(x)$, $y = f(x) + a$, $y = f(x + a)$, and $y = f(ax)$ from $y = f(x)$, and use a translation to count the roots of $f(x) = k$.',
    level: 'a-level',
    area: 'functions-and-graphs',
    prereqs: ['fn.functions', 'fn.quadratic-graphs'],
    encompasses: { 'fn.functions': 0.5, 'fn.quadratic-graphs': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Understand the effect of simple transformations on the graph of y = f(x) including sketching associated graphs".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fn.modulus',
    title: 'The modulus function',
    summary: 'Solve equations such as $|2x| + |x - 1| = 3$ by splitting at the critical values, and sketch $y = |f(x)|$.',
    level: 'a-level',
    area: 'functions-and-graphs',
    prereqs: ['ineq.linear-quadratic', 'geom.straight-lines'],
    encompasses: { 'ineq.linear-quadratic': 0.4, 'geom.straight-lines': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "sketch curves defined by simple equations including polynomials, the modulus of linear and other functions".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fn.modulus-regions',
    title: 'Regions defined by modulus inequalities',
    summary: 'Sketch regions such as $|x| + |y| \\le 1$ and $|x - 1| - |y + 1| \\le 1$ by drawing the boundary in each quadrant and testing a point.',
    level: 'step',
    area: 'functions-and-graphs',
    prereqs: ['fn.modulus', 'ineq.polynomial-regions'],
    encompasses: { 'fn.modulus': 0.6, 'ineq.polynomial-regions': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Solve inequalities and interpret them graphically; including ... the modulus function."', verified: true }],
    estMinutes: 20,
  },
];
