/** Area `functional-programming`. CS-0 functional programming in OCaml: CS3110 chapters 2 to 5, 8, and 9 and the FoCS 2025-26 notes, each topic citing the FoCS 2026-27 syllabus lecture it prepares (graph/reviews/cambridge-prep.md). */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_FOCS } from '../sources';

export const functionalProgramming: Topic[] = [
  {
    id: 'fp.expressions',
    title: 'OCaml expressions, values, and types',
    summary: 'Evaluate OCaml expressions of type int, float, bool, and string, including if expressions, and read the type the toplevel reports.',
    level: 'a-level',
    area: 'functional-programming',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: CST, course: CST_FOCS, section: 'Introduction to Programming', note: 'Syllabus: "Introduction to integer and floating-point arithmetic." and "Decisions and booleans."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fp.functions',
    title: 'Defining and applying functions',
    summary: 'Define functions with let and fun, apply them to arguments, and see a multi-argument function as one that returns a function.',
    level: 'a-level',
    area: 'functional-programming',
    prereqs: ['fp.expressions'],
    encompasses: { 'fp.expressions': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Introduction to Programming', note: 'Syllabus: "Declaring functions."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fp.recursion',
    title: 'Recursive functions',
    summary: 'Write recursive functions with let rec, and turn a recursion into an iterative, tail-recursive one with an accumulator.',
    level: 'a-level',
    area: 'functional-programming',
    prereqs: ['fp.functions'],
    encompasses: { 'fp.functions': 0.6 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Recursion and Efficiency', note: 'Syllabus: "Examples: Exponentiation and summing integers. Iteration versus recursion."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.complexity',
    title: 'The cost of a function',
    summary: 'Estimate how the running time of a recursive function grows, and state it in O-notation, as $O(n)$ against $O(\\log n)$ for exponentiation.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.recursion'],
    encompasses: { 'fp.recursion': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Recursion and Efficiency', note: 'Syllabus: "Examples of growth rates. Dominance and O-Notation. The costs of some representative functions. Cost estimation."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.lists',
    title: 'Lists and pattern matching',
    summary: 'Build lists with :: and [], take them apart by pattern matching, and write recursive functions such as length, append, and reverse.',
    level: 'a-level',
    area: 'functional-programming',
    prereqs: ['fp.recursion'],
    encompasses: { 'fp.recursion': 0.6 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Lists', note: 'Syllabus: "Basic list operations. Append. Naïve versus efficient functions for length and reverse."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.polymorphism',
    title: 'Polymorphic types',
    summary: 'Read types with type variables, such as \'a in the type of a function from an \'a list to an int, and see how OCaml infers the most general type of a function.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.lists'],
    encompasses: { 'fp.lists': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'More on lists', note: 'Syllabus: "A word on polymorphism."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fp.records-tuples',
    title: 'Tuples and records',
    summary: 'Group values in tuples and records, and take them apart by pattern matching, as zip and unzip do.',
    level: 'a-level',
    area: 'functional-programming',
    prereqs: ['fp.lists'],
    encompasses: { 'fp.lists': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'More on lists', note: 'Syllabus: "Pattern-matching: zip, unzip."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fp.variants',
    title: 'Variants and algebraic data types',
    summary: 'Declare a type by its constructors, such as \'a option, and define functions on it by matching every case.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.records-tuples', 'fp.polymorphism'],
    encompasses: { 'fp.records-tuples': 0.4, 'fp.polymorphism': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Datatypes and trees', note: 'Syllabus: "Pattern-matching and case expressions."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.exceptions',
    title: 'Exceptions',
    summary: 'Raise an exception when a function has no sensible result, and handle it with try ... with.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.variants'],
    encompasses: { 'fp.variants': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Datatypes and trees', note: 'Syllabus: "Exceptions."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'fp.trees',
    title: 'Binary trees',
    summary: 'Define binary trees as a recursive datatype, compute their size and depth, and list their labels in preorder, inorder, and postorder.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.variants'],
    encompasses: { 'fp.variants': 0.6 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Datatypes and trees', note: 'Syllabus: "Binary tree traversal (conversion to lists): preorder, inorder, postorder."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.higher-order',
    title: 'Higher-order functions and currying',
    summary: 'Pass functions as arguments, return them as results, write anonymous functions, and use currying for partial application.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.polymorphism'],
    encompasses: { 'fp.polymorphism': 0.5, 'fp.functions': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Functions as values', note: 'Syllabus: "Nameless functions. Currying."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.map-filter-fold',
    title: 'Map, filter, and fold',
    summary: 'Process lists with map, filter, exists, and fold instead of writing the recursion each time, and chain them into pipelines.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.higher-order'],
    encompasses: { 'fp.higher-order': 0.7 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Functions as values', note: 'Syllabus: "The “apply to all” functional, map. Examples: The predicate functionals filter and exists."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.modules',
    title: 'Modules and interfaces',
    summary: 'Package a data structure in a module with a signature that hides its representation, as for a stack.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.variants'],
    encompasses: { 'fp.variants': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Queues and search strategies', note: 'Syllabus: "Importance of efficient data representation." CS3110 chapter 5 teaches modules; FoCS uses them for queues.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.functional-queues',
    title: 'Functional queues',
    summary: 'Implement a queue as a pair of lists so that each operation costs $O(1)$ amortised, and see why the naive list queue costs $O(n)$.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.modules', 'fp.complexity'],
    encompasses: { 'fp.modules': 0.5, 'fp.complexity': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Queues and search strategies', note: 'Syllabus: "An efficient representation of queues."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.functors',
    title: 'Functors',
    summary: 'Build a module from another module with a functor, as Map.Make and Set.Make build dictionaries and sets from an ordered type.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.modules', 'fp.higher-order'],
    encompasses: { 'fp.modules': 0.6, 'fp.higher-order': 0.3 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Dictionaries and functional arrays', note: 'Syllabus: "Dictionaries". CS3110 Section 5.9 builds them with functors; the FoCS syllabus does not name functors.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.specifications-testing',
    title: 'Specifications and testing',
    summary: 'Write a function\'s specification with its preconditions and postconditions, and test it with black-box and glass-box test cases.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.lists'],
    encompasses: { 'fp.lists': 0.3 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Introduction to Programming', note: 'Syllabus: "The role of abstraction and representation." CS3110 chapter 8 teaches specification and testing; the FoCS syllabus does not name them.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.equational-reasoning',
    title: 'Proving recursive functions correct',
    summary: 'Prove facts about recursive functions, such as that a fast exponentiation agrees with the slow one, by equational reasoning and induction on $n$.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.recursion', 'alg.proof-by-induction'],
    encompasses: { 'fp.recursion': 0.5, 'alg.proof-by-induction': 0.6 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Recursion and Efficiency', note: 'Syllabus: "Examples: Exponentiation and summing integers." CS3110 Section 8.7 proves such functions correct.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.structural-induction',
    title: 'Structural induction',
    summary: 'Prove properties of functions on lists and trees, such as $\\mathrm{rev}(\\mathrm{rev}\\ xs) = xs$, by induction on the structure of the data.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.equational-reasoning', 'fp.trees'],
    encompasses: { 'fp.equational-reasoning': 0.6, 'fp.trees': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Datatypes and trees', note: 'Syllabus: "Binary tree traversal". CS3110 Section 8.8 proves facts about lists and trees by structural induction.', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'fp.binary-search-trees',
    title: 'Binary search trees',
    summary: 'Store a dictionary in a binary search tree, look up and update keys in $O(\\log n)$ when the tree is balanced, and see how insertion order can unbalance it.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.trees', 'fp.complexity'],
    encompasses: { 'fp.trees': 0.6, 'fp.complexity': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Dictionaries and functional arrays', note: 'Syllabus: "Dictionaries: association lists (slow) versus binary search trees. Problems with unbalanced trees."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.red-black-trees',
    title: 'Red-black trees',
    summary: 'Keep a search tree balanced with the red-black invariants, and insert by rebalancing locally.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.binary-search-trees'],
    encompasses: { 'fp.binary-search-trees': 0.7 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Dictionaries and functional arrays', note: 'Syllabus: "Problems with unbalanced trees." CS3110 Section 9.3 solves them with red-black trees.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.references',
    title: 'References and arrays',
    summary: 'Use refs, mutable fields, and arrays, and tell assignment from binding.',
    level: 'step',
    area: 'functional-programming',
    prereqs: ['fp.records-tuples'],
    encompasses: { 'fp.records-tuples': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Elements of procedural programming', note: 'Syllabus: "Address versus contents. Assignment versus binding. Own variables. Arrays, mutable or not."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.hash-tables',
    title: 'Hash tables',
    summary: 'Implement a dictionary as an array of buckets, keep the load factor bounded by resizing, and see why that makes operations $O(1)$ amortised.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.references', 'fp.modules', 'fp.complexity'],
    encompasses: { 'fp.references': 0.4, 'fp.modules': 0.4, 'fp.complexity': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Dictionaries and functional arrays', note: 'Syllabus: "Dictionaries". CS3110 Sections 9.1 and 9.2 implement them as hash tables with amortised analysis.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.lazy-sequences',
    title: 'Lazy sequences',
    summary: 'Represent an infinite sequence by a head and a function that computes the tail on demand, and define take, map, and filter on it.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.higher-order', 'fp.variants'],
    encompasses: { 'fp.higher-order': 0.5, 'fp.variants': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Sequences, or lazy lists', note: 'Syllabus: "Lazy lists. Their implementation in OCaml. Applications, for example Newton-Raphson square roots."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'fp.sorting',
    title: 'Sorting algorithms',
    summary: 'Write insertion sort, mergesort, and quicksort on lists, and compare their costs, $O(n^2)$ against $O(n \\log n)$.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.complexity', 'fp.lists'],
    encompasses: { 'fp.complexity': 0.5, 'fp.lists': 0.5 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Sorting', note: 'Syllabus: "Insertion sort, mergesort, quicksort. Their efficiency."', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'fp.search',
    title: 'Depth-first and breadth-first search',
    summary: 'Search a tree depth first with a stack and breadth first with a queue, and see why breadth first finds the nearest solution.',
    level: 'tripos-ia',
    area: 'functional-programming',
    prereqs: ['fp.functional-queues', 'fp.trees'],
    encompasses: { 'fp.functional-queues': 0.5, 'fp.trees': 0.4 },
    sources: [{ doc: CST, course: CST_FOCS, section: 'Queues and search strategies', note: 'Syllabus: "Depth-first search and its limitations. Breadth-first search (BFS). Implementing BFS using lists."', verified: true }],
    estMinutes: 20,
  },
];
