/** Area `ia-axiomatic`. IA Probability "Axiomatic approach" [5 lectures], except conditioning and distributions. */
import type { Topic } from '@learnhub/mastery';
import { IA_AXIOMATIC, TRIPOS } from '../sources';

export const iaAxiomatic: Topic[] = [
  {
    id: 'prob.axioms',
    title: 'The axioms of probability, countable case',
    summary: 'State the axioms for a countable sample space, including countable additivity.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.classical-probability', 'sets.countable-unions', 'an.nonnegative-series'],
    encompasses: { 'prob.classical-probability': 0.4, 'sets.countable-unions': 0.4, 'an.nonnegative-series': 0.4 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Axioms (countable case)."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.point-mass-spaces',
    title: 'Probability spaces on a countable set',
    summary: 'Build a probability space from point masses $p(\\omega)$ that sum to one, with $P(A)$ the sum over $A$.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axioms', 'prob.discrete-distributions'],
    encompasses: { 'prob.axioms': 0.6, 'an.nonnegative-series': 0.4, 'prob.discrete-distributions': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Probability spaces."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.axiom-consequences',
    title: 'First consequences of the axioms',
    summary: 'Prove the complement rule, monotonicity, and the two-event addition rule from the axioms.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axioms', 'prob.addition-rule'],
    encompasses: { 'prob.axioms': 0.6, 'prob.addition-rule': 0.5 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Not named in the schedule; the standard first results from "Axioms".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.inclusion-exclusion',
    title: 'The inclusion-exclusion formula',
    summary: 'Prove and apply the general inclusion-exclusion formula for $n$ events.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences', 'prob.inclusion-exclusion-three', 'alg.proof-by-induction', 'comb.binomial-theorem'],
    encompasses: { 'prob.inclusion-exclusion-three': 0.7, 'prob.axiom-consequences': 0.5, 'alg.proof-by-induction': 0.4, 'comb.binomial-theorem': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Inclusion-exclusion formula." The binomial theorem gives the counting check that each outcome is counted once.', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'prob.continuity',
    title: 'Continuity of probability measures',
    summary: 'For increasing events, $P(A_n)$ tends to the probability of their union, and dually for decreasing.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences'],
    encompasses: { 'prob.axiom-consequences': 0.5, 'prob.axioms': 0.5, 'an.monotone-convergence': 0.4, 'sets.countable-unions': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Continuity and subadditivity of probability measures."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'prob.subadditivity',
    title: 'Countable subadditivity',
    summary: 'Prove $P$ of a countable union is at most the sum of the probabilities (the union bound).',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences'],
    encompasses: { 'prob.axiom-consequences': 0.5, 'prob.axioms': 0.5, 'an.nonnegative-series': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Continuity and subadditivity of probability measures."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'prob.independence',
    title: 'Independence of several events',
    summary: 'Define mutual independence of a family of events and tell it apart from pairwise independence.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.independent-events', 'prob.axiom-consequences'],
    encompasses: { 'prob.independent-events': 0.6, 'prob.axiom-consequences': 0.3 },
    sources: [{ doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Independence."', verified: true }],
    estMinutes: 20,
  },
];
