/** Area `logic`. Statements, connectives, implication, equivalences, and quantifiers, for CST Discrete Mathematics "Proof". */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_DM, CST_PROOF, M1_ALGEBRA, M1_PROOF, STEP, STEP_SUPPORT } from '../sources';

export const logic: Topic[] = [
  {
    id: 'logic.connectives',
    title: 'And, or, and not',
    summary: 'Combine statements with and, or, and not ($\\land$, $\\lor$, $\\lnot$), and work out the truth of the result with a truth table.',
    level: 'a-level',
    area: 'logic',
    prereqs: [],
    encompasses: {},
    sources: [
      {
        doc: STEP,
        course: 'STEP Mathematics 1',
        section: M1_ALGEBRA,
        note: `Spec: "Express solutions through correct use of 'and' and 'or', or through set notation." Truth tables are not named. ${STEP_SUPPORT[4]}`,
        verified: true,
      },
      { doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "conjunction", "disjunction", "negation".', verified: true },
    ],
    estMinutes: 15,
  },
  {
    id: 'logic.implication',
    title: 'Implication',
    summary: 'Read $P \\Rightarrow Q$ (if $P$ then $Q$), know it is false only when $P$ is true and $Q$ is false, and tell it apart from its converse.',
    level: 'a-level',
    area: 'logic',
    prereqs: ['logic.connectives'],
    encompasses: { 'logic.connectives': 0.5 },
    sources: [
      {
        doc: STEP,
        course: 'STEP Mathematics 1',
        section: M1_PROOF,
        note: 'Spec: "proceeding from given assumptions through a series of logical steps to a conclusion"; the notation list defines p implies q.',
        verified: true,
      },
      { doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "implication".', verified: true },
    ],
    estMinutes: 15,
  },
  {
    id: 'logic.iff',
    title: 'Necessary, sufficient, and if and only if',
    summary: 'Say whether a condition is necessary, sufficient, or both, and prove an if and only if in both directions.',
    level: 'step',
    area: 'logic',
    prereqs: ['logic.implication', 'pre.algebraic-argument'],
    encompasses: { 'logic.implication': 0.7 },
    sources: [
      {
        doc: STEP,
        course: 'STEP Mathematics 1',
        section: M1_PROOF,
        note: 'Spec, in bold italics: "Understand and use the terms \'necessary and sufficient\' and \'if and only if\'."',
        verified: true,
      },
      { doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "bi-implication".', verified: true },
    ],
    estMinutes: 15,
  },
  {
    id: 'logic.equivalences',
    title: 'Logical equivalences',
    summary: 'Rewrite statements with De Morgan\'s laws, double negation, and the contrapositive, and check an equivalence by truth table.',
    level: 'tripos-ia',
    area: 'logic',
    prereqs: ['logic.iff'],
    encompasses: { 'logic.connectives': 0.6, 'logic.implication': 0.5, 'logic.iff': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "logical equivalences".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'logic.quantifiers',
    title: 'For all and there exists',
    summary: 'Read and write statements with the universal and existential quantifiers, $\\forall$ and $\\exists$, over a stated set.',
    level: 'tripos-ia',
    area: 'logic',
    prereqs: ['logic.implication', 'sets.comprehension'],
    encompasses: { 'logic.implication': 0.4, 'sets.comprehension': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "universal quantification", "existential quantification".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'logic.nested-quantifiers',
    title: 'Nested quantifiers',
    summary: 'Read statements with several quantifiers and see why $\\forall x\\, \\exists y$ differs from $\\exists y\\, \\forall x$.',
    level: 'tripos-ia',
    area: 'logic',
    prereqs: ['logic.quantifiers'],
    encompasses: { 'logic.quantifiers': 0.7 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_PROOF,
      note: 'Syllabus: "universal quantification", "existential quantification". Statements with several quantifiers are not named separately.',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'logic.negating-quantifiers',
    title: 'Negating quantified statements',
    summary: 'Negate a statement by swapping $\\forall$ and $\\exists$ and negating the inside, as a counterexample does.',
    level: 'tripos-ia',
    area: 'logic',
    prereqs: ['logic.nested-quantifiers', 'logic.equivalences'],
    encompasses: { 'logic.nested-quantifiers': 0.5, 'logic.equivalences': 0.5, 'logic.quantifiers': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "negation", applied to quantified statements.', verified: true }],
    estMinutes: 15,
  },
];
