/** Area `number-and-algebra`. Fraction, algebra, and index skills, plus e^x and ln x, and the whole-number skills (primes, factors, remainders) under number theory. */
import type { Topic } from '@learnhub/mastery';
import { GCSE, GCSE_ALGEBRA, GCSE_NUMBER, M1_PURE, STEP, STEP_SUPPORT } from '../sources';

export const numberAndAlgebra: Topic[] = [
  {
    id: 'pre.fractions',
    title: 'Fractions and ratios',
    summary: 'Add, multiply, and simplify fractions, and read a ratio as parts of a whole.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 2 and 8 (fraction arithmetic); ratio from "Ratio, proportion and rates of change", items 3 to 8.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.algebraic-manipulation',
    title: 'Expanding, factorising, and simplifying',
    summary: 'Expand brackets, factorise, collect like terms, and simplify algebraic fractions.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_ALGEBRA, note: 'Item 4.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'pre.indices',
    title: 'Laws of indices',
    summary: 'Multiply, divide, and raise powers, including zero, negative, and fractional indices.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 6 and 7; laws of indices also in Algebra item 4.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.exp-and-ln',
    title: 'The exponential function and natural logarithm',
    summary: 'Use $e^x$ and $\\ln x$ as inverse functions and apply the laws of logarithms.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.indices'],
    encompasses: { 'pre.indices': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Exponentials and logarithms`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'pre.primes-and-factors',
    title: 'Primes, factors, and multiples',
    summary: 'Tell primes from composite numbers, and list the factors and multiples of a whole number.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 4: "prime numbers, factors (divisors), multiples".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.prime-factorisation',
    title: 'Prime factorisation',
    summary: 'Write a whole number as a product of prime powers, for example $360 = 2^3 \\times 3^2 \\times 5$.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.primes-and-factors', 'pre.indices'],
    encompasses: { 'pre.primes-and-factors': 0.6, 'pre.indices': 0.3 },
    sources: [{
      doc: GCSE,
      course: 'GCSE Mathematics',
      section: GCSE_NUMBER,
      note: 'Item 4: "prime factorisation, including using product notation and the unique factorisation theorem". Used here; proved in num.fundamental-theorem.',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'pre.hcf-lcm',
    title: 'Highest common factor and lowest common multiple',
    summary: 'Find the HCF and LCM of two numbers by listing and from their prime factorisations.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.prime-factorisation'],
    encompasses: { 'pre.prime-factorisation': 0.6, 'pre.primes-and-factors': 0.4 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 4: "common factors, common multiples, highest common factor, lowest common multiple".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.remainders',
    title: 'Quotient and remainder',
    summary: 'Divide one whole number by another to get a quotient and a remainder smaller than the divisor.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.primes-and-factors'],
    encompasses: { 'pre.primes-and-factors': 0.3 },
    sources: [{
      doc: GCSE,
      course: 'GCSE Mathematics',
      section: GCSE_NUMBER,
      note: `Item 2: "apply the four operations, including formal written methods, to integers". The remainder is not named; it is what short division leaves. ${STEP_SUPPORT[3]}`,
      verified: true,
    }],
    estMinutes: 10,
  },
];
