/** Area `number-and-algebra`. Fraction, algebra, and index skills, plus e^x and ln x, and the whole-number skills (primes, factors, remainders) under number theory. */
import type { Topic } from '@learnhub/mastery';
import {
  GCSE, GCSE_ALGEBRA, GCSE_NUMBER, M1_ALGEBRA, M1_ALGEBRA_FUNCTIONS, M1_EXP_LOG, M1_PURE, M2_FURTHER_ALGEBRA, STEP, STEP_SUPPORT,
} from '../sources';

export const numberAndAlgebra: Topic[] = [
  {
    id: 'pre.fractions',
    title: 'Fractions and ratios',
    summary: 'Add, multiply, and simplify fractions, and read a ratio as parts of a whole.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 2 and 8 (fraction arithmetic); ratio from "Ratio, proportion and rates of change", items 3 to 8.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.algebraic-manipulation',
    title: 'Expanding, factorising, and simplifying',
    summary: 'Expand brackets, factorise, collect like terms, and simplify algebraic fractions.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_ALGEBRA, note: 'Item 4.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'pre.indices',
    title: 'Laws of indices',
    summary: 'Multiply, divide, and raise powers, including zero, negative, and fractional indices.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 6 and 7; laws of indices also in Algebra item 4.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.exp-and-ln',
    title: 'The exponential function and natural logarithm',
    summary: 'Use $e^x$ and $\\ln x$ as inverse functions and apply the laws of logarithms.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.indices'],
    encompasses: { 'pre.indices': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Exponentials and logarithms`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'pre.primes-and-factors',
    title: 'Primes, factors, and multiples',
    summary: 'Tell primes from composite numbers, and list the factors and multiples of a whole number.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 4: "prime numbers, factors (divisors), multiples".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.prime-factorisation',
    title: 'Prime factorisation',
    summary: 'Write a whole number as a product of prime powers, for example $360 = 2^3 \\times 3^2 \\times 5$.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.primes-and-factors', 'pre.indices'],
    encompasses: { 'pre.primes-and-factors': 0.6, 'pre.indices': 0.3 },
    sources: [{
      doc: GCSE,
      course: 'GCSE Mathematics',
      section: GCSE_NUMBER,
      note: 'Item 4: "prime factorisation, including using product notation and the unique factorisation theorem". Used here; proved in num.fundamental-theorem.',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'pre.hcf-lcm',
    title: 'Highest common factor and lowest common multiple',
    summary: 'Find the HCF and LCM of two numbers by listing and from their prime factorisations.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.prime-factorisation'],
    encompasses: { 'pre.prime-factorisation': 0.6, 'pre.primes-and-factors': 0.4 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 4: "common factors, common multiples, highest common factor, lowest common multiple".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'pre.remainders',
    title: 'Quotient and remainder',
    summary: 'Divide one whole number by another to get a quotient and a remainder smaller than the divisor.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.primes-and-factors'],
    encompasses: { 'pre.primes-and-factors': 0.3 },
    sources: [{
      doc: GCSE,
      course: 'GCSE Mathematics',
      section: GCSE_NUMBER,
      note: `Item 2: "apply the four operations, including formal written methods, to integers". The remainder is not named; it is what short division leaves. ${STEP_SUPPORT[3]}`,
      verified: true,
    }],
    estMinutes: 10,
  },
  {
    id: 'pre.quadratic-equations',
    title: 'Solving quadratic equations',
    summary: 'Solve $ax^2 + bx + c = 0$ by factorising, completing the square, or the formula, and tell from the discriminant how many real roots there are.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA, note: 'Spec: "solution of quadratic equations including solving quadratic equations in a function of the unknown." A bridge: the batch 2 sources assume it (STEP 2 Statistics Q5, a quadratic in e^lambda; Sheet 3 Q9; difference equations).', verified: true }],
    estMinutes: 15,
  },
  // Preparation, Stage A (graph/reviews/cambridge-prep.md).
  {
    id: 'alg.surds',
    title: 'Surds',
    summary: 'Simplify surds, expand brackets with them, and rationalise a denominator such as $\\frac{1}{3 + \\sqrt{5}}$.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.indices'],
    encompasses: { 'pre.indices': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Use and manipulate surds, including rationalising the denominator."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.simultaneous-equations',
    title: 'Simultaneous equations',
    summary: 'Solve linear systems in two to four unknowns by elimination, and one linear with one quadratic equation by substitution.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.quadratic-equations'],
    encompasses: { 'pre.quadratic-equations': 0.4, 'pre.algebraic-manipulation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Solve simultaneous equations in two (or more) variables by elimination and by substitution".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'alg.polynomials',
    title: 'Polynomials and the factor theorem',
    summary: 'Find a root by trial, divide out the factor, and write a cubic as a product of linear factors.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.quadratic-equations'],
    encompasses: { 'pre.quadratic-equations': 0.5, 'pre.algebraic-manipulation': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "simple algebraic division; use of the factor theorem and the remainder theorem; use of equating coefficients in identities".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'alg.roots-coefficients',
    title: 'Roots and coefficients',
    summary: 'Relate the roots of a polynomial to its coefficients by comparing $(x - \\alpha)(x - \\beta)(x - \\gamma)$ with the expanded form, and use it to find integer roots.',
    level: 'step',
    area: 'number-and-algebra',
    prereqs: ['alg.polynomials'],
    encompasses: { 'alg.polynomials': 0.6 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Know, understand and use the relationship between the roots and coefficients of quadratic equations."', verified: true },
      { doc: STEP, course: 'STEP Mathematics 2', section: M2_FURTHER_ALGEBRA, note: 'Spec: "the relationship between roots and coefficients of polynomial equations up to quartic and higher degree equations."', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'alg.factorisations',
    title: 'Useful factorisations',
    summary: 'Factorise $a^3 \\pm b^3$ and $a^n - b^n$, and spot a difference of two squares such as $x^4 + 1 = (x^2 + 1)^2 - 2x^2$.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['alg.polynomials', 'alg.geometric-series'],
    encompasses: { 'alg.polynomials': 0.5, 'alg.geometric-series': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Manipulate polynomials algebraically, including expanding brackets and collecting like terms, factorisation".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.partial-fractions',
    title: 'Partial fractions',
    summary: 'Split a fraction such as $\\frac{1}{(x + 1)(x + 2)}$ into simpler fractions by substituting values or equating coefficients.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['alg.polynomials', 'pre.fractions'],
    encompasses: { 'alg.polynomials': 0.4, 'pre.fractions': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "Decompose rational functions into partial fractions (denominators not more complicated than squared linear terms".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.exponential-equations',
    title: 'Exponential equations',
    summary: 'Solve equations in $a^x$ by substituting $y = a^x$ to get a polynomial, keeping only positive $y$, and solve $a^x = b$ with logarithms.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['alg.exp-and-ln', 'pre.quadratic-equations'],
    encompasses: { 'alg.exp-and-ln': 0.5, 'pre.quadratic-equations': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_EXP_LOG, note: 'Spec: "Solve equations of the form a^x = b."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.surd-equations',
    title: 'Equations with square roots',
    summary: 'Solve equations with square roots by substituting for the root or squaring, then check for solutions that squaring introduced.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['alg.surds', 'pre.quadratic-equations'],
    encompasses: { 'alg.surds': 0.4, 'pre.quadratic-equations': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_ALGEBRA_FUNCTIONS, note: 'Spec: "solution of quadratic equations including solving quadratic equations in a function of the unknown."', verified: true }],
    estMinutes: 15,
  },
];
