/** Area `number-theory`. Divisibility, congruences, gcd, and their uses, for CST Discrete Mathematics "Proof" and "Numbers". */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_DM, CST_NUMBERS, CST_PROOF, M1_PROOF, STEP, STEP_SUPPORT } from '../sources';

export const numberTheory: Topic[] = [
  {
    id: 'num.number-systems',
    title: 'Natural numbers, integers, and rationals',
    summary: 'Name the number systems $\\mathbb{N} = \\{0, 1, 2, \\ldots\\}$, $\\mathbb{Z}$, and $\\mathbb{Q}$, and say which of addition, subtraction, multiplication, and division each is closed under.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['sets.comprehension', 'pre.fractions'],
    encompasses: { 'sets.comprehension': 0.3, 'pre.fractions': 0.2 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: 'Syllabus: "Number systems: natural numbers, integers, rationals". The 2025-26 notes start N at 0 (printed page 158), and supervision exercise 1.2.3 is false only because 0 is in N; the STEP notation list starts N at 1, so the lesson says which convention it uses.',
      verified: true,
    }],
    estMinutes: 10,
  },
  {
    id: 'num.divisibility',
    title: 'Divisibility',
    summary: 'Define $a \\mid b$ as $b = ka$ for an integer $k$, and prove facts such as: if $a \\mid b$ and $a \\mid c$, then $a \\mid b + c$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['proof.quantifier-patterns'],
    encompasses: { 'proof.quantifier-patterns': 0.5, 'pre.algebraic-argument': 0.5, 'pre.primes-and-factors': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_PROOF, note: `Syllabus: "Divisibility and congruences." ${STEP_SUPPORT[12]}`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'num.division-theorem',
    title: 'The division theorem',
    summary: 'Prove that for an integer $a$ and a positive integer $b$ there are unique $q$ and $r$ with $a = qb + r$ and $0 \\le r < b$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.number-systems', 'proof.strong-induction', 'proof.quantifier-patterns'],
    encompasses: { 'pre.remainders': 0.6, 'proof.strong-induction': 0.4, 'proof.quantifier-patterns': 0.3 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: 'Syllabus: "The Division Theorem and Algorithm". The algorithm (repeated subtraction, with its invariant) is the existence proof.',
      verified: true,
    }],
    estMinutes: 25,
  },
  {
    id: 'num.congruence',
    title: 'Congruence modulo m',
    summary: 'Define $a \\equiv b \\pmod{m}$ as $m \\mid a - b$, and show it means $a$ and $b$ leave the same remainder.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.divisibility', 'num.division-theorem'],
    encompasses: { 'num.divisibility': 0.6, 'num.division-theorem': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "Divisibility and congruences."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'num.modular-arithmetic',
    title: 'Arithmetic with congruences',
    summary: 'Add, subtract, and multiply congruences, and use them to find remainders such as the last digit of $7^{100}$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.congruence', 'proof.cases'],
    encompasses: { 'num.congruence': 0.7, 'proof.cases': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: `Syllabus: "Modular arithmetic." ${STEP_SUPPORT[17]}`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'num.modular-integers',
    title: 'The integers modulo m',
    summary: 'Work in $\\mathbb{Z}_m$, the residues $0$ to $m - 1$ with addition and multiplication mod $m$, and read its operation tables.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.modular-arithmetic'],
    encompasses: { 'num.modular-arithmetic': 0.6, 'num.number-systems': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "modular integers" (under "Number systems") and "Modular arithmetic".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'num.modular-exponentiation',
    title: 'Powers modulo m by repeated squaring',
    summary: 'Compute $a^k \\bmod m$ with about $\\log_2 k$ squarings, reducing mod $m$ at every step.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.fermat-little'],
    encompasses: { 'num.modular-arithmetic': 0.7, 'pre.indices': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Modular arithmetic". Not named; the Diffie-Hellman method needs it.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'num.gcd',
    title: 'The greatest common divisor',
    summary: 'Define $\\gcd(a, b)$, and prove that $\\gcd(a, b) = \\gcd(b, r)$ when $a = qb + r$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.divisibility', 'pre.hcf-lcm', 'num.division-theorem'],
    encompasses: { 'num.divisibility': 0.6, 'pre.hcf-lcm': 0.4, 'num.division-theorem': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "The greatest common divisor".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'num.euclid-algorithm',
    title: 'Euclid\'s algorithm',
    summary: 'Find $\\gcd(a, b)$ by repeated division with remainder, and prove that it stops with the right answer.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.gcd', 'alg.fibonacci'],
    encompasses: { 'num.gcd': 0.7, 'num.division-theorem': 0.5 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Euclid\'s Algorithm and Theorem".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'num.extended-euclid',
    title: 'The extended Euclidean algorithm',
    summary: 'Run Euclid\'s algorithm backwards to write $\\gcd(a, b) = ax + by$ for integers $x$ and $y$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.euclid-algorithm'],
    encompasses: { 'num.euclid-algorithm': 0.7, 'pre.algebraic-manipulation': 0.3 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: `Syllabus: "The Extended Euclid's Algorithm". ${STEP_SUPPORT[3]}`, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'num.euclid-theorem',
    title: 'Euclid\'s theorem on divisors of a product',
    summary: 'Prove that if $k \\mid mn$ and $\\gcd(k, m) = 1$ then $k \\mid n$, so a prime that divides $mn$ divides $m$ or $n$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.euclid-algorithm', 'num.congruence'],
    encompasses: { 'num.euclid-algorithm': 0.5, 'num.gcd': 0.5, 'num.divisibility': 0.4 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: 'Syllabus: "Euclid\'s Algorithm and Theorem". The page does not state the theorem. The official 2023-24 exercise solutions (Discrete Mathematics Exercises 3, M. Fiore, https://www.cl.cam.ac.uk/teaching/2324/DiscMath/solutions/DiscMaths3_Sols.pdf) use "Euclid\'s Theorem" in the coprime form (from m/g dividing (n/g)(i - j) with gcd(m/g, n/g) = 1, conclude m/g divides i - j) and in the prime form (p divides (n - 1)(n + 1), so p divides one factor). That matches this statement, with the prime case as a corollary. The 2025-26 notes prove it from the linearity of gcd (Lemma 81, printed pages 238 and 239), before the extended algorithm (page 245), so it builds on Euclid\'s algorithm, not on the extended one (batch 1 change 5).',
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'num.modular-inverse',
    title: 'Inverses modulo m',
    summary: 'Show that $a$ has an inverse mod $m$ exactly when $\\gcd(a, m) = 1$, and compute it with the extended Euclidean algorithm.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.extended-euclid', 'num.modular-integers'],
    encompasses: { 'num.extended-euclid': 0.6, 'num.modular-integers': 0.5 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "multiplicative inverses in modular arithmetic".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'num.fundamental-theorem',
    title: 'The fundamental theorem of arithmetic',
    summary: 'Prove that every integer $n \\ge 2$ is a product of primes in exactly one way, up to order.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.euclid-theorem'],
    encompasses: { 'num.euclid-theorem': 0.6, 'proof.strong-induction': 0.5, 'pre.prime-factorisation': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Fundamental Theorem of Arithmetic", listed under "Mathematical induction".', verified: true }],
    estMinutes: 25,
  },
  {
    id: 'num.prime-binomial',
    title: 'A prime divides its inner binomial coefficients',
    summary: 'Prove that $p \\mid \\binom{p}{k}$ for a prime $p$ and $0 < k < p$, from $k \\binom{p}{k} = p \\binom{p - 1}{k - 1}$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.euclid-theorem', 'comb.combinations'],
    encompasses: { 'num.euclid-theorem': 0.5, 'comb.combinations': 0.5 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_PROOF,
      note: 'Syllabus: "Fermat\'s Little Theorem". Not named; the lemma its binomial proof needs.',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'num.fermat-little',
    title: 'Fermat\'s little theorem',
    summary: 'Prove that $a^p \\equiv a \\pmod{p}$ by induction on $a$, and deduce $a^{p - 1} \\equiv 1 \\pmod{p}$ when $p \\nmid a$.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.prime-binomial', 'comb.binomial-theorem', 'num.modular-arithmetic'],
    encompasses: {
      'num.prime-binomial': 0.6, 'comb.binomial-theorem': 0.5, 'num.modular-arithmetic': 0.5,
      'alg.proof-by-induction': 0.3,
    },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_PROOF,
      note: 'Syllabus: "Fermat\'s Little Theorem." The 2025-26 notes prove part 1 from the binomial theorem and p dividing C(p, m), and part 2 from part 1 and Euclid\'s Theorem (printed pages 129, 240, 241); the inverse i^(p - 2) is a consequence (page 244), so the topic does not build on inverses (batch 1 change 6). It states the theorem as a congruence, so it builds on modular arithmetic directly, which the inverse edge used to bring in.',
      verified: true,
    }],
    estMinutes: 25,
  },
  {
    id: 'num.diffie-hellman',
    title: 'The Diffie-Hellman key exchange',
    summary: 'Agree a shared secret $g^{ab} \\bmod p$ over an open channel, and see why its safety rests on discrete logarithms being hard.',
    level: 'tripos-ia',
    area: 'number-theory',
    prereqs: ['num.modular-exponentiation', 'num.modular-integers', 'num.extended-euclid'],
    encompasses: { 'num.modular-exponentiation': 0.7, 'num.modular-integers': 0.4 },
    sources: [{ doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "The Diffie-Hellman cryptographic method."', verified: true }],
    estMinutes: 20,
  },
  // Preparation, Stage A (graph/reviews/cambridge-prep.md).
  {
    id: 'num.linear-diophantine',
    title: 'Integer solutions of linear equations',
    summary: 'Find one integer solution of $ax + by = c$ by trial or reduction, then every solution by adding multiples, as in $8N = 81m + 65$.',
    level: 'step',
    area: 'number-theory',
    prereqs: ['pre.algebraic-argument', 'pre.remainders'],
    encompasses: { 'pre.algebraic-argument': 0.5, 'pre.remainders': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "Understand and use the structure of mathematical proof". STEP Support Assignments 3 and 13 set linear Diophantine equations; the STEP specification has no heading for them.', verified: true }],
    estMinutes: 20,
  },
];
