/** Area `proof`. Proof techniques from GCSE algebraic arguments to strong induction, for CST Discrete Mathematics "Proof" and "Numbers". */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_DM, CST_NUMBERS, CST_PROOF, GCSE, GCSE_ALGEBRA, M1_PROOF, STEP } from '../sources';

export const proof: Topic[] = [
  {
    id: 'pre.algebraic-argument',
    title: 'Algebraic arguments about integers',
    summary: 'Write even, odd, and consecutive integers as 2n, 2n + 1, and n + 1, and use algebra to show a claim holds for all of them.',
    level: 'pre-a-level',
    area: 'proof',
    prereqs: ['pre.algebraic-manipulation', 'pre.primes-and-factors'],
    encompasses: { 'pre.algebraic-manipulation': 0.5, 'pre.primes-and-factors': 0.3 },
    sources: [{
      doc: GCSE,
      course: 'GCSE Mathematics',
      section: GCSE_ALGEBRA,
      note: 'Item 6: "argue mathematically to show algebraic expressions are equivalent, and use algebra to support and construct arguments and proofs".',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'proof.direct',
    title: 'Direct proof',
    summary: 'Prove a statement by a chain of deductions from the assumptions to the conclusion, found first in scratch work.',
    level: 'a-level',
    area: 'proof',
    prereqs: ['logic.implication', 'pre.algebraic-argument'],
    encompasses: { 'pre.algebraic-argument': 0.6, 'logic.implication': 0.5 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "proof by deduction".', verified: true },
      {
        doc: CST,
        course: CST_DM,
        section: CST_PROOF,
        note: 'Syllabus: "Proofs in practice and mathematical jargon" and "Logical deduction: proof strategies and patterns, scratch work".',
        verified: true,
      },
    ],
    estMinutes: 20,
  },
  {
    id: 'proof.cases',
    title: 'Proof by cases',
    summary: 'Split a claim into cases that cover every possibility, such as n even or n odd, and prove each case.',
    level: 'a-level',
    area: 'proof',
    prereqs: ['proof.direct'],
    encompasses: { 'proof.direct': 0.5, 'logic.connectives': 0.4, 'pre.algebraic-argument': 0.4 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "proof by exhaustion".', verified: true },
      { doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "proof strategies and patterns"; cases are how a proof uses a disjunction.', verified: true },
    ],
    estMinutes: 15,
  },
  {
    id: 'proof.counterexample',
    title: 'Disproof by counterexample',
    summary: 'Show that a claim about every case is false by exhibiting one case where it fails.',
    level: 'a-level',
    area: 'proof',
    prereqs: ['proof.direct'],
    encompasses: { 'proof.direct': 0.3, 'pre.algebraic-argument': 0.3 },
    sources: [{
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: M1_PROOF,
      note: 'Spec: "Disproof by counter-example." The CST syllabus does not name it; its objectives ask students to "prove and disprove mathematical statements".',
      verified: true,
    }],
    estMinutes: 10,
  },
  {
    id: 'proof.contradiction',
    title: 'Proof by contradiction',
    summary: 'Assume the statement is false, deduce something impossible, and conclude that the statement is true.',
    level: 'a-level',
    area: 'proof',
    prereqs: ['proof.direct'],
    encompasses: { 'proof.direct': 0.5, 'logic.connectives': 0.3 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "Proof by contradiction", with the irrationality of root 2 as a named example.', verified: true },
      { doc: CST, course: CST_DM, section: CST_PROOF, note: 'Syllabus: "Proof by contradiction."', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'proof.infinitely-many-primes',
    title: 'There are infinitely many primes',
    summary: 'Prove Euclid\'s result: from any finite list of primes, build a number that none of them divides.',
    level: 'a-level',
    area: 'proof',
    prereqs: ['proof.contradiction', 'pre.prime-factorisation', 'pre.remainders'],
    encompasses: { 'proof.contradiction': 0.6, 'pre.prime-factorisation': 0.4, 'pre.remainders': 0.3 },
    sources: [
      { doc: STEP, course: 'STEP Mathematics 1', section: M1_PROOF, note: 'Spec: "the infinity of primes", as an example of proof by contradiction.', verified: true },
      { doc: CST, course: CST_DM, section: CST_NUMBERS, note: 'Syllabus: "Euclid\'s infinity of primes", listed under "Mathematical induction".', verified: true },
    ],
    estMinutes: 20,
  },
  {
    id: 'proof.contrapositive',
    title: 'Proof by contrapositive',
    summary: 'Prove if P then Q by proving the equivalent statement if not Q then not P.',
    level: 'tripos-ia',
    area: 'proof',
    prereqs: ['logic.equivalences', 'proof.direct'],
    encompasses: { 'proof.direct': 0.5, 'logic.equivalences': 0.4 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_PROOF,
      note: 'Syllabus: "proof strategies and patterns" and "logical equivalences"; the contrapositive is the equivalence proofs use most.',
      verified: true,
    }],
    estMinutes: 15,
  },
  {
    id: 'proof.quantifier-patterns',
    title: 'Proving and using quantified statements',
    summary: 'Prove for all by taking an arbitrary element and there exists by giving a witness, and use each kind as an assumption.',
    level: 'tripos-ia',
    area: 'proof',
    prereqs: ['logic.quantifiers', 'proof.counterexample'],
    encompasses: { 'logic.quantifiers': 0.6, 'proof.direct': 0.5, 'proof.counterexample': 0.3 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_PROOF,
      note: 'Syllabus: "Logical deduction: proof strategies and patterns". A counterexample is the witness that disproves a for all.',
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'proof.strong-induction',
    title: 'Strong induction',
    summary: 'Prove P(n) for every n by assuming P(k) for all k below n, for example that every n >= 2 has a prime factor.',
    level: 'tripos-ia',
    area: 'proof',
    prereqs: ['alg.proof-by-induction', 'logic.quantifiers'],
    encompasses: { 'alg.proof-by-induction': 0.7, 'logic.quantifiers': 0.3 },
    sources: [{
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: 'Syllabus: "Mathematical induction". The strong form is not named; the Fundamental Theorem of Arithmetic needs it.',
      verified: true,
    }],
    estMinutes: 20,
  },
];
