/**
 * Area `random-variables`. Discrete random variables: STEP's expectation and variance
 * (Mixed STEP 1, STEP 2, and STEP 3 Statistics), then IA Probability "Discrete random
 * variables" (graph/reviews/cambridge-batch-2.md).
 */
import type { Topic } from '@learnhub/mastery';
import {
  IA_DISCRETE_RV, IA_PROB_PART_V, M1_STAT_DIST, M3_ALGEBRA_OF_EXPECTATION, STEP, TRIPOS,
} from '../sources';

export const randomVariables: Topic[] = [
  {
    id: 'rv.expectation',
    title: 'Expectation of a discrete random variable',
    summary: 'Compute $E(X) = \\sum x \\, P(X = x)$ from a distribution and read it as a long-run average.',
    level: 'step',
    area: 'random-variables',
    prereqs: ['prob.discrete-distributions', 'an.exp-series'],
    encompasses: { 'prob.discrete-distributions': 0.6, 'alg.sigma-notation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_STAT_DIST, note: 'Spec: "calculation of expectation and variance of discrete random variables is included".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'rv.tail-sum',
    title: 'Expectation as a sum of tail probabilities',
    summary: 'For $X$ taking values $0, 1, 2, \\ldots$, show and use $E(X) = \\sum_{n \\ge 1} P(X \\ge n)$.',
    level: 'step',
    area: 'random-variables',
    prereqs: ['rv.expectation'],
    encompasses: { 'rv.expectation': 0.6, 'alg.sigma-notation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_STAT_DIST, note: 'The tail-sum formula is not named; Mixed STEP 1 Statistics Q2 (2010 S1 Q12) asks for it from the expectation the spec names.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'rv.variance',
    title: 'Variance and standard deviation',
    summary: 'Compute $\\mathrm{Var}(X) = E(X^2) - E(X)^2$ and the standard deviation of a discrete random variable.',
    level: 'step',
    area: 'random-variables',
    prereqs: ['rv.expectation'],
    encompasses: { 'rv.expectation': 0.7, 'prob.discrete-distributions': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_STAT_DIST, note: 'Spec: "calculation of expectation and variance of discrete random variables is included".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'rv.expectation-algebra',
    title: 'The algebra of expectation and variance',
    summary: 'Use $E(aX + bY + c) = aE(X) + bE(Y) + c$ and, for independent $X$ and $Y$, $\\mathrm{Var}(aX + bY) = a^2 \\mathrm{Var}(X) + b^2 \\mathrm{Var}(Y)$.',
    level: 'step',
    area: 'random-variables',
    prereqs: ['rv.variance', 'prob.independent-events'],
    encompasses: { 'rv.variance': 0.6, 'rv.expectation': 0.6, 'prob.independent-events': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 3', section: M3_ALGEBRA_OF_EXPECTATION, verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.indicators',
    title: 'Indicator variables and linearity of expectation',
    summary: 'Write a count as a sum of indicator variables and find its mean by linearity, even when the indicators are dependent.',
    level: 'step',
    area: 'random-variables',
    prereqs: ['rv.expectation-algebra'],
    encompasses: { 'rv.expectation-algebra': 0.6, 'rv.expectation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 3', section: M3_ALGEBRA_OF_EXPECTATION, note: 'Indicators are not named; STEP 3 Statistics Q3 (2013 S3 Q12) uses them with the algebra of expectation.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.random-variables',
    title: 'Random variables on a probability space',
    summary: 'Define a random variable as a function on $\\Omega$ and find its distribution from the probability space.',
    level: 'tripos-ia',
    area: 'random-variables',
    prereqs: ['prob.point-mass-spaces'],
    encompasses: { 'prob.point-mass-spaces': 0.5, 'prob.discrete-distributions': 0.5 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Expectation." The section opens with random variables, which it does not name separately.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'rv.expectation-general',
    title: 'Expectation on a countable space',
    summary: 'Define $E(X)$ when the sum converges absolutely, and compute $E(g(X)) = \\sum g(x) P(X = x)$.',
    level: 'tripos-ia',
    area: 'random-variables',
    prereqs: ['rv.random-variables', 'rv.expectation-algebra', 'an.absolute-convergence'],
    encompasses: { 'rv.random-variables': 0.6, 'rv.expectation-algebra': 0.5, 'an.absolute-convergence': 0.4, 'rv.expectation': 0.5 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Expectation. Functions of a random variable, indicator function, variance, standard deviation."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.independence',
    title: 'Independent random variables',
    summary: 'Define independence of random variables and use $E(XY) = E(X)E(Y)$ for independent $X$ and $Y$.',
    level: 'tripos-ia',
    area: 'random-variables',
    prereqs: ['rv.expectation-general'],
    encompasses: { 'prob.independence': 0.6, 'rv.expectation-general': 0.5 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Covariance, independence of random variables."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.covariance',
    title: 'Covariance, correlation, and variance of sums',
    summary: 'Compute $\\mathrm{cov}(X, Y)$ and the correlation, and the variance of a sum of dependent or independent variables.',
    level: 'tripos-ia',
    area: 'random-variables',
    prereqs: ['rv.independence'],
    encompasses: { 'rv.independence': 0.5, 'rv.expectation-algebra': 0.5, 'rv.variance': 0.5 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Covariance, independence of random variables." The correlation coefficient is in "Continuous random variables".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'rv.conditional-expectation',
    title: 'Conditional distributions and expectation',
    summary: 'Find the distribution of $X$ given $Y = y$, and use the tower law $E(X) = E(E(X \\mid Y))$.',
    level: 'tripos-ia',
    area: 'random-variables',
    prereqs: ['rv.expectation-general', 'prob.total-probability', 'comb.binomial-theorem', 'prob.poisson-distribution'],
    encompasses: { 'prob.total-probability': 0.6, 'rv.expectation-general': 0.5 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Conditional expectation."', verified: true }],
    estMinutes: 25,
  },
];
