/** Area `sequences-and-series`. Sequences, sigma notation, arithmetic and geometric series, and induction. */
import type { Topic } from '@learnhub/mastery';
import { CST, CST_DM, CST_NUMBERS, GCSE, GCSE_SEQUENCES, M1_PURE, STEP, STEP_SS, STEP_SUPPORT } from '../sources';

export const sequencesAndSeries: Topic[] = [
  {
    id: 'pre.sequences',
    title: 'Sequences and nth term rules',
    summary: 'Generate a sequence from a term-to-term or position-to-term rule and find its nth term.',
    level: 'pre-a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.2 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_SEQUENCES, note: 'Items 23 to 25.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.sigma-notation',
    title: 'Sigma notation',
    summary: 'Read and write sums with sigma notation, and shift or split the index.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.sequences'],
    encompasses: { 'pre.sequences': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.arithmetic-series',
    title: 'Arithmetic series',
    summary: 'Find the nth term and the sum of the first n terms of an arithmetic sequence.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.sequences': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-series',
    title: 'Finite geometric series',
    summary: 'Sum a finite geometric series with the formula a(1 - r^n)/(1 - r).',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation', 'pre.indices'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.indices': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-sum-to-infinity',
    title: 'Sum to infinity of a geometric series',
    summary: 'Sum a geometric series to infinity when |r| < 1, and see why it fails otherwise.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.geometric-series'],
    encompasses: { 'alg.geometric-series': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.proof-by-induction',
    title: 'Proof by induction',
    summary: 'Prove a statement for every natural number from a base case and an inductive step.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['alg.arithmetic-series'],
    encompasses: { 'alg.arithmetic-series': 0.3, 'alg.sigma-notation': 0.4, 'pre.algebraic-manipulation': 0.4 },
    sources: [{
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PURE}, Proof`,
      note: 'Level step: DfE A level Mathematics leaves induction to Further Mathematics. Also IA Numbers and Sets, "The integers".',
      verified: true,
    }, {
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: `Syllabus: "Mathematical induction". ${STEP_SUPPORT[20]}`,
      verified: true,
    }],
    estMinutes: 20,
  },
];
