/** Area `sequences-and-series`. Sequences, sigma notation, arithmetic and geometric series, and induction. */
import type { Topic } from '@learnhub/mastery';
import {
  CST, CST_DM, CST_NUMBERS, GCSE, GCSE_SEQUENCES, IA_DISCRETE_RV, IA_PROB_PART_V, M1_PURE, M1_SEQUENCES, M2_FURTHER_ALGEBRA, STEP, STEP_SS, STEP_SUPPORT, TRIPOS,
} from '../sources';

export const sequencesAndSeries: Topic[] = [
  {
    id: 'pre.sequences',
    title: 'Sequences and nth term rules',
    summary: 'Generate a sequence from a term-to-term or position-to-term rule and find its $n$th term.',
    level: 'pre-a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.2 },
    sources: [{ doc: GCSE, course: 'GCSE Mathematics', section: GCSE_SEQUENCES, note: 'Items 23 to 25.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.sigma-notation',
    title: 'Sigma notation',
    summary: 'Read and write sums with sigma notation, and shift or split the index.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.sequences', 'pre.fractions'],
    encompasses: { 'pre.sequences': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.arithmetic-series',
    title: 'Arithmetic series',
    summary: 'Find the $n$th term and the sum of the first $n$ terms of an arithmetic sequence.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.sequences': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-series',
    title: 'Finite geometric series',
    summary: 'Sum a finite geometric series with the formula $\\frac{a(1 - r^n)}{1 - r}$.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation', 'pre.indices'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.indices': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-sum-to-infinity',
    title: 'Sum to infinity of a geometric series',
    summary: 'Sum a geometric series to infinity when $|r| < 1$, and see why it fails otherwise.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.geometric-series', 'alg.surds'],
    encompasses: { 'alg.geometric-series': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.proof-by-induction',
    title: 'Proof by induction',
    summary: 'Prove a statement for every natural number from a base case and an inductive step.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['alg.arithmetic-series'],
    encompasses: { 'alg.arithmetic-series': 0.3, 'alg.sigma-notation': 0.4, 'pre.algebraic-manipulation': 0.4 },
    sources: [{
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PURE}, Proof`,
      note: 'Level step: DfE A level Mathematics leaves induction to Further Mathematics. Also IA Numbers and Sets, "The integers".',
      verified: true,
    }, {
      doc: CST,
      course: CST_DM,
      section: CST_NUMBERS,
      note: `Syllabus: "Mathematical induction". ${STEP_SUPPORT[20]}`,
      verified: true,
    }],
    estMinutes: 20,
  },
  {
    id: 'alg.arithmetico-geometric',
    title: 'Sums of n r^n',
    summary: 'Sum $\\sum n r^n$ and $\\sum (a + nd) r^n$ by multiplying by $r$ and subtracting, or by differentiating the geometric series.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['rv.expectation'],
    encompasses: { 'alg.geometric-sum-to-infinity': 0.6, 'alg.sigma-notation': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Not named; the spec\'s geometric series and sigma notation, as STEP 3 Statistics Q2 (2010 S3 Q12) uses them.', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.linear-recurrences',
    title: 'Linear difference equations',
    summary: 'Solve $u_{n+1} = a u_n + b$ and $u_{n+1} = a u_n + b u_{n-1}$ from the auxiliary equation, with a particular solution for a constant term.',
    level: 'tripos-ia',
    area: 'sequences-and-series',
    prereqs: ['pre.quadratic-equations', 'rv.expectation', 'prob.total-probability'],
    encompasses: { 'pre.quadratic-equations': 0.6, 'alg.geometric-series': 0.4, 'pre.sequences': 0.4 },
    sources: [{ doc: TRIPOS, course: IA_PROB_PART_V, section: IA_DISCRETE_RV, note: 'Schedule: "Difference equations and their solution."', verified: true }],
    estMinutes: 25,
  },
  // Preparation, Stage A (graph/reviews/cambridge-prep.md).
  {
    id: 'alg.telescoping',
    title: 'Telescoping sums and products',
    summary: 'Sum $\\sum (f(r) - f(r - 1))$ or multiply $\\prod \\frac{g(r)}{g(r - 1)}$ by letting the middle terms cancel.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation'],
    encompasses: { 'alg.sigma-notation': 0.6, 'pre.fractions': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 2', section: M2_FURTHER_ALGEBRA, note: 'Spec: "Understand and use the method of differences for summation of series, including the use of partial fractions."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'alg.sums-of-powers',
    title: 'Sums of squares and cubes',
    summary: 'Find $\\sum r^2$ and $\\sum r^3$ by fitting a polynomial through small cases, and prove the formulas by induction.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['alg.proof-by-induction', 'alg.simultaneous-equations'],
    encompasses: { 'alg.proof-by-induction': 0.5, 'alg.simultaneous-equations': 0.4, 'alg.arithmetic-series': 0.4 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_SEQUENCES, note: 'Spec: "Understand and use sigma notation for sums of series."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'alg.recurrence-sequences',
    title: 'Sequences defined by recurrences',
    summary: 'Generate a sequence from $u_{n+1} = f(u_n)$, decide whether it converges, is periodic, or diverges, and find a limit as a fixed point.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['an.sequence-limits', 'alg.polynomials'],
    encompasses: { 'an.sequence-limits': 0.5, 'pre.quadratic-equations': 0.4, 'pre.sequences': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_SEQUENCES, note: 'Spec: "those generated by a simple relations of the form x_(n+1) = f(x_n), or x_(n+1) = f(x_n, x_(n-1)); increasing sequences; decreasing sequences; periodic sequences."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'alg.fibonacci',
    title: 'Fibonacci numbers',
    summary: 'Prove identities about $F_n$ by induction, and derive the closed form $F_n = \\frac{\\varphi^n - \\psi^n}{\\sqrt{5}}$ from the roots of $x^2 = x + 1$.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['alg.proof-by-induction', 'pre.quadratic-equations', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'alg.proof-by-induction': 0.5, 'pre.quadratic-equations': 0.4, 'alg.geometric-sum-to-infinity': 0.2 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_SEQUENCES, note: 'Spec: sequences "generated by a simple relations of the form ... x_(n+1) = f(x_n, x_(n-1))". The Fibonacci recurrence is the standard case; STEP Support Assignments 14 and 20 set it.', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'alg.binomial-rational',
    title: 'The binomial series for any power',
    summary: 'Expand $(1 + x)^n$ for rational $n$ when $|x| < 1$, and use the first terms as approximations such as $\\sqrt{1 + t} \\approx 1 + \\frac{t}{2}$.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['comb.binomial-theorem', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'comb.binomial-theorem': 0.6, 'alg.geometric-sum-to-infinity': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_SEQUENCES, note: 'Spec: "Extend the binomial expansion of (a + bx)^n to any rational n, including its use for approximation; be aware that the expansion is valid (converges) for |bx/a| < 1".', verified: true }],
    estMinutes: 20,
  },
];
