/** Area `trigonometry`. Right-triangle trigonometry to compound angles, equations, and small angles, for STEP Support Foundation (graph/reviews/cambridge-prep.md). */
import type { Topic } from '@learnhub/mastery';
import { M1_TRIG, STEP } from '../sources';

export const trigonometry: Topic[] = [
  {
    id: 'trig.right-triangle',
    title: 'Sine, cosine, and tangent in a right triangle',
    summary: 'Define $\\sin\\theta$, $\\cos\\theta$, and $\\tan\\theta$ from the sides of a right triangle, prove $\\cos^2\\theta + \\sin^2\\theta = 1$, and use the exact values at $30^\\circ$, $45^\\circ$, and $60^\\circ$.',
    level: 'pre-a-level',
    area: 'trigonometry',
    prereqs: ['pre.fractions'],
    encompasses: { 'pre.fractions': 0.3 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Know, understand and use the definitions of sine, cosine, and tangent for all arguments" and "sin^2 + cos^2 = 1".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'trig.sine-cosine-rules',
    title: 'The sine and cosine rules',
    summary: 'Derive and use the cosine rule, the sine rule, and the area $\\frac{1}{2}ab\\sin C$ to solve any triangle.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.right-triangle'],
    encompasses: { 'trig.right-triangle': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "the sine and cosine rules; the area of a triangle in the form (1/2) ab sin C."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'trig.radians-and-graphs',
    title: 'Radians and the trigonometric graphs',
    summary: 'Measure angles in radians, sketch $\\sin$, $\\cos$, and $\\tan$ for all angles, and use their symmetries and periods to find every angle with a given value.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.double-angle'],
    encompasses: { 'trig.right-triangle': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Work with radian measure" and "Understand and use the sine, cosine, and tangent functions; their graphs, symmetries, and periodicity."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'trig.compound-angles',
    title: 'Compound angle formulae',
    summary: 'Prove $\\sin(\\alpha + \\beta) = \\sin\\alpha\\cos\\beta + \\cos\\alpha\\sin\\beta$ from a triangle, derive the other compound angle formulae, and find exact values such as $\\sin 75^\\circ$.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.sine-cosine-rules'],
    encompasses: { 'trig.sine-cosine-rules': 0.5, 'trig.right-triangle': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "use of formulae for sin(A +- B), cos(A +- B), and tan(A +- B); understand geometrical proofs of these formulae."', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'trig.double-angle',
    title: 'Double and triple angle formulae',
    summary: 'Derive $\\sin 2A$, $\\cos 2A$, $\\tan 2A$, and $\\cos 3A = 4\\cos^3 A - 3\\cos A$ from the compound angle formulae.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.compound-angles'],
    encompasses: { 'trig.compound-angles': 0.7 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Know, understand and use double angle formulae".', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'trig.equations',
    title: 'Solving trigonometric equations',
    summary: 'Solve equations such as $\\sin 3A - \\sin A = 2\\cos 2A$ on an interval by rewriting with identities and factorising.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.radians-and-graphs', 'alg.polynomials'],
    encompasses: { 'trig.double-angle': 0.6, 'trig.radians-and-graphs': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Find general solutions to trigonometric equations, including quadratic equations in sin, cos, or tan and equations involving linear multiples of the unknown angle".', verified: true }],
    estMinutes: 20,
  },
  {
    id: 'trig.reciprocal-functions',
    title: 'Secant, cosecant, and cotangent',
    summary: 'Define $\\sec$, $\\csc$, and $\\cot$, find their exact values, and use $\\sec^2\\theta = 1 + \\tan^2\\theta$.',
    level: 'a-level',
    area: 'trigonometry',
    prereqs: ['trig.radians-and-graphs'],
    encompasses: { 'trig.radians-and-graphs': 0.5 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Know, understand and use the definitions of sec, cosec, and cot" and "sec^2 = 1 + tan^2, and cosec^2 = 1 + cot^2."', verified: true }],
    estMinutes: 15,
  },
  {
    id: 'trig.small-angles',
    title: 'Small angle approximations',
    summary: 'Show $\\frac{\\sin\\theta}{\\theta} \\to 1$ by comparing areas, and use $\\sin\\theta \\approx \\theta$, $\\tan\\theta \\approx \\theta$, and $\\cos\\theta \\approx 1 - \\frac{\\theta^2}{2}$ for small $\\theta$ in radians.',
    level: 'step',
    area: 'trigonometry',
    prereqs: ['trig.radians-and-graphs', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'trig.radians-and-graphs': 0.6 },
    sources: [{ doc: STEP, course: 'STEP Mathematics 1', section: M1_TRIG, note: 'Spec: "Know, understand and use the standard small angle approximations of sin, cos, and tan ... where theta is in radians."', verified: true }],
    estMinutes: 20,
  },
];
