// Generated from TOPIC_CONTENT by the content checks (content.test.ts, "the catalog"). Do not edit by hand:
// after adding a topic or changing its Cambridge problems, run `npx vitest run -u` in content/ and review the diff.

/** A Cambridge problem as the app lists it without loading its topic. */
export interface CatalogProblem {
  readonly id: string;
  readonly title: string;
  readonly mode: 'auto' | 'supervision';
}

/** Every topic with content, in the order of TOPIC_CONTENT, with its Cambridge problems. */
export const CATALOG: Readonly<Record<string, readonly CatalogProblem[]>> = {
  "pre.fractions": [
    { id: "a6-q1-i-general", title: "The same product to n factors", mode: "auto" },
    { id: "a6-q1-i-show", title: "Why the general product is 2n + 1", mode: "supervision" },
  ],
  "pre.set-notation": [
    { id: "bop-1-5-1a", title: "A union", mode: "auto" },
    { id: "bop-1-5-1c", title: "A difference", mode: "auto" },
    { id: "bop-1-5-1g", title: "A set inside another", mode: "auto" },
    { id: "bop-1-5-1i", title: "An empty difference", mode: "auto" },
    { id: "bop-1-6-1a", title: "A complement", mode: "auto" },
    { id: "bop-1-6-1g", title: "Complements and a difference", mode: "auto" },
    { id: "bop-1-6-2f", title: "The complement of a union", mode: "auto" },
    { id: "bop-1-7-5", title: "A distributive law", mode: "auto" },
    { id: "bop-1-7-8", title: "The complement of a union", mode: "auto" },
    { id: "bop-1-7-3", title: "A Venn diagram for three sets", mode: "supervision" },
    { id: "bop-1-7-10", title: "A difference and a union", mode: "supervision" },
  ],
  "pre.product-rule": [
    { id: "a7-q4-i-b", title: "Five weights, one pan", mode: "auto" },
    { id: "a7-q4-ii-a", title: "Two weights, two pans", mode: "auto" },
    { id: "a7-q4-ii-c", title: "Four weights up to 40", mode: "auto" },
    { id: "a7-q4-ii-b-count", title: "Each weight left, right, or out", mode: "auto" },
    { id: "a7-q4-i-a", title: "Three weights, and only one choice", mode: "supervision" },
    { id: "a7-q4-i-c-show", title: "At most 2^n loads", mode: "supervision" },
    { id: "a7-q4-ii-b-show", title: "At most 3^n loads", mode: "supervision" },
  ],
  "logic.connectives": [
    { id: "tmua-a-1", title: "Statements about 21", mode: "auto" },
    { id: "tmua-b-1", title: "Not not", mode: "auto" },
    { id: "bop-2-1-1", title: "Statement or not", mode: "auto" },
    { id: "bop-2-1-3", title: "Statement or not", mode: "auto" },
    { id: "bop-2-1-9", title: "Statement or not", mode: "auto" },
    { id: "bop-2-1-11", title: "Statement or not", mode: "auto" },
    { id: "bop-2-1-13", title: "Statement or not", mode: "auto" },
    { id: "bop-2-2-8", title: "At least one is zero", mode: "auto" },
    { id: "bop-2-2-9", title: "Membership of a difference", mode: "auto" },
    { id: "bop-2-2-10", title: "Membership of a union", mode: "auto" },
    { id: "bop-2-5-5", title: "A contradiction or Q", mode: "auto" },
    { id: "bop-2-5-8", title: "Three letters", mode: "auto" },
    { id: "bop-2-6-4", title: "De Morgan by truth table", mode: "auto" },
    { id: "bop-2-6-9", title: "Equivalent or not", mode: "auto" },
    { id: "bop-2-6-13", title: "Equivalent or not", mode: "auto" },
    { id: "tmua-c-4", title: "Bracketing \"or\" two ways", mode: "auto" },
    { id: "tmua-a-2", title: "Replacing 21 by x", mode: "supervision" },
    { id: "tmua-b-2", title: "Many nots", mode: "supervision" },
    { id: "bop-2-2-12", title: "Tolstoy in symbols", mode: "supervision" },
  ],
  "pre.algebraic-manipulation": [
    { id: "a7-q2-v", title: "Three integer roots", mode: "auto" },
    { id: "a7-q3", title: "The roots of a quartic", mode: "auto" },
    { id: "a12-q2-i-a", title: "Two algebraic fractions", mode: "auto" },
    { id: "a12-q2-i-b", title: "Products and a sum of fractions", mode: "auto" },
    { id: "tmua-q", title: "Squaring both sides", mode: "auto" },
    { id: "a7-q2-i-ii", title: "Roots and coefficients without the formula", mode: "supervision" },
    { id: "a7-q2-iv", title: "Three substitutions", mode: "supervision" },
    { id: "a7-q3-show", title: "The general polynomial", mode: "supervision" },
  ],
  "sets.comprehension": [
    { id: "sw-3-1-1", title: "CD(666, 330)", mode: "auto" },
    { id: "notes-202-interval", title: "An interval of integers", mode: "auto" },
    { id: "notes-205-d0", title: "The divisors of zero", mode: "auto" },
    { id: "notes-205-equality", title: "Proving two sets equal", mode: "supervision" },
  ],
  "comb.factorial": [
    { id: "a12-q4-extent-6", title: "An extent on 6 bells", mode: "auto" },
    { id: "a12-q4-extent-8", title: "An extent on 8 bells", mode: "auto" },
  ],
  "pre.indices": [
    { id: "sw-1-2-3-verdict", title: "Prove or disprove: 2 divides 2^n", mode: "auto" },
    { id: "sw-1-2-3-witness", title: "The counterexample", mode: "auto" },
    { id: "a12-q1-iii", title: "n^5 - n^3 and 24", mode: "supervision" },
  ],
  "pre.sequences": [
    { id: "sw-1-3-1-b", title: "A formula for t_k", mode: "auto" },
    { id: "sw-1-3-1-c", title: "Triangular and square", mode: "supervision" },
    { id: "sw-1-3-1-d", title: "Two consecutive triangular numbers", mode: "supervision" },
  ],
  "pre.probability-scale": [
    { id: "a12-q2-ii-first", title: "The first sweet", mode: "auto" },
    { id: "a12-q2-iv-b", title: "The first child in the queue", mode: "auto" },
  ],
  "comb.pigeonhole": [
    { id: "a8-q4-i", title: "One pair, three colours", mode: "auto" },
    { id: "a8-q4-ii", title: "Two pairs, three colours", mode: "auto" },
    { id: "a5-q4-iii", title: "n pairs, 2 colours", mode: "auto" },
    { id: "a8-q4-iii", title: "n pairs, 3 colours", mode: "auto" },
    { id: "a5-q4-iii-show", title: "Why 2n + 1 socks", mode: "supervision" },
    { id: "a8-q4-iii-show", title: "Why 2n + 2 socks", mode: "supervision" },
    { id: "notes-87-proof", title: "Prove the pigeonhole principle", mode: "supervision" },
  ],
  "prob.bayes-two-events": [
    { id: "a6-q4-i-abc", title: "Joint, total, and conditional", mode: "auto" },
    { id: "a6-q4-i-e", title: "A man, given a non-smoker", mode: "auto" },
    { id: "a6-q4-ii", title: "How worried should you be?", mode: "auto" },
    { id: "a6-discussion", title: "Which probability matters?", mode: "supervision" },
  ],
  "prob.event-spaces": [
    { id: "q4-definitions", title: "State the definitions", mode: "supervision" },
    { id: "q4-a-finite", title: "Finite unions and intersections", mode: "supervision" },
    { id: "q6-b-event", title: "\"Infinitely often\" is an event", mode: "supervision" },
  ],
  "pre.sample-spaces": [
    { id: "a19-q4-ii-three", title: "Three sixes", mode: "auto" },
    { id: "a19-q4-ii-one", title: "Exactly one six", mode: "auto" },
    { id: "a19-q4-ii-table", title: "Every number of sixes", mode: "auto" },
    { id: "a19-q4-ii-bet", title: "Should I accept the bet?", mode: "supervision" },
  ],
  "logic.implication": [
    { id: "bop-2-5-1", title: "A truth table with an implication", mode: "auto" },
    { id: "bop-2-5-7", title: "A truth table with an implication", mode: "auto" },
    { id: "bop-2-5-10", title: "Truth values from a false statement", mode: "auto" },
    { id: "bop-2-5-11", title: "Truth values from a true statement", mode: "auto" },
    { id: "bop-2-3-3", title: "In the form \"If P, then Q\"", mode: "auto" },
    { id: "bop-2-3-5", title: "In the form \"If P, then Q\"", mode: "auto" },
    { id: "bop-2-3-7", title: "In the form \"If P, then Q\"", mode: "auto" },
    { id: "bop-2-3-11", title: "In the form \"If P, then Q\"", mode: "auto" },
    { id: "tmua-e-4", title: "If P then (P or Q)", mode: "auto" },
    { id: "tmua-p29", title: "True or false implications", mode: "auto" },
    { id: "notes-50-prop10", title: "If √(x) is rational, so is x", mode: "supervision" },
    { id: "notes-54-thm11", title: "Implication is transitive", mode: "supervision" },
    { id: "tmua-e-1-2", title: "If P then Q, with and, or, not", mode: "supervision" },
    { id: "tmua-j-3-4", title: "Converses", mode: "supervision" },
  ],
  "pre.prime-factorisation": [
    { id: "a12-q4-sets", title: "How many sets of ages", mode: "auto" },
    { id: "a12-q4-imam", title: "How old is the Imam?", mode: "auto" },
    { id: "a12-q4-rabbi", title: "How old is the Rabbi?", mode: "auto" },
    { id: "a12-q4-explain", title: "Why the remark helps", mode: "supervision" },
  ],
  "pre.tree-diagrams": [
    { id: "a12-q2-iii-b", title: "Three blackcurrant chews", mode: "auto" },
    { id: "a12-q2-iv-a", title: "At least one child has goggles", mode: "auto" },
    { id: "a12-q2-iv-c", title: "Only the middle child forgets", mode: "auto" },
    { id: "a12-q2-ii-methods", title: "One after the other, or both at once", mode: "supervision" },
    { id: "a6-q4-i-tree", title: "A tree for the smokers", mode: "supervision" },
  ],
  "pre.algebraic-argument": [
    { id: "bop-4-1", title: "An even number squared", mode: "auto" },
    { id: "bop-4-3", title: "An odd number in a quadratic", mode: "auto" },
    { id: "bop-4-5", title: "An even factor", mode: "auto" },
    { id: "bop-4-2", title: "An odd number cubed", mode: "supervision" },
    { id: "bop-4-4", title: "Odd times odd", mode: "supervision" },
    { id: "a12-q1-ii-six", title: "n^3 - n and 6", mode: "supervision" },
  ],
  "num.number-systems": [
    { id: "notes-174-z", title: "Admitting additive inverses", mode: "auto" },
    { id: "notes-174-q", title: "Admitting multiplicative inverses", mode: "auto" },
    { id: "notes-167-cancel", title: "Why cancellation needs k ≠ 0", mode: "auto" },
    { id: "sw-1-1-6", title: "The sum of two rationals", mode: "supervision" },
    { id: "sw-3-2-5", title: "Lowest terms are unique", mode: "supervision" },
  ],
  "alg.sigma-notation": [
    { id: "bop-10-1", title: "The sum of the first n integers", mode: "auto" },
    { id: "bop-10-4", title: "Products of neighbours", mode: "auto" },
    { id: "bop-10-6", title: "An arithmetic sum", mode: "auto" },
    { id: "bop-10-7", title: "Products two apart", mode: "auto" },
    { id: "bop-10-15", title: "A telescoping sum", mode: "auto" },
    { id: "bop-10-3", title: "The sum of cubes", mode: "auto" },
    { id: "sw-4-3-2-d", title: "Every power sum is a polynomial", mode: "supervision" },
    { id: "bop-10-20", title: "Square of a sum, sum of cubes", mode: "supervision" },
  ],
  "comb.combinations": [
    { id: "q7-a", title: "Two given people on the committee", mode: "auto" },
    { id: "q12-check", title: "Balls in boxes, small cases", mode: "auto" },
    { id: "bop-4-22", title: "n^2 from binomial coefficients", mode: "auto" },
    { id: "bop-4-23", title: "C(2n, n) is even", mode: "supervision" },
    { id: "bop-4-25", title: "Choosing in two stages", mode: "supervision" },
  ],
  "sets.countable-unions": [
    { id: "q6-divides-b", title: "Divisors, for all large n", mode: "auto" },
    { id: "q6-parity-b", title: "Alternating sets", mode: "auto" },
    { id: "q6-fixed-a", title: "Two fixed points and two that alternate", mode: "auto" },
    { id: "q4-de-morgan", title: "De Morgan's law for a sequence", mode: "supervision" },
    { id: "q6-words", title: "Infinitely often, in quantifiers", mode: "supervision" },
  ],
  "logic.iff": [
    { id: "bop-2-4-1", title: "In the form \"P if and only if Q\"", mode: "auto" },
    { id: "bop-2-4-3", title: "In the form \"P if and only if Q\"", mode: "auto" },
    { id: "bop-2-4-5", title: "In the form \"P if and only if Q\"", mode: "auto" },
    { id: "sw-1-1-3-verdict", title: "Prove or disprove: n^2 even iff n even", mode: "auto" },
    { id: "tmua-necessary", title: "\"A is necessary for B\" in symbols", mode: "auto" },
    { id: "tmua-necessary-sufficient", title: "Necessary and sufficient, in symbols", mode: "auto" },
    { id: "sw-1-1-3", title: "n^2 is even if and only if n is even", mode: "supervision" },
    { id: "sw-1-2-2", title: "Cancelling a common factor", mode: "supervision" },
    { id: "sw-1-2-7", title: "Divisible by 30", mode: "supervision" },
    { id: "tmua-i-3", title: "Swapping the sides", mode: "supervision" },
  ],
  "logic.quantifiers": [
    { id: "tmua-m", title: "For every, and there exists", mode: "auto" },
    { id: "bop-2-7-1", title: "Every real square is positive?", mode: "auto" },
    { id: "notes-93-prop21", title: "A witness for k = 13", mode: "auto" },
    { id: "notes-95-prop22", title: "Between two powers of 2", mode: "auto" },
    { id: "notes-72-prop18", title: "A congruence for every n", mode: "supervision" },
    { id: "sw-1-3-2", title: "A \"there exists\" on the left of an arrow", mode: "supervision" },
    { id: "sw-1-2-10", title: "Everything up to n", mode: "supervision" },
  ],
  "proof.direct": [
    { id: "bop-4-7", title: "a^2 divides b^2", mode: "auto" },
    { id: "bop-4-19", title: "a^6 divides c", mode: "auto" },
    { id: "bop-4-6", title: "a divides b + c", mode: "auto" },
    { id: "bop-4-10", title: "a divides 3b^3 - b^2 + 5b", mode: "auto" },
    { id: "tmua-r-3", title: "Clearing a fraction from an inequality", mode: "auto" },
    { id: "tmua-p72-extra-root", title: "The extra solution", mode: "auto" },
    { id: "bop-4-9", title: "7 divides 4a", mode: "supervision" },
    { id: "bop-4-13", title: "Two cases from a factorisation", mode: "supervision" },
    { id: "bop-4-24", title: "Long runs of composite numbers", mode: "supervision" },
    { id: "notes-35-scratch", title: "From scratch work to a proof", mode: "supervision" },
  ],
  "alg.arithmetic-series": [
    { id: "sw-1-3-1-e-25", title: "Euler: 25n + 3 is triangular", mode: "auto" },
    { id: "sw-1-3-1-e-81", title: "Euler: 81n + 10 is triangular", mode: "auto" },
    { id: "sw-1-3-1-f", title: "Jordan's generalisation", mode: "auto" },
    { id: "sw-1-3-1-e", title: "Euler's four maps", mode: "supervision" },
    { id: "sw-1-3-1-f-proof", title: "Prove Jordan's generalisation", mode: "supervision" },
  ],
  "logic.nested-quantifiers": [
    { id: "tmua-n", title: "Two quantifiers, every order", mode: "auto" },
    { id: "bop-2-7-9", title: "True or false", mode: "auto" },
    { id: "bop-2-7-10", title: "True or false", mode: "auto" },
    { id: "bop-2-9-7", title: "Into symbols", mode: "auto" },
    { id: "bop-2-9-5", title: "Into symbols", mode: "auto" },
    { id: "tmua-p59-s1-s2", title: "S_1 and S_2", mode: "supervision" },
    { id: "bop-2-9-13", title: "Funny, as long as", mode: "supervision" },
  ],
  "alg.geometric-series": [
    { id: "sw-4-2-1-b", title: "2^15 - 1 is not prime", mode: "auto" },
    { id: "bop-10-5", title: "Powers of 2", mode: "auto" },
    { id: "sw-4-2-1-a-proof", title: "Establish the identity", mode: "supervision" },
    { id: "sw-4-2-1-b-proof", title: "Composite exponents", mode: "supervision" },
  ],
  "comb.binomial-identities": [
    { id: "bop-10-24", title: "A weighted row sum", mode: "auto" },
    { id: "bop-10-40", title: "Squares along a row", mode: "auto" },
    { id: "bop-10-41", title: "Another diagonal", mode: "auto" },
    { id: "bop-10-35", title: "Even entries", mode: "supervision" },
    { id: "bop-10-38", title: "Vandermonde's identity", mode: "supervision" },
    { id: "notes-280-homework-2", title: "Finish the Binomial Theorem's inductive step", mode: "supervision" },
  ],
  "pre.two-way-tables": [
    { id: "a6-q4-i-regions", title: "The four regions of the diagram", mode: "auto" },
    { id: "a6-q4-i-e-woman", title: "A woman, given a non-smoker", mode: "auto" },
    { id: "a6-q4-i-diagram", title: "Reading a condition from the diagram", mode: "supervision" },
  ],
  "comb.binomial-theorem": [
    { id: "cst-cor-33-p5", title: "The Freshman's Dream for 5", mode: "auto" },
    { id: "cst-cor-31-2", title: "The coefficients add up to a power of 2", mode: "auto" },
    { id: "cst-cor-32", title: "2^p modulo p", mode: "auto" },
    { id: "cst-cor-31-proof", title: "Corollary 31 from the theorem", mode: "supervision" },
    { id: "cst-cor-32-proof", title: "Why 2^p \\equiv 2 \\pmodp", mode: "supervision" },
  ],
  "logic.equivalences": [
    { id: "bop-2-6-3", title: "An implication as an \"or\"", mode: "auto" },
    { id: "bop-2-6-5", title: "De Morgan for three", mode: "auto" },
    { id: "bop-2-6-7", title: "An implication with a contradiction", mode: "auto" },
    { id: "bop-2-6-10", title: "Equivalent or not", mode: "auto" },
    { id: "bop-2-6-11", title: "Equivalent or not", mode: "auto" },
    { id: "bop-2-6-12", title: "Equivalent or not", mode: "auto" },
    { id: "tmua-f-1", title: "not (A and not B)", mode: "auto" },
    { id: "tmua-k-2", title: "The contrapositive of the converse", mode: "auto" },
    { id: "tmua-k-4", title: "The contrapositive of \"a and b odd\"", mode: "auto" },
    { id: "tmua-f-3", title: "Equivalent statements in words", mode: "supervision" },
    { id: "tmua-k-5", title: "A careless \"not\"", mode: "supervision" },
    { id: "cst-lemma-43-equivalences", title: "Which equivalences?", mode: "supervision" },
  ],
  "proof.cases": [
    { id: "a6-q3-ii", title: "Digit sum 39", mode: "auto" },
    { id: "sw-2-2-3-cases", title: "Squares modulo 4, case by case", mode: "auto" },
    { id: "sw-3-2-7-b", title: "Odd squares modulo 8", mode: "auto" },
    { id: "bop-4-14", title: "The parity of 5n^2 + 3n + 7", mode: "auto" },
    { id: "bop-4-15", title: "The parity of n^2 + 3n + 4", mode: "auto" },
    { id: "bop-4-4-k", title: "Every multiple of 4", mode: "auto" },
    { id: "sw-2-2-3", title: "Squares leave 0 or 1 modulo 4", mode: "supervision" },
    { id: "sw-1-2-8", title: "Dividing each other", mode: "supervision" },
    { id: "sw-2-3-1", title: "Differences of two squares", mode: "supervision" },
    { id: "sw-3-2-7", title: "24 divides p^2 - 1", mode: "supervision" },
    { id: "bop-4-16", title: "Same parity, even sum", mode: "supervision" },
  ],
  "logic.negating-quantifiers": [
    { id: "bop-2-10-7", title: "Anything with a face", mode: "auto" },
    { id: "bop-2-10-11", title: "Fooling people", mode: "auto" },
    { id: "tmua-n1", title: "Not every square is more than 6", mode: "auto" },
    { id: "sw-1-1-5-negation", title: "The negation of a supervision exercise", mode: "auto" },
    { id: "sw-1-1-5-witness", title: "No integer between them", mode: "auto" },
    { id: "sw-1-1-5", title: "No integer z", mode: "supervision" },
    { id: "bop-2-10-5", title: "A limit, negated", mode: "supervision" },
    { id: "bop-2-10-12", title: "Two evils", mode: "supervision" },
  ],
  "proof.counterexample": [
    { id: "sw-1-1-1", title: "Not prime, then 2n + 13 not prime?", mode: "auto" },
    { id: "sw-1-2-5", title: "m | k and n | k, but not mn | k", mode: "auto" },
    { id: "sw-1-2-9", title: "k | mn, but k divides neither", mode: "auto" },
    { id: "sw-2-2-1", title: "Congruent exponents, different powers", mode: "auto" },
    { id: "tmua-p-2-a", title: "Odd and greater than 4", mode: "auto" },
    { id: "tmua-p-2-b", title: "Odd or greater than 37", mode: "auto" },
    { id: "tmua-p-2-c", title: "Prime if and only if odd", mode: "auto" },
    { id: "tmua-p-2-d", title: "Odd only if prime", mode: "auto" },
    { id: "tmua-p-2-e", title: "Prime only if odd", mode: "auto" },
    { id: "tmua-p-1", title: "What counts as a counterexample", mode: "supervision" },
    { id: "tmua-p-2-f", title: "Prime, or divisible by something smaller", mode: "supervision" },
  ],
  "proof.contradiction": [
    { id: "sw-2-3-2-a", title: "The first repunits", mode: "auto" },
    { id: "sw-2-3-2-base", title: "A square repunit in another base", mode: "auto" },
    { id: "bop-6-11", title: "No a, b with 18a + 6b = 1", mode: "auto" },
    { id: "bop-6-10", title: "No a, b with 21a + 30b = 1", mode: "auto" },
    { id: "sw-2-3-2-b", title: "No repunit is a square", mode: "supervision" },
    { id: "tmua-o-1", title: "Replace 2 by 9", mode: "supervision" },
    { id: "tmua-o-2", title: "√(p) for a prime p", mode: "supervision" },
    { id: "bop-6-5", title: "√(3) is irrational", mode: "supervision" },
    { id: "bop-6-7", title: "a^2 - 4b - 3 ≠ 0", mode: "supervision" },
  ],
  "comb.repeated-arrangements": [
    { id: "a6-q2-ii", title: "Names with one repeated letter", mode: "auto" },
    { id: "a6-q2-iii", title: "Reggie, Hannah, and Marshmallow", mode: "auto" },
    { id: "a6-q2-v", title: "MISSISSIPPI", mode: "auto" },
    { id: "a6-q5-iii", title: "Anna's two pairs", mode: "auto" },
    { id: "a6-q2-iv", title: "Lillian", mode: "supervision" },
    { id: "a6-q2-general", title: "Why the general formula holds", mode: "supervision" },
  ],
  "alg.proof-by-induction": [
    { id: "sw-4-2-3-g-ii", title: "A sum of Fibonacci numbers", mode: "auto" },
    { id: "sw-4-2-3-g-iii", title: "A sum of Fibonacci numbers", mode: "auto" },
    { id: "bop-10-9", title: "24 divides 5^2n - 1", mode: "auto" },
    { id: "sw-4-1-2-count", title: "How many L-shaped pieces", mode: "auto" },
    { id: "sw-4-1-1-step", title: "From k points to k + 1", mode: "auto" },
    { id: "ia-q10", title: "The Polya urn", mode: "auto" },
    { id: "bop-10-13", title: "6 divides n^3 - n", mode: "supervision" },
    { id: "sw-4-1-2", title: "L-shaped tiles", mode: "supervision" },
    { id: "sw-4-2-2", title: "Bernoulli's inequality", mode: "supervision" },
    { id: "sw-4-1-1", title: "Angles of a polygon", mode: "supervision" },
    { id: "ia-q10-proof", title: "The Polya urn, proved", mode: "supervision" },
  ],
  "prob.counting-probability": [
    { id: "a12-q3-ii", title: "Two people with 2 pound coins", mode: "auto" },
    { id: "a12-q3-iii", title: "Three people with 2 pound coins", mode: "auto" },
    { id: "a12-q2-ii-mints", title: "Two mints, by counting pairs", mode: "auto" },
    { id: "a12-q3-ii-show", title: "Justify the case n = 2", mode: "supervision" },
    { id: "a12-q3-discussion", title: "The general conjecture", mode: "supervision" },
  ],
  "proof.contrapositive": [
    { id: "bop-5-1", title: "n^2 even", mode: "auto" },
    { id: "bop-5-9", title: "3 and squares", mode: "auto" },
    { id: "bop-5-7", title: "Both even", mode: "auto" },
    { id: "sw-1-1-2-verdict", title: "If x^2 + y = 13 and y ≠ 4", mode: "auto" },
    { id: "sw-1-1-8-verdict", title: "mn even", mode: "auto" },
    { id: "bop-5-25", title: "2^n - 1 for a composite n", mode: "auto" },
    { id: "sw-1-1-2", title: "A partial contrapositive", mode: "supervision" },
    { id: "sw-1-1-8", title: "mn even means one factor is even", mode: "supervision" },
    { id: "cst-corollary-41", title: "Square roots of irrationals", mode: "supervision" },
    { id: "tmua-k-3", title: "The converse of the contrapositive", mode: "supervision" },
  ],
  "prob.independent-events": [
    { id: "a19-q4-ii-two", title: "Three dice, two sixes", mode: "auto" },
    { id: "a12-q2-iv-one", title: "Exactly one child has goggles", mode: "auto" },
    { id: "a12-q2-iv-dependent", title: "Independent children, dependent events", mode: "auto" },
    { id: "a19-q4-ii-independence", title: "Where independence was used", mode: "supervision" },
    { id: "a12-q2-iv-disjoint", title: "Disjoint is not independent", mode: "supervision" },
  ],
  "prob.inclusion-exclusion-three": [
    { id: "ia-q5-b-any", title: "Divisible by 3, 5, or 7", mode: "auto" },
    { id: "ia-q5-a-numbers", title: "In B or C, but not in A", mode: "auto" },
    { id: "ia-q5-a", title: "The identity for A^c ∩ (B ∪ C)", mode: "supervision" },
    { id: "ia-q5-three", title: "Inclusion-exclusion for three, derived", mode: "supervision" },
  ],
  "proof.quantifier-patterns": [
    { id: "sw-1-1-7", title: "The unique y", mode: "auto" },
    { id: "bop-7-17", title: "A prime between 90 and 100", mode: "auto" },
    { id: "bop-7-12", title: "A positive x with x^2 < x", mode: "auto" },
    { id: "bop-7-20", title: "11 divides 2^n - 1", mode: "auto" },
    { id: "bop-4-26", title: "An odd number as a difference of squares", mode: "auto" },
    { id: "sw-1-1-7-proof", title: "Existence and uniqueness", mode: "supervision" },
    { id: "sw-1-1-4-proof", title: "Writing an existence proof", mode: "supervision" },
    { id: "bop-4-26-proof", title: "Every odd integer", mode: "supervision" },
  ],
  "prob.classical-probability": [
    { id: "ia-q2-b", title: "Meeting in the final", mode: "auto" },
    { id: "ia-q2-c", title: "Meeting in any round", mode: "auto" },
    { id: "ia-q3", title: "Halving a deck", mode: "auto" },
    { id: "ia-q11", title: "Mary and John", mode: "auto" },
    { id: "ia-q11-proof", title: "Prove the conjecture", mode: "supervision" },
    { id: "ia-q2-space", title: "One probability space", mode: "supervision" },
  ],
  "proof.infinitely-many-primes": [
    { id: "cst-totd-first-composite", title: "How long does the product plus one stay prime?", mode: "auto" },
    { id: "cst-totd-remarks", title: "What the argument does and does not show", mode: "supervision" },
    { id: "bop-6-1-primes", title: "Book of Proof's version", mode: "supervision" },
  ],
  "comb.binomial-theorem-proof": [
    { id: "notes-275-pascal-by-counting", title: "Pascal's rule by counting", mode: "auto" },
    { id: "notes-274-unfold", title: "Unfolding the left-hand side", mode: "auto" },
    { id: "bop-10-23", title: "Book of Proof's version", mode: "supervision" },
    { id: "notes-278-semiring", title: "Where commutativity is used", mode: "supervision" },
  ],
  "proof.strong-induction": [
    { id: "bop-10-2-postage-47", title: "Forty-seven cents in stamps", mode: "auto" },
    { id: "bop-10-32", title: "Binary numbers with no consecutive 1s", mode: "auto" },
    { id: "bop-10-25", title: "A Fibonacci sum", mode: "auto" },
    { id: "bop-10-42-count", title: "Even Fibonacci numbers", mode: "auto" },
    { id: "sheet-4-3-1", title: "The subtractive algorithm terminates", mode: "supervision" },
    { id: "bop-10-2-trees", title: "Why the tree proof needs strong induction", mode: "supervision" },
    { id: "bop-10-42", title: "When a Fibonacci number is even", mode: "supervision" },
  ],
  "num.divisibility": [
    { id: "sheet-1-2-1-a", title: "Which integers does zero divide?", mode: "auto" },
    { id: "sheet-1-2-1-b", title: "Which integers divide zero?", mode: "auto" },
    { id: "bop-6-19", title: "Five consecutive integers", mode: "auto" },
    { id: "bop-4-20", title: "When a^2 divides a", mode: "auto" },
    { id: "sheet-1-2-4", title: "Divisibility is transitive", mode: "supervision" },
    { id: "sheet-1-2-6", title: "Sums, multiples, and combinations", mode: "supervision" },
    { id: "bop-4-11", title: "Products of divisors", mode: "supervision" },
    { id: "a12-q1-iv", title: "A tempting wrong argument", mode: "supervision" },
  ],
  "prob.conditional-formula": [
    { id: "a19-q4-i-formula", title: "Three coins, by the formula", mode: "auto" },
    { id: "a12-q3-ii-121", title: "The raffle queue starts 1, 2, 1", mode: "auto" },
    { id: "a12-q3-ii-11", title: "The raffle queue starts 1, 1", mode: "auto" },
    { id: "a12-q3-iii", title: "Three people with £2 coins", mode: "supervision" },
    { id: "a6-q4-i-formula", title: "Both directions by the formula", mode: "supervision" },
  ],
  "num.division-theorem": [
    { id: "sheet-2-1-3-a", title: "Cancelling a multiple in a remainder", mode: "auto" },
    { id: "notes-186-cor-59", title: "The notes' formula for [k]_m", mode: "auto" },
    { id: "bop-7-28", title: "Uniqueness in the division algorithm", mode: "supervision" },
    { id: "notes-181-theorem-57", title: "Why the algorithm is right", mode: "supervision" },
    { id: "sheet-2-1-3", title: "Three remainder identities", mode: "supervision" },
  ],
  "prob.binomial-distribution": [
    { id: "a19-q4-ii-at-least-two", title: "At least two sixes", mode: "auto" },
    { id: "a12-q2-iv-two", title: "Exactly two children with goggles", mode: "auto" },
    { id: "a12-q2-iv-distribution", title: "The whole distribution", mode: "auto" },
    { id: "a19-q4-ii-why-binomial", title: "Why the number of sixes is binomial", mode: "supervision" },
  ],
  "num.congruence": [
    { id: "bop-5-2-example", title: "Which are congruences?", mode: "auto" },
    { id: "sheet-3-2-10-b-reduce", title: "Reducing a congruence", mode: "auto" },
    { id: "sheet-2-1-1", title: "Congruence is an equivalence relation", mode: "supervision" },
    { id: "sheet-3-2-4", title: "Cancelling in a congruence", mode: "supervision" },
    { id: "bop-5-21", title: "Cubes of congruent numbers", mode: "supervision" },
    { id: "bop-5-32", title: "Congruent numbers have the same remainder", mode: "supervision" },
  ],
  "num.gcd": [
    { id: "bop-7-32", title: "The values of \\gcd(n, n + 2)", mode: "auto" },
    { id: "sheet-3-2-6-numbers", title: "\\gcd(13a + 8b, 5a + 3b) with numbers", mode: "auto" },
    { id: "sheet-3-1-3", title: "The gcd divides every combination", mode: "supervision" },
    { id: "sheet-3-2-1", title: "When the gcd is one of the numbers", mode: "supervision" },
    { id: "sheet-3-2-6", title: "A gcd that does not change", mode: "supervision" },
    { id: "bop-5-31", title: "The gcd and the remainder", mode: "supervision" },
  ],
  "num.modular-arithmetic": [
    { id: "bop-6-17-remark", title: "Two more than a square, modulo 4", mode: "auto" },
    { id: "bop-5-17-largest", title: "Odd squares minus one", mode: "auto" },
    { id: "sheet-2-1-2", title: "Congruence respects the operations", mode: "supervision" },
    { id: "sheet-2-2-2", title: "Digit tests", mode: "supervision" },
    { id: "bop-6-17", title: "No square plus two is a multiple of four", mode: "supervision" },
  ],
  "num.euclid-algorithm": [
    { id: "notes-218-example-75", title: "The steps of \\gcd(13, 34)", mode: "auto" },
    { id: "sheet-4-2-3-d", title: "Fibonacci numbers are the slowest inputs", mode: "auto" },
    { id: "sheet-3-3-3", title: "Why the subtractive algorithm is right", mode: "supervision" },
    { id: "notes-224-theorem-79-bound", title: "The second number halves every two steps", mode: "supervision" },
    { id: "sheet-4-2-3-d-proof", title: "Fibonacci steps, by induction", mode: "supervision" },
  ],
  "prob.sampling-models": [
    { id: "ia-q12-four", title: "Four balls, four boxes", mode: "auto" },
    { id: "ia-q13", title: "A random increasing function", mode: "auto" },
    { id: "ia-q13-bijection", title: "Counting non-decreasing functions", mode: "supervision" },
    { id: "ia-q12-model", title: "Which outcomes are equally likely?", mode: "supervision" },
  ],
  "num.modular-integers": [
    { id: "notes-193-example-62-row", title: "A row of the table of \\mathbbZ_5", mode: "auto" },
    { id: "sheet-2-2-6-z6-additive", title: "Additive inverses in \\mathbbZ_6", mode: "auto" },
    { id: "sheet-2-1-4", title: "Associativity and additive inverses", mode: "supervision" },
    { id: "bop-11-5-8", title: "Addition is well defined", mode: "supervision" },
    { id: "notes-190-example-60", title: "\\mathbbZ_2 is the booleans", mode: "supervision" },
  ],
  "num.modular-exponentiation": [
    { id: "notes-132-totd-341", title: "A false witness to primality", mode: "auto" },
    { id: "notes-131-btw-witness", title: "Showing 341 is composite without factorising", mode: "auto" },
    { id: "sheet-2-2-5-flt", title: "No contradiction with Fermat", mode: "supervision" },
    { id: "squaring-cost", title: "Why repeated squaring is fast", mode: "supervision" },
  ],
  "num.extended-euclid": [
    { id: "sheet-3-1-4-a", title: "x · 30 + y · 22 = \\gcd(30, 22)", mode: "auto" },
    { id: "sheet-3-1-4-b", title: "A solution with 0 ≤ y' < 30", mode: "auto" },
    { id: "notes-255-example-90", title: "The notes' egcd(13, 34)", mode: "auto" },
    { id: "sheet-3-1-5", title: "One as a combination", mode: "supervision" },
    { id: "bop-7-4-proposition-7-1", title: "The gcd is the least positive combination", mode: "supervision" },
    { id: "notes-249-all-combinations", title: "Every solution", mode: "supervision" },
  ],
  "num.euclid-theorem": [
    { id: "bop-11-5-5", title: "No zero divisors in \\mathbbZ_5", mode: "auto" },
    { id: "bop-11-5-6", title: "Zero divisors in \\mathbbZ_6", mode: "auto" },
    { id: "sheet-3-1-6", title: "Square roots of one modulo a prime", mode: "supervision" },
    { id: "sheet-3-2-2", title: "Coprime divisors multiply", mode: "supervision" },
    { id: "sheet-3-3-1", title: "From a square to a divisor", mode: "supervision" },
    { id: "bop-7-29", title: "Euclid's theorem by Bezout", mode: "supervision" },
  ],
  "num.diffie-hellman": [
    { id: "notes-263-lemma-94", title: "Lemma 94 with numbers", mode: "auto" },
    { id: "notes-265-key-exchange", title: "Sending a key in three messages", mode: "auto" },
    { id: "notes-264-lemma-94-proof", title: "Why decryption undoes encryption", mode: "supervision" },
    { id: "notes-261-safety", title: "What an eavesdropper sees", mode: "supervision" },
    { id: "notes-266-rsa", title: "The RSA aside", mode: "supervision" },
  ],
  "prob.stirling-formula": [
    { id: "ia-q14-a-numbers", title: "The random walk returns to 0", mode: "auto" },
    { id: "ia-q3-stirling-derivation", title: "Deriving the deck estimate", mode: "supervision" },
    { id: "ia-q14-a", title: "The local limit at 0", mode: "supervision" },
    { id: "ia-q14-b", title: "The local limit everywhere", mode: "supervision" },
  ],
  "num.modular-inverse": [
    { id: "sheet-3-2-10-a", title: "77x \\equiv 11 \\pmod40", mode: "auto" },
    { id: "sheet-3-2-10-b", title: "12y \\equiv 30 \\pmod54", mode: "auto" },
    { id: "sheet-3-2-10-c", title: "A system of two congruences", mode: "auto" },
    { id: "sheet-3-2-12-inverse", title: "The inverse of [22^12,001]_175", mode: "auto" },
    { id: "sheet-2-2-6-z7-inverses", title: "The inverse table of \\mathbbZ_7", mode: "auto" },
    { id: "sheet-3-2-12", title: "Why the inverse exists", mode: "supervision" },
    { id: "notes-244-corollary-86", title: "\\mathbbZ_p is a field", mode: "supervision" },
  ],
  "prob.axioms": [
    { id: "ia-q4-countable-additivity", title: "Countable additivity with numbers", mode: "auto" },
    { id: "ia-q4-c", title: "Finite additivity from countable additivity", mode: "supervision" },
    { id: "schedule-countable-case", title: "Point masses give a probability measure", mode: "supervision" },
  ],
  "num.fundamental-theorem": [
    { id: "notes-304-example-98", title: "The power of 2 in 1224", mode: "auto" },
    { id: "notes-208-example-68", title: "How many divisors has 1224?", mode: "auto" },
    { id: "notes-302-homework", title: "Uniqueness by induction", mode: "supervision" },
    { id: "bop-10-4-theorem-10-1", title: "Uniqueness by a smallest counterexample", mode: "supervision" },
  ],
  "prob.axiom-consequences": [
    { id: "ia-q4-e-numbers", title: "The addition rule with numbers", mode: "auto" },
    { id: "ia-q4-b", title: "The complement rule", mode: "supervision" },
    { id: "ia-q4-e", title: "The addition rule for two events", mode: "supervision" },
    { id: "ia-q4-bounds", title: "The Bonferroni bounds for two events", mode: "supervision" },
  ],
  "num.prime-binomial": [
    { id: "notes-242-corollary-85", title: "The second half of Corollary 85", mode: "auto" },
    { id: "bop-4-21", title: "Book of Proof's version", mode: "supervision" },
    { id: "notes-116-lemmas-27-29", title: "The ends of the row and the proof by cases", mode: "supervision" },
  ],
  "num.fermat-little": [
    { id: "notes-132-totd-cubes", title: "Rubik's cubes, five at a time", mode: "auto" },
    { id: "sheet-2-2-7", title: "Exponents modulo p - 1", mode: "supervision" },
    { id: "sheet-2-2-9", title: "n^7 \\equiv n \\pmod42", mode: "supervision" },
    { id: "sheet-3-2-8", title: "n^13 \\equiv n \\pmod10", mode: "supervision" },
    { id: "notes-127-dropout", title: "The Dropout Lemmas", mode: "supervision" },
  ],
  "prob.inclusion-exclusion": [
    { id: "ia-q7-identity", title: "The identity with numbers", mode: "auto" },
    { id: "ia-q7", title: "Two counts of one event", mode: "supervision" },
    { id: "schedule-inclusion-exclusion", title: "Proving the formula", mode: "supervision" },
  ],
  "prob.continuity": [
    { id: "ia-q6-alternating", title: "Infinitely often but not eventually", mode: "auto" },
    { id: "ia-q6-continuity", title: "\"Eventually\" as a limit", mode: "supervision" },
    { id: "ia-q4-f-decreasing", title: "Continuity from above", mode: "supervision" },
  ],
  "prob.conditional-probability": [
    { id: "ia-q10-third-white", title: "The third draw", mode: "auto" },
    { id: "ia-q10-exchangeable", title: "Order does not matter", mode: "supervision" },
    { id: "schedule-conditional-measure", title: "\\mathbbP(· | B) is a probability measure", mode: "supervision" },
  ],
  "prob.subadditivity": [
    { id: "ia-q6-numbers", title: "The bound with numbers", mode: "auto" },
    { id: "ia-q6-subadditivity", title: "Countable subadditivity from the axioms", mode: "supervision" },
    { id: "ia-q6-c-converse", title: "The converse fails", mode: "supervision" },
  ],
  "prob.total-probability": [
    { id: "ia-q9-same-twice", title: "Voting the same way twice", mode: "auto" },
    { id: "ia-q8-reading", title: "Which probabilities are which?", mode: "supervision" },
    { id: "schedule-total-probability", title: "The law, for a countable partition", mode: "supervision" },
  ],
  "prob.independence": [
    { id: "ia-q11-by-independence", title: "The conjecture, by independence", mode: "supervision" },
    { id: "schedule-independence", title: "Pairwise is not enough", mode: "supervision" },
  ],
  "prob.bayes-formula": [
    { id: "ia-q9", title: "Voting the same way again", mode: "auto" },
    { id: "ia-q9-explain", title: "What the observation tells you", mode: "supervision" },
    { id: "schedule-bayes", title: "Bayes's formula for a partition", mode: "supervision" },
  ],
};
