/**
 * Glossary entries of the Preparation group D topics (sequences, series, sets, and proof),
 * kept in their own file so the group adds one line to glossary.ts. Same rules as
 * glossary.ts: computed numbers only, one or two plain sentences.
 */
import type { GlossaryEntry } from './glossary';
import { q } from './math';
import { math, t, type Rich } from './rich';

const g = (topic: string, id: string, term: string, definition: Rich, example: Rich, aliases?: readonly string[]): GlossaryEntry =>
  (aliases === undefined ? { id, term, definition, example, topic } : { id, term, definition, example, topic, aliases });

const GI = 'alg.geometric-sum-to-infinity';
const SU = 'sets.subsets';
const CP = 'sets.cartesian-product';
const IX = 'sets.indexed';
const SP = 'proof.set-proofs';
const DX = 'proof.disproof';
const SC = 'proof.smallest-counterexample';
const PM = 'comb.permutations';
const ME = 'pre.mutually-exclusive';
const AR = 'prob.addition-rule';
const AG = 'ineq.am-gm';
const FB = 'alg.fibonacci';
const SL = 'an.sequence-limits';
const RS = 'alg.recurrence-sequences';
const TL = 'alg.telescoping';
const SPW = 'alg.sums-of-powers';
const BR = 'alg.binomial-rational';
const DD = 'prob.discrete-distributions';
const MT = 'mat.matrices';

export const GLOSSARY_PREP_D: readonly GlossaryEntry[] = [
  g(GI, 'partial-sum', 'Partial sum', t`The sum ${math`S_{n}`} of the first ${math`n`} terms of a series. A series is studied through its partial sums.`, t`For ${math`${1} + \frac{${1}}{${2}} + \frac{${1}}{${4}} + \cdots`}, the third partial sum is ${math`${q(7, 4)}`}.`, ['running total']),
  g(GI, 'sum-to-infinity', 'Sum to infinity', t`The limit of the partial sums of a series, when they have one. A geometric series has one exactly when ${math`|r| < ${1}`}, and it is ${math`\frac{a}{${1} - r}`}.`, t`${math`${3} + ${1} + \frac{${1}}{${3}} + \cdots = \frac{${3}}{${1} - ${q(1, 3)}} = ${q(9, 2)}`}.`, ['infinite sum', 'sum of a convergent series', 'convergent series']),
  g(SU, 'subset', 'Subset', t`${math`A \subseteq B`} when every element of ${math`A`} is an element of ${math`B`}. Not the same as ${math`A \in B`}, which says ${math`A`} itself is listed in ${math`B`}.`, t`${math`\{${1}\} \subseteq \{${1}, ${2}\}`}, but ${math`\{${1}\} \notin \{${1}, ${2}\}`}.`, ['subset of', 'inclusion', 'proper subset', 'contained in']),
  g(SU, 'power-set', 'Power set', t`${math`\mathcal{P}(A)`}, the set of all subsets of ${math`A`}. A set with ${math`n`} elements has ${math`${2}^{n}`} subsets.`, t`${math`\mathcal{P}(\{${1}, ${2}\}) = \{\varnothing, \{${1}\}, \{${2}\}, \{${1}, ${2}\}\}`}, with ${4} elements.`, ['P(A)', 'set of all subsets']),
  g(CP, 'ordered-pair', 'Ordered pair', t`${math`(a, b)`}, with a first and a second entry: ${math`(a, b) = (c, d)`} exactly when ${math`a = c`} and ${math`b = d`}. Unlike a set, a pair remembers order.`, t`${math`(${3}, ${5}) \neq (${5}, ${3})`}, though ${math`\{${3}, ${5}\} = \{${5}, ${3}\}`}.`, ['pair', 'ordered list', 'tuple', 'triple']),
  g(CP, 'cartesian-product', 'Cartesian product', t`${math`A \times B = \{(a, b) : a \in A, b \in B\}`}, every ordered pair with first entry from ${math`A`} and second from ${math`B`}. It has ${math`|A| \cdot |B|`} elements.`, t`${math`\{${1}, ${2}\} \times \{a, b, c\}`} has ${6} pairs; ${math`\mathbb{R} \times \mathbb{R}`} is the plane.`, ['product of sets', 'A x B', 'Cartesian power']),
  g(IX, 'indexed-family', 'Indexed family of sets', t`A set ${math`A_{\alpha}`} for each ${math`\alpha`} in an index set ${math`I`}. Its union is everything in some ${math`A_{\alpha}`}; its intersection is what is in every ${math`A_{\alpha}`}.`, t`${math`A_{n} = [${0}, n]`} for ${math`n \in \mathbb{N}`}: the union is ${math`[${0}, \infty)`} and the intersection is ${math`[${0}, ${1}]`}.`, ['indexed sets', 'family of sets', 'big union', 'big intersection']),
  g(IX, 'index-set', 'Index set', t`The set ${math`I`} of labels in an indexed family ${math`(A_{\alpha})_{\alpha \in I}`}. It may be finite or infinite, and need not be a set of numbers.`, t`In ${math`\bigcup_{X \in \mathcal{P}(\mathbb{N})} X`}, the index set is ${math`\mathcal{P}(\mathbb{N})`}.`, ['indexing set', 'labels']),
  g(SP, 'element-chasing', 'Element chasing', t`Proving ${math`A \subseteq B`} by taking an arbitrary ${math`x \in A`} and deducing ${math`x \in B`} from the definitions. Because ${math`x`} was arbitrary, the argument covers every element.`, t`If ${math`x = ${12}n`}, then ${math`x = ${2}(${6}n)`}, so every multiple of ${12} is even.`, ['arbitrary element', 'chasing an element']),
  g(SP, 'double-inclusion', 'Proof by double inclusion', t`Proving ${math`A = B`} by proving ${math`A \subseteq B`} and ${math`B \subseteq A`}, each by element chasing.`, t`${math`\{${6}n\} = \{${2}n\} \cap \{${3}n\}`} needs both inclusions; ${math`\{${12}n\} \subseteq \{${6}n\}`} alone does not give equality.`, ['two inclusions', 'set equality proof']),
  g(DX, 'disproof-of-existence', 'Disproof of an existence statement', t`Showing that ${math`\exists x\, P(x)`} is false by proving its negation ${math`\forall x\, \neg P(x)`}, with a general argument or by contradiction. No search of examples can do this.`, t`No integers ${math`a, b`} have ${math`${42}a + ${7}b = ${1}`}: the left side is always a multiple of ${7}.`, ['disproving existence', 'proving impossibility']),
  g(SC, 'well-ordering-principle', 'Well-ordering principle', t`Every non-empty set of natural numbers has a smallest element. It fails for the positive rationals and for the integers.`, t`The set of ${math`n`} with ${math`${2}^{n} > ${100}`} has smallest element ${7}.`, ['well ordering', 'least element principle']),
  g(SC, 'smallest-counterexample', 'Proof by smallest counterexample', t`To prove ${math`S_{n}`} for every natural number ${math`n`}: check ${math`S_{${1}}`}, suppose some ${math`S_{n}`} fails, take the smallest such ${math`k`}, and use the true ${math`S_{k - ${1}}`} to contradict the failure of ${math`S_{k}`}.`, t`If ${math`${5}^{k - ${1}} - ${1} = ${4}a`}, then ${math`${5}^{k} - ${1} = ${4}(${5}a + ${1})`}, so ${4} divides ${math`${5}^{n} - ${1}`} for every ${math`n`}.`, ['minimal counterexample', 'least counterexample', 'minimum criminal']),
  g(PM, 'permutation', 'Permutation', t`An ordered list of ${math`r`} different objects chosen from ${math`n`}. There are ${math`P(n, r) = \frac{n!}{(n - r)!}`} of them; with ${math`r = n`}, ${math`n!`}.`, t`Gold, silver and bronze among ${8} runners: ${math`${8} \times ${7} \times ${6} = ${336}`} podiums.`, ['nPr', 'P(n, r)', 'ordered selection', 'arrangement of r from n']),
  g(ME, 'mutually-exclusive', 'Mutually exclusive events', t`Events that cannot both happen: ${math`A \cap B = \varnothing`}. For them, ${math`P(A \text{ or } B) = P(A) + P(B)`}.`, t`One die: "a six" and "a one" are mutually exclusive, so ${math`P(\text{six or one}) = ${q(1, 3)}`}.`, ['exclusive events', 'disjoint events', 'cannot happen together']),
  g(ME, 'exhaustive-events', 'Exhaustive events', t`Events of which at least one must happen: together they cover the sample space. If they are also mutually exclusive, their probabilities sum to ${1}.`, t`"Odd total" and "even total" for two dice are exhaustive and exclusive: ${math`${q(1, 2)} + ${q(1, 2)} = ${1}`}.`, ['exhaustive', 'complete set of outcomes']),
  g(AR, 'addition-rule', 'Addition rule', t`For any two events, ${math`P(A \cup B) = P(A) + P(B) - P(A \cap B)`}: adding counts the overlap twice, so it is taken off once.`, t`A card is a picture card or a heart with probability ${math`\frac{${12} + ${13} - ${3}}{${52}} = ${q(11, 26)}`}.`, ['general addition rule', 'P(A or B)', 'or rule']),
  g(AG, 'arithmetic-mean', 'Arithmetic mean', t`The ordinary average ${math`\frac{a_{${1}} + \cdots + a_{n}}{n}`}. For non-negative numbers it is at least the geometric mean.`, t`The arithmetic mean of ${2} and ${8} is ${5}.`, ['AM', 'average', 'mean']),
  g(AG, 'geometric-mean', 'Geometric mean', t`For non-negative numbers, ${math`\sqrt[n]{a_{${1}} \cdots a_{n}}`}: for two numbers, the side of a square with the same area as the ${math`a`} by ${math`b`} rectangle.`, t`The geometric mean of ${2} and ${8} is ${math`\sqrt{${16}} = ${4}`}, below their arithmetic mean ${5}.`, ['GM']),
  g(FB, 'fibonacci-numbers', 'Fibonacci numbers', t`${math`F_{${0}} = ${0}`}, ${math`F_{${1}} = ${1}`}, and ${math`F_{n + ${1}} = F_{n} + F_{n - ${1}}`}: each term the sum of the two before. Closed form ${math`F_{n} = \frac{\varphi^{n} - \psi^{n}}{\sqrt{${5}}}`}.`, t`${math`F_{${10}} = ${55}`}; Cassini: ${math`F_{${11}}F_{${9}} - F_{${10}}^{${2}} = ${89} \times ${34} - ${3025} = ${1}`}.`, ['Fibonacci sequence', 'F_n', 'Binet formula', 'Cassini identity']),
  g(FB, 'golden-ratio', 'Golden ratio', t`${math`\varphi = \frac{${1} + \sqrt{${5}}}{${2}}`}, the positive root of ${math`x^{${2}} = x + ${1}`}. Ratios of consecutive Fibonacci numbers tend to it.`, t`${math`\frac{F_{${11}}}{F_{${10}}} = \frac{${89}}{${55}}`}, already close to ${math`\varphi`}.`, ['phi', 'golden section']),
  g(SL, 'limit-of-sequence', 'Limit of a sequence', t`${math`x_{n} \to a`} when for every ${math`\varepsilon > ${0}`} there is an ${math`N`} with ${math`|x_{n} - a| < \varepsilon`} for all ${math`n \ge N`}: eventually within any tolerance, and staying there.`, t`${math`\frac{${1}}{n} \to ${0}`}: for ${math`\varepsilon = ${q(1, 100)}`}, ${math`N = ${101}`} works.`, ['limit', 'converges', 'convergent sequence', 'tends to']),
  g(SL, 'divergent-sequence', 'Divergent sequence', t`A sequence with no real limit: its terms may grow without bound, or keep oscillating.`, t`${math`(-${1})^{n}`} and ${math`${2}^{n}`} both diverge.`, ['diverges', 'divergence']),
  g(RS, 'recurrence-relation', 'Recurrence relation', t`A rule giving each term of a sequence from earlier ones, such as ${math`u_{n + ${1}} = f(u_{n})`}, together with the starting term or terms.`, t`${math`u_{${1}} = ${3}`}, ${math`u_{n + ${1}} = ${2}u_{n} - ${1}`} gives ${math`${3}, ${5}, ${9}, ${17}, \ldots`}.`, ['recurrence', 'iterative sequence', 'term-to-term rule']),
  g(RS, 'fixed-point', 'Fixed point', t`A value ${math`l`} with ${math`f(l) = l`}. If a sequence ${math`u_{n + ${1}} = f(u_{n})`} converges, its limit is a fixed point (when the limit laws apply to ${math`f`}).`, t`${math`f(u) = ${37} - \frac{${36}}{u}`} has fixed points ${1} and ${36}.`, ['fixed point equation']),
  g(RS, 'periodic-sequence', 'Periodic sequence', t`A sequence with ${math`u_{n + p} = u_{n}`} for all ${math`n`}; the smallest such ${math`p \ge ${1}`} is the period. It converges only if it is constant.`, t`${math`${4}, ${1}, -${3}, -${4}, -${1}, ${3}, ${4}, \ldots`} has period ${6}.`, ['period', 'periodic']),
  g(TL, 'method-of-differences', 'Method of differences', t`Summing ${math`\sum_{r = ${1}}^{n} (f(r) - f(r - ${1}))`} as ${math`f(n) - f(${0})`}, after writing each term as a difference, often by partial fractions.`, t`${math`\sum_{r = ${1}}^{${9}} \frac{${1}}{r(r + ${1})} = ${1} - \frac{${1}}{${10}} = ${q(9, 10)}`}.`, ['differences', 'telescoping series']),
  g(TL, 'product-notation', 'Product notation', t`${math`\prod_{r = ${1}}^{n} a_{r} = a_{${1}} a_{${2}} \cdots a_{n}`}, the multiplying counterpart of ${math`\sum`}. A product of ratios ${math`\frac{g(r)}{g(r - ${1})}`} telescopes to ${math`\frac{g(n)}{g(${0})}`}.`, t`${math`\prod_{r = ${1}}^{${4}} r = ${24}`}, and ${math`\prod_{r = ${1}}^{${9}} \frac{r}{r + ${1}} = ${q(1, 10)}`}.`, ['product', 'pi notation', 'telescoping product']),
  g(SPW, 'sum-of-squares', 'Sums of squares and cubes', t`${math`\sum_{r = ${1}}^{n} r^{${2}} = \frac{n(n + ${1})(${2}n + ${1})}{${6}}`} and ${math`\sum_{r = ${1}}^{n} r^{${3}} = \left(\frac{n(n + ${1})}{${2}}\right)^{${2}}`}.`, t`${math`${1} + ${4} + \cdots + ${100} = ${385}`} and ${math`${1} + ${8} + \cdots + ${1000} = ${3025}`}.`, ['sum of squares', 'sum of cubes', 'power sums']),
  g(BR, 'binomial-series', 'Binomial series', t`${math`(${1} + x)^{n} = \sum_{k \ge ${0}} \binom{n}{k}x^{k}`} with ${math`\binom{n}{k} = \frac{n(n - ${1})\cdots(n - k + ${1})}{k!}`}, for any rational ${math`n`}; it is valid for ${math`|x| < ${1}`}.`, t`${math`\sqrt{${1} + x} = ${1} + \frac{x}{${2}} - \frac{x^{${2}}}{${8}} + \cdots`}.`, ['binomial expansion for rational powers', 'general binomial theorem']),
  g(DD, 'distribution-table', 'Probability distribution of a discrete random variable', t`The list of values ${math`x_{i}`} of a discrete random variable with their probabilities ${math`P(X = x_{i})`}, which are non-negative and add to ${1}.`, t`Heads in three tosses: ${math`${0}, ${1}, ${2}, ${3}`} with probabilities ${math`${q(1, 8)}, ${q(3, 8)}, ${q(3, 8)}, ${q(1, 8)}`}.`, ['distribution', 'probability table', 'discrete distribution']),
  g(MT, 'matrix', 'Matrix', t`A rectangular array of numbers. Matrices of one size add entry by entry; the product ${math`AB`} has entries ${math`\sum_{k} a_{ik}b_{kj}`}, a row of ${math`A`} times a column of ${math`B`}, and usually ${math`AB \neq BA`}.`, t`${math`\begin{pmatrix} ${1} & ${2} \\ ${3} & ${4} \end{pmatrix}\begin{pmatrix} ${0} \\ ${1} \end{pmatrix} = \begin{pmatrix} ${2} \\ ${4} \end{pmatrix}`}.`, ['matrices', 'matrix product']),
  g(MT, 'determinant', 'Determinant', t`For ${math`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`}, the number ${math`ad - bc`}: the factor by which the transformation scales areas. The matrix is invertible exactly when it is not ${0}.`, t`${math`\det\begin{pmatrix} ${2} & ${1} \\ ${5} & ${3} \end{pmatrix} = ${6} - ${5} = ${1}`}.`, ['det', 'ad - bc']),
  g(MT, 'inverse-matrix', 'Inverse matrix', t`${math`A^{-${1}}`} with ${math`AA^{-${1}} = A^{-${1}}A = I`}. For a ${math`${2} \times ${2}`} matrix it is ${math`\frac{${1}}{ad - bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}`}.`, t`${math`\begin{pmatrix} ${2} & ${1} \\ ${5} & ${3} \end{pmatrix}^{-${1}} = \begin{pmatrix} ${3} & -${1} \\ -${5} & ${2} \end{pmatrix}`}.`, ['inverse', 'non-singular matrix']),
];
