/**
 * Glossary entries for the Part V group A topics (expectation and variance, indicators,
 * first-step analysis, difference equations, random walks). Kept in their own file so the
 * shared glossary changes by one import and one spread; checked like every other entry.
 */
import type { GlossaryEntry } from './glossary';
import { q } from './math';
import { listOf, math, t, type Rich } from './rich';

const g = (topic: string, id: string, term: string, definition: Rich, example: Rich, aliases?: readonly string[]): GlossaryEntry =>
  (aliases === undefined ? { id, term, definition, example, topic } : { id, term, definition, example, topic, aliases });

const EX = 'rv.expectation';
const TS = 'rv.tail-sum';
const RA = 'comb.restricted-arrangements';
const FS = 'prob.first-step';
const QE = 'pre.quadratic-equations';
const VA = 'rv.variance';
const EA = 'rv.expectation-algebra';
const IV = 'rv.indicators';
const AG = 'alg.arithmetico-geometric';
const LR = 'alg.linear-recurrences';
const GR = 'rw.gamblers-ruin';
const AT = 'rw.absorption-time';

export const PARTV_A_GLOSSARY: readonly GlossaryEntry[] = [
  g(EX, 'expectation', 'Expectation', t`The mean of a random variable: ${math`E(X) = \sum_{x} x \, P(X = x)`}, each value weighted by its probability. It is the long-run average of ${math`X`} over many repetitions.`, t`A fair die has ${math`E(X) = \frac{${1} + ${2} + \cdots + ${6}}{${6}} = ${q(7, 2)}`}, a value it never shows.`, ['expected value', 'mean', 'E(X)']),
  g(EX, 'fair-game', 'Fair game', t`A game whose expected gain is ${0}: on average a player neither wins nor loses. The fair stake is the expected prize.`, t`A prize of £${6} on a six is fair at a stake of £${1}: ${math`${6} \times ${q(1, 6)} = ${1}`}.`, ['fair stake', 'fair bet']),
  g(TS, 'tail-sum-formula', 'Tail-sum formula', t`For ${math`X`} taking values ${0}, ${1}, ${2}, and so on: ${math`E(X) = \sum_{n \ge ${1}} P(X \ge n)`}, the sum of the tail probabilities.`, t`The smaller of two dice has ${math`P(X \ge n) = \left(\frac{${7} - n}{${6}}\right)^{${2}}`}, so ${math`E(X) = \frac{${36} + ${25} + ${16} + ${9} + ${4} + ${1}}{${36}} = ${q(91, 36)}`}.`, ['tail sum', 'tail probabilities']),
  g(RA, 'block-method', 'Block method', t`To count arrangements with a group kept together, glue the group into one block, arrange the block with the other objects, then multiply by the orders inside the block.`, t`Four men together in a line with six women: ${math`${7}! \times ${4}!`} of the ${math`${10}!`} orders, probability ${q(1, 30)}.`, ['rope', 'glue together', 'kept together']),
  g(RA, 'gap-method', 'Gap method', t`To count arrangements with no two of a group next to each other, arrange the others first, then place the group in different gaps between them, counting both ends as gaps.`, t`Six women leave ${7} gaps, so four men can be kept apart in ${math`${6}! \times ${7} \times ${6} \times ${5} \times ${4}`} ways.`, ['gaps', 'kept apart', 'no two together']),
  g(FS, 'first-step-analysis', 'First-step analysis', t`Finding a probability or an expected value for a repeated experiment by conditioning on its first step. A step that leads back to the start brings back the unknown itself, giving an equation to solve.`, t`Toss two coins; HH wins, TT repeats, anything else loses: ${math`x = \frac{${1}}{${4}} + \frac{${1}}{${4}}x`}, so ${math`x = ${q(1, 3)}`}.`, ['first step', 'conditioning on the first step', 'first-step equations']),
  g(QE, 'quadratic-formula', 'Quadratic formula', t`The roots of ${math`ax^{${2}} + bx + c = ${0}`}, with ${math`a \ne ${0}`}, are ${math`x = \frac{-b \pm \sqrt{b^{${2}} - ${4}ac}}{${2}a}`}. It comes from completing the square.`, t`${math`x^{${2}} - ${5}x + ${6} = ${0}`}: ${math`x = \frac{${5} \pm \sqrt{${25} - ${24}}}{${2}}`}, so ${math`x = ${3}`} or ${math`x = ${2}`}.`, ['formula', 'roots of a quadratic', 'solving a quadratic']),
  g(QE, 'discriminant', 'Discriminant', t`The number ${math`b^{${2}} - ${4}ac`} for the quadratic ${math`ax^{${2}} + bx + c`}. Two real roots when it is positive, one repeated root when it is ${0}, none when it is negative.`, t`${math`x^{${2}} + ${2}x + ${5}`} has discriminant ${math`${4} - ${20} = -${16}`}, so it has no real roots.`, ['b^2 - 4ac', 'repeated root']),
  g(VA, 'variance', 'Variance', t`The mean squared distance of a random variable from its mean: ${math`\mathrm{Var}(X) = E\left((X - \mu)^{${2}}\right) = E(X^{${2}}) - \mu^{${2}}`}. It is never negative, and ${0} only when ${math`X`} is constant.`, t`A fair die: ${math`\frac{${91}}{${6}} - \left(\frac{${7}}{${2}}\right)^{${2}} = ${q(35, 12)}`}.`, ['Var(X)', 'spread', 'mean of the squares minus the square of the mean']),
  g(VA, 'standard-deviation', 'Standard deviation', t`The square root of the variance, ${math`\sigma = \sqrt{\mathrm{Var}(X)}`}: a measure of spread in the same units as ${math`X`}.`, t`${math`X \sim B(${16}, \frac{${1}}{${2}})`} has variance ${4} and standard deviation ${2}.`, ['sd', 'sigma']),
  g(EA, 'linearity-of-expectation', 'Linearity of expectation', t`${math`E(aX + bY + c) = aE(X) + bE(Y) + c`} for any random variables, independent or not. So the mean of a sum is the sum of the means.`, t`Two dice, however they are linked, have total with mean ${math`${q(7, 2)} + ${q(7, 2)} = ${7}`}.`, ['linearity', 'E(X + Y) = E(X) + E(Y)']),
  g(EA, 'variance-of-sum', 'Variance of a sum', t`${math`\mathrm{Var}(X + Y) = \mathrm{Var}(X) + \mathrm{Var}(Y) + ${2}\operatorname{cov}(X, Y)`}. For independent ${math`X`} and ${math`Y`} the covariance is ${0}, so ${math`\mathrm{Var}(aX + bY + c) = a^{${2}}\mathrm{Var}(X) + b^{${2}}\mathrm{Var}(Y)`}: variances add, even for a difference.`, t`Two dice: ${math`\mathrm{Var}(X_{${1}} - X_{${2}}) = ${q(35, 12)} + ${q(35, 12)} = ${q(35, 6)}`}.`, ['variances add', 'Var(X + Y)', 'variance of a sum of independent variables']),
  g(IV, 'indicator-variable', 'Indicator variable', t`The random variable ${math`I_{A}`} that is ${1} when the event ${math`A`} happens and ${0} otherwise. Its mean is ${math`P(A)`} and its variance ${math`P(A)(${1} - P(A))`}; a count is a sum of indicators.`, t`The number of sixes in ${10} throws is a sum of ${10} indicators, each with mean ${q(1, 6)}, so its mean is ${q(5, 3)}.`, ['indicator', 'indicator function', 'Bernoulli variable']),
  g(IV, 'record', 'Record', t`In a sequence, an entry is a record when it beats every earlier entry. In a random order of ${math`n`} distinct values, entry ${math`i`} is a record with probability ${math`\frac{${1}}{i}`}, independently of the others.`, t`In ${listOf([3, 5, 1, 4, 2])}, read as rankings where smaller is better, the records are at positions ${1} and ${3}.`, ['record year', 'record value']),
  g(AG, 'arithmetico-geometric-series', 'Arithmetico-geometric series', t`A series whose terms are an arithmetic sequence times a geometric one, ${math`\sum (a + nd)r^{n}`}. For ${math`|r| < ${1}`} it sums to ${math`\frac{a}{${1} - r} + \frac{dr}{(${1} - r)^{${2}}}`}, found by subtracting ${math`r`} times the series.`, t`${math`${1} + \frac{${2}}{${2}} + \frac{${3}}{${4}} + \frac{${4}}{${8}} + \cdots = \frac{${1}}{(${1} - \frac{${1}}{${2}})^{${2}}} = ${4}`}.`, ['sum of n r^n', 'S - rS']),
  g(LR, 'difference-equation', 'Difference equation', t`An equation that gives each term of a sequence from earlier terms, such as ${math`u_{n + ${1}} = au_{n} + bu_{n - ${1}} + c`}. Linear ones are solved like differential equations: a general solution of the homogeneous part plus one particular solution.`, t`${math`u_{n + ${1}} = ${2}u_{n} + ${1}`}, ${math`u_{${0}} = ${0}`}: the fixed point is ${math`-${1}`}, so ${math`u_{n} = ${2}^{n} - ${1}`}.`, ['recurrence relation', 'recurrence', 'linear recurrence']),
  g(LR, 'auxiliary-equation', 'Auxiliary equation', t`For ${math`u_{n + ${1}} = au_{n} + bu_{n - ${1}}`}, the equation ${math`\lambda^{${2}} = a\lambda + b`} that ${math`u_{n} = \lambda^{n}`} must satisfy. Distinct roots ${math`\alpha`}, ${math`\beta`} give ${math`A\alpha^{n} + B\beta^{n}`}; a repeated root gives ${math`(A + Bn)\alpha^{n}`}.`, t`${math`u_{n + ${1}} = u_{n} + ${2}u_{n - ${1}}`} has ${math`\lambda^{${2}} - \lambda - ${2} = (\lambda - ${2})(\lambda + ${1})`}, so ${math`u_{n} = A \cdot ${2}^{n} + B(-${1})^{n}`}.`, ['characteristic equation', 'characteristic polynomial']),
  g(GR, 'simple-random-walk', 'Simple random walk', t`The sums ${math`S_{n} = X_{${1}} + \cdots + X_{n}`} of independent steps, each ${1} with probability ${math`p`} and ${math`-${1}`} with probability ${math`q = ${1} - p`}. Symmetric when ${math`p = q = \frac{${1}}{${2}}`}.`, t`A gambler betting £${1} a time at even chances: her fortune is a symmetric simple random walk.`, ['random walk', 'SRW']),
  g(GR, 'gamblers-ruin', "Gambler's ruin", t`A simple random walk from ${math`k`} stopped at ${0} or ${math`N`}. It reaches ${math`N`} first with probability ${math`\frac{${1} - \rho^{k}}{${1} - \rho^{N}}`}, where ${math`\rho = \frac{q}{p}`}, or ${math`\frac{k}{N}`} when ${math`p = q`}.`, t`With £${2}, aiming for £${4} at even chances: ${math`\frac{${2}}{${4}} = ${q(1, 2)}`}.`, ['ruin probability', 'gambler ruin']),
  g(GR, 'absorbing-barrier', 'Absorbing barrier', t`A state a random walk never leaves once it arrives, such as ${0} for a gambler with no money. The walk stops there.`, t`In gambler's ruin on ${math`${0}, \ldots, N`}, both ${0} and ${math`N`} are absorbing barriers.`, ['absorbing state', 'barrier']),
  g(AT, 'expected-duration', 'Expected duration', t`The mean time a random walk takes to reach an absorbing barrier, ${math`m_{k}`} from state ${math`k`}. It satisfies ${math`m_{k} = ${1} + pm_{k + ${1}} + qm_{k - ${1}}`}, and for a fair walk on ${math`${0}, \ldots, N`} it is ${math`k(N - k)`}.`, t`A fair gambler with £${2} aiming for £${6} expects ${math`${2} \times ${4} = ${8}`} bets.`, ['mean time to absorption', 'absorption time', 'duration of the game']),
];
