/**
 * Glossary entries for the Part V continuous random variable topics (group B), kept apart
 * from glossary.ts so the four Part V groups merge without conflicts; glossary.ts spreads
 * them into GLOSSARY. Same rules as glossary.ts: computed numbers, LaTeX for mathematics.
 */
import type { GlossaryEntry } from './glossary';
import { q } from './math';
import { math, t, type Rich } from './rich';

const g = (topic: string, id: string, term: string, definition: Rich, example: Rich, aliases?: readonly string[]): GlossaryEntry =>
  (aliases === undefined ? { id, term, definition, example, topic } : { id, term, definition, example, topic, aliases });

const PDF = 'rv.pdf';
const CS = 'rv.continuous-summaries';
const CDF = 'rv.cdf-method';
const ND = 'prob.normal-distribution';
const NA = 'prob.normal-approximation';
const EX = 'prob.exponential-distribution';
const JD = 'rv.joint-densities';
const TR = 'rv.transformations';
const GP = 'prob.geometric-probability';
const SIM = 'rv.simulation';

export const PARTV_B_GLOSSARY: readonly GlossaryEntry[] = [
  g(PDF, 'continuous-random-variable', 'Continuous random variable', t`A random variable that takes every value in an interval, with probabilities given by a density. Each single value has probability ${0}.`, t`The time until a bus arrives, uniform between ${0} and ${10} minutes: ${math`P(X = ${3}) = ${0}`}, but ${math`P(${2} \le X \le ${4}) = ${q(1, 5)}`}.`, ['continuous variable', 'continuous distribution']),
  g(PDF, 'density-function', 'Probability density function', t`A function ${math`f \ge ${0}`} with total area ${1}, such that ${math`P(a \le X \le b) = \int_{a}^{b} f(x)\,dx`}. Its value is probability per unit length, not a probability.`, t`${math`f(x) = ${2}x`} on ${math`[${0}, ${1}]`} is a density: its area is ${1}, and ${math`P(X \le \tfrac{${1}}{${2}}) = ${q(1, 4)}`}.`, ['pdf', 'density', 'probability density']),
  g(PDF, 'cumulative-distribution-function', 'Distribution function', t`${math`F(x) = P(X \le x)`}. For a continuous random variable, ${math`F(x) = \int_{-\infty}^{x} f(t)\,dt`} and ${math`F' = f`}.`, t`For the density ${math`${2}x`} on ${math`[${0}, ${1}]`}, ${math`F(x) = x^{${2}}`} there.`, ['cdf', 'cumulative distribution function', 'c.d.f.']),
  g(PDF, 'uniform-distribution', 'Uniform distribution', t`${math`X \sim U(a, b)`} has constant density ${math`\frac{${1}}{b - a}`} on ${math`[a, b]`}: a subinterval's probability is its share of the length.`, t`For ${math`U(${0}, ${60})`}, ${math`P(${10} \le X \le ${25}) = ${q(15, 60)}`}.`, ['uniform', 'U(a, b)', 'continuous uniform']),
  g(CS, 'median-of-density', 'Median', t`For a continuous random variable, the value ${math`m`} with ${math`F(m) = \tfrac{${1}}{${2}}`}: half the area under the density lies on each side.`, t`For the density ${math`${2}x`} on ${math`[${0}, ${1}]`}, ${math`m^{${2}} = \tfrac{${1}}{${2}}`}, so ${math`m = \tfrac{${1}}{\sqrt{${2}}}`}.`, ['median value', 'middle value']),
  g(CS, 'mode-of-density', 'Mode', t`For a continuous random variable, a value where the density is largest. There may be more than one.`, t`The density ${math`r e^{-r^{${2}}/${2}}`} has derivative ${math`(${1} - r^{${2}})e^{-r^{${2}}/${2}}`}, so its mode is ${1}.`, ['modal value']),
  g(CDF, 'cdf-method', 'Distribution function method', t`To find the density of ${math`Y = g(X)`}: write ${math`F_{Y}(y) = P(g(X) \le y)`} as an event about ${math`X`}, use ${math`F_{X}`}, and differentiate.`, t`For ${math`X`} uniform on ${math`[${0}, ${1}]`}, ${math`F_{X^{${2}}}(y) = P(X \le \sqrt{y}) = \sqrt{y}`}, so ${math`X^{${2}}`} has density ${math`\frac{${1}}{${2}\sqrt{y}}`}.`, ['CDF method', 'change of variable', 'transforming a density']),
  g(ND, 'normal-distribution', 'Normal distribution', t`${math`N(\mu, \sigma^{${2}})`} has the bell-shaped density ${math`\frac{${1}}{\sigma\sqrt{${2}\pi}}e^{-(x - \mu)^{${2}}/(${2}\sigma^{${2}})}`}, with mean ${math`\mu`} and variance ${math`\sigma^{${2}}`}.`, t`${math`N(${100}, ${225})`} has mean ${100} and standard deviation ${15}.`, ['Gaussian', 'bell curve', 'N(mu, sigma^2)']),
  g(ND, 'standard-normal', 'Standard normal', t`${math`Z \sim N(${0}, ${1})`}, with distribution function ${math`\Phi`}. Any normal ${math`X`} standardises to ${math`Z = (X - \mu)/\sigma`}.`, t`For ${math`X \sim N(${50}, ${16})`}, ${math`P(X < ${54}) = \Phi(${1})`}.`, ['Z', 'Phi', 'standardise', 'z-score']),
  g(NA, 'continuity-correction', 'Continuity correction', t`When a normal variable ${math`Y`} approximates a whole-number variable ${math`X`}, each value ${math`k`} stands for the interval from ${math`k - \tfrac{${1}}{${2}}`} to ${math`k + \tfrac{${1}}{${2}}`}, so cut-offs move half a unit.`, t`${math`P(X \le ${55}) \approx P(Y < ${55.5})`} and ${math`P(X = ${100}) \approx P(${99.5} < Y < ${100.5})`}.`, ['half-unit correction']),
  g(EX, 'exponential-distribution', 'Exponential distribution', t`${math`X \sim \mathrm{Exp}(\lambda)`} has density ${math`\lambda e^{-\lambda x}`} for ${math`x \ge ${0}`}: ${math`P(X > x) = e^{-\lambda x}`} and ${math`E(X) = ${1}/\lambda`}. It models waiting times.`, t`A bulb lasting ${math`\mathrm{Exp}(${q(1, 2)})`} years has mean life ${2} years and outlasts ${2} years with probability ${math`e^{-${1}}`}.`, ['Exp(lambda)', 'exponential', 'waiting time']),
  g(EX, 'memoryless-property', 'Memoryless property', t`${math`P(X > s + t \mid X > s) = P(X > t)`}: having waited ${math`s`}, the remaining wait has the same distribution as a fresh one. Among continuous distributions, only the exponential has it.`, t`A server with ${math`\mathrm{Exp}(${q(1, 4)})`} lifetime that has run ${6} hours lasts ${2} more with probability ${math`e^{-${q(1, 2)}}`}, as a new one would.`, ['memorylessness', 'lack of memory']),
  g(JD, 'joint-density', 'Joint density', t`A function ${math`f(x, y) \ge ${0}`} with total volume ${1}, such that ${math`P((X, Y) \in A) = \iint_{A} f(x, y)\,dx\,dy`}.`, t`Two independent uniforms on ${math`[${0}, ${1}]`} have joint density ${1} on the unit square, so ${math`P(X + Y \le ${1}) = ${q(1, 2)}`}, the area of a triangle.`, ['joint pdf', 'bivariate density', 'joint distribution']),
  g(JD, 'marginal-density', 'Marginal density', t`The density of one variable alone, found by integrating the joint density over the other: ${math`f_{X}(x) = \int f(x, y)\,dy`}.`, t`For ${math`f(x, y) = x + y`} on the unit square, ${math`f_{X}(x) = x + \tfrac{${1}}{${2}}`}.`, ['marginal', 'marginal distribution']),
  g(TR, 'change-of-variables', 'Change of variables formula', t`For a one to one smooth map ${math`(U, V) = T(X, Y)`}: ${math`f_{U,V}(u, v) = f_{X,Y}(x(u, v), y(u, v))\,|J|`}, with ${math`J`} the Jacobian of the inverse map.`, t`For ${math`U = X + Y`}, ${math`V = X - Y`}, ${math`|J| = \tfrac{${1}}{${2}}`}, so ${math`f_{U,V}(u, v) = \tfrac{${1}}{${2}}f_{X,Y}\left(\tfrac{u + v}{${2}}, \tfrac{u - v}{${2}}\right)`}.`, ['transformation formula', 'Jacobian formula', 'transforming a joint density']),
  g(TR, 'jacobian', 'Jacobian', t`The determinant ${math`\frac{\partial(x, y)}{\partial(u, v)}`} of the matrix of partial derivatives of ${math`(x, y)`} with respect to ${math`(u, v)`}: the factor by which the map from ${math`(u, v)`} to ${math`(x, y)`} scales small areas.`, t`Polar coordinates ${math`x = r\cos\theta`}, ${math`y = r\sin\theta`} have Jacobian ${math`r`}.`, ['Jacobian determinant', 'J']),
  g(GP, 'buffons-needle', "Buffon's needle", t`A needle of length ${math`\ell`} dropped at random on parallel lines ${math`d \ge \ell`} apart crosses a line with probability ${math`\frac{${2}\ell}{\pi d}`}.`, t`A needle half as long as the gap crosses with probability ${math`${1}/\pi \approx ${Number((1 / Math.PI).toFixed(4))}`}.`, ['Buffon', 'needle problem']),
  g(GP, 'bertrands-paradox', "Bertrand's paradox", t`"A random chord of a circle" has no single meaning: three natural uniform models give three different chances that the chord is longer than a side of the inscribed equilateral triangle.`, t`Uniform endpoints give ${q(1, 3)}, a uniform distance from the centre gives ${q(1, 2)}, and a uniform midpoint gives ${q(1, 4)}.`, ['Bertrand', 'random chord']),
  g(SIM, 'inverse-transform-sampling', 'Inverse transform sampling', t`If ${math`F`} is a continuous, strictly increasing distribution function and ${math`U`} is uniform on ${math`(${0}, ${1})`}, then ${math`F^{-${1}}(U)`} has distribution function ${math`F`}.`, t`${math`-\ln(${1} - U)`} is ${math`\mathrm{Exp}(${1})`}, since ${math`F(x) = ${1} - e^{-x}`} inverts to ${math`-\ln(${1} - u)`}.`, ['inverse transform', 'inversion method', 'quantile transform']),
  g(SIM, 'box-muller', 'Box-Muller transform', t`From independent uniforms ${math`U_{${1}}, U_{${2}}`}: ${math`R = \sqrt{-${2}\ln U_{${1}}}`} and ${math`\Theta = ${2}\pi U_{${2}}`} give independent standard normals ${math`R\cos\Theta`} and ${math`R\sin\Theta`}.`, t`${math`u_{${1}} = e^{-${2}}`} and ${math`u_{${2}} = \tfrac{${1}}{${4}}`} give ${math`R = ${2}`}, ${math`\Theta = \pi/${2}`}: the pair ${math`(${0}, ${2})`}.`, ['Box Muller', 'polar method', 'normal simulation']),
  g(SIM, 'rejection-sampling', 'Rejection sampling', t`To sample a density ${math`f \le M`} on ${math`[${0}, ${1}]`}: propose ${math`Y`} uniform and accept with probability ${math`f(Y)/M`}, else repeat. Each proposal is accepted with probability ${math`${1}/M`}.`, t`For ${math`f(x) = ${6}x(${1} - x)`}, ${math`M = ${q(3, 2)}`}, so ${q(2, 3)} of the proposals are accepted.`, ['acceptance-rejection', 'accept-reject method']),
];
