/**
 * Glossary entries of the Preparation group C topics (calculus), kept in their own file so
 * each Preparation group adds one line to glossary.ts. Same rules as glossary.ts: computed
 * numbers only, one or two plain sentences.
 */
import type { GlossaryEntry } from './glossary';
import { q } from './math';
import { math, t, type Rich } from './rich';

const g = (topic: string, id: string, term: string, definition: Rich, example: Rich, aliases?: readonly string[]): GlossaryEntry =>
  (aliases === undefined ? { id, term, definition, example, topic } : { id, term, definition, example, topic, aliases });

const DV = 'calc.derivatives';
const SP = 'calc.stationary-points';
const RF = 'fn.rational-functions';
const CS = 'calc.curve-sketching';
const CV = 'calc.convexity';
const IP = 'calc.inflection-points';
const GT = 'fn.graph-transformations';
const FP = 'calc.first-principles';
const HY = 'calc.hyperbolic';
const DR = 'calc.differentiation-rules';
const ES = 'an.exp-series';
const DI = 'calc.definite-integrals';
const IBP = 'calc.integration-by-parts';
const SI = 'calc.standard-integrals';
const SU = 'calc.substitution';
const SY = 'calc.symmetry-integrals';
const ID = 'calc.implicit-differentiation';
const SO = 'calc.separable-odes';
const II = 'calc.improper-integrals';

export const GLOSSARY_PREP_C: readonly GlossaryEntry[] = [
  g(DV, 'derivative', 'Derivative', t`${math`f'(a) = \lim_{h \to ${0}} \frac{f(a + h) - f(a)}{h}`}: the gradient the chords from ${math`a`} settle on as the second point slides in. Written ${math`\frac{dy}{dx}`} when ${math`y = f(x)`}.`, t`For ${math`f(x) = x^{${2}}`}, the chord from ${math`x = ${3}`} has gradient ${math`${6} + h`}, so ${math`f'(${3}) = ${6}`}; the gradient of ${math`y = x^{${2}}`} at ${math`x = ${q(1, 2)}`} is ${1}.`, ['gradient function', 'dy/dx', "f'(x)", 'differentiation']),
  g(DV, 'differentiable', 'Differentiable', t`A function is differentiable at ${math`a`} when the limit defining ${math`f'(a)`} exists: the graph has a definite, non-vertical tangent there.`, t`${math`|x|`} is not differentiable at ${0}: chords to the right have gradient ${1}, to the left ${math`-${1}`}.`, ['differentiability']),
  g(SP, 'stationary-point', 'Stationary point', t`A point where ${math`f'(a) = ${0}`}, so the tangent is horizontal. It may be a local maximum, a local minimum, or a stationary point of inflection.`, t`${math`y = x^{${3}} - ${3}x`} has stationary points at ${math`x = \pm ${1}`}; ${math`y = x^{${3}}`} has one at ${math`x = ${0}`} that is neither.`, ['turning point', 'critical point', "f'(x) = 0"]),
  g(SP, 'local-maximum', 'Local maximum and minimum', t`${math`f`} has a local maximum at ${math`a`} if ${math`f(x) \le f(a)`} for all ${math`x`} close enough to ${math`a`}; a local minimum if ${math`f(x) \ge f(a)`} there. If ${math`f`} is differentiable there, ${math`f'(a) = ${0}`}.`, t`${math`y = x + \frac{${1}}{x}`} has a local maximum ${math`(${-1}, ${-2})`} below its local minimum ${math`(${1}, ${2})`}: local means compared with nearby points only.`, ['local minimum', 'maximum', 'minimum', 'second derivative test', 'turning point']),
  g(RF, 'rational-function', 'Rational function', t`A quotient ${math`\frac{p(x)}{q(x)}`} of two polynomials, defined wherever ${math`q(x) \ne ${0}`}.`, t`${math`\frac{x^{${2}}}{x - ${1}}`} is rational, defined for every ${math`x`} except ${1}.`, ['quotient of polynomials', 'rational curve']),
  g(RF, 'asymptote', 'Asymptote', t`A line the curve approaches ever more closely: ${math`x = a`} when ${math`|y| \to \infty`} as ${math`x \to a`}, or ${math`y = mx + k`} when ${math`y - (mx + k) \to ${0}`} as ${math`x \to \pm\infty`}.`, t`${math`y = \frac{x^{${2}}}{x - ${1}} = x + ${1} + \frac{${1}}{x - ${1}}`} has asymptotes ${math`x = ${1}`} and ${math`y = x + ${1}`}.`, ['vertical asymptote', 'horizontal asymptote', 'oblique asymptote']),
  g(CS, 'intermediate-value-theorem', 'Intermediate value theorem', t`If ${math`f`} is continuous on ${math`[a, b]`} and ${math`k`} is strictly between ${math`f(a)`} and ${math`f(b)`}, then ${math`f(c) = k`} for some ${math`c`} strictly between ${math`a`} and ${math`b`}.`, t`${math`x^{${3}} + x - ${1}`} is ${-1} at ${0} and ${1} at ${1}, so it has a root between ${0} and ${1}.`, ['IVT', 'intermediate value property']),
  g(CS, 'end-behaviour', 'End behaviour', t`What ${math`y`} does as ${math`x \to \infty`} and ${math`x \to -\infty`}. For a polynomial the highest power decides it.`, t`${math`y = -${2}x^{${3}} + x`} goes to ${math`+\infty`} on the left and ${math`-\infty`} on the right.`, ['behaviour at infinity', 'as x tends to infinity']),
  g(CV, 'concave-function', 'Concave function', t`${math`f`} is concave on an interval if ${math`-f`} is convex there: every chord lies on or below the curve. If ${math`f'' \le ${0}`} on the interval, ${math`f`} is concave.`, t`${math`\ln x`} is concave on ${math`x > ${0}`}: ${math`\frac{d^{${2}}}{dx^{${2}}} \ln x = -\frac{${1}}{x^{${2}}} < ${0}`}.`, ['concave', 'concave down', 'concavity']),
  g(CV, 'tangent-below', 'Tangent line inequality', t`For a convex ${math`f`}, every tangent lies below the curve: ${math`f(x) \ge f(a) + f'(a)(x - a)`}. For a concave ${math`f`} it lies above.`, t`The tangent to ${math`e^{x}`} at ${0} gives ${math`e^{x} \ge ${1} + x`}; the tangent to ${math`\ln x`} at ${1} gives ${math`\ln x \le x - ${1}`}.`, ['supporting line', 'tangent below the curve']),
  g(IP, 'point-of-inflection', 'Point of inflection', t`A point where ${math`f''`} changes sign, so the curve changes between concave and convex. There ${math`f''(a) = ${0}`}, but ${math`f''(a) = ${0}`} alone does not make an inflection. It is stationary if also ${math`f'(a) = ${0}`}.`, t`${math`y = x^{${3}}`} has a stationary inflection at ${math`(${0}, ${0})`}; ${math`y = (x - ${1})^{${4}}`} has ${math`f''(${1}) = ${0}`} but a minimum, not an inflection.`, ['inflection', 'inflexion', 'stationary point of inflection', 'non-stationary inflection']),
  g(GT, 'translation', 'Translation', t`Sliding a graph without turning or stretching it: by ${math`(u, v)`}, each point ${math`(x, y)`} moves to ${math`(x + u, y + v)`}. ${math`y = f(x - u) + v`} is ${math`y = f(x)`} translated by ${math`(u, v)`}.`, t`${math`y = (x - ${3})^{${2}} + ${1}`} is ${math`y = x^{${2}}`} translated by ${math`(${3}, ${1})`}: its vertex moves from ${math`(${0}, ${0})`} to ${math`(${3}, ${1})`}.`, ['shift', 'transformation of a graph', 'stretch', 'reflection']),
  g(FP, 'difference-quotient', 'Difference quotient', t`${math`\frac{f(x + h) - f(x)}{h}`} for ${math`h \ne ${0}`}: the gradient of the chord from ${math`x`} to ${math`x + h`}. Its limit as ${math`h \to ${0}`} is ${math`f'(x)`}.`, t`For ${math`f(x) = x^{${3}}`} the quotient is ${math`${3}x^{${2}} + ${3}xh + h^{${2}}`}, which tends to ${math`${3}x^{${2}}`}.`, ['chord gradient', 'first principles', 'Newton quotient']),
  g(HY, 'hyperbolic-functions', 'Hyperbolic functions', t`${math`\cosh x = \frac{e^{x} + e^{-x}}{${2}}`}, ${math`\sinh x = \frac{e^{x} - e^{-x}}{${2}}`}, and ${math`\tanh x = \frac{\sinh x}{\cosh x}`}. They satisfy ${math`\cosh^{${2}} x - \sinh^{${2}} x = ${1}`}, and each of cosh and sinh differentiates to the other.`, t`${math`\cosh(\ln ${2}) = \frac{${2} + \frac{${1}}{${2}}}{${2}} = ${q(5, 4)}`} and ${math`\sinh(\ln ${2}) = ${q(3, 4)}`}; indeed ${math`${q(25, 16)} - ${q(9, 16)} = ${1}`}.`, ['cosh', 'sinh', 'tanh', 'hyperbolic cosine', 'hyperbolic sine']),
  g(DR, 'product-rule-calculus', 'Product rule (differentiation)', t`${math`(uv)' = u'v + uv'`}: change one factor at a time and add the two effects.`, t`${math`\frac{d}{dx}(xe^{x}) = e^{x} + xe^{x} = (x + ${1})e^{x}`}.`, ['product rule for derivatives', "(uv)'"]),
  g(DR, 'chain-rule', 'Chain rule', t`${math`(f \circ g)'(x) = f'(g(x))g'(x)`}: differentiate the outside at the inside, then multiply by the derivative of the inside. In Leibniz notation, ${math`\frac{dy}{dx} = \frac{dy}{du}\frac{du}{dx}`}.`, t`${math`\frac{d}{dx}(${2}x^{${3}} + ${1})^{${2}} = ${2}(${2}x^{${3}} + ${1}) \cdot ${6}x^{${2}}`}.`, ['function of a function', 'composite rule', 'quotient rule']),
  g(ES, 'exponential-series', 'Exponential series', t`${math`e^{x} = \sum_{k \ge ${0}} \frac{x^{k}}{k!} = ${1} + x + \frac{x^{${2}}}{${2}!} + \cdots`}, convergent for every real ${math`x`} and equal to its own derivative.`, t`${math`\sum_{k \ge ${0}} \frac{${2}^{k}}{k!} = e^{${2}}`}, and the Poisson probabilities ${math`e^{-\lambda}\frac{\lambda^{k}}{k!}`} add to ${1}.`, ['e^x series', 'Maclaurin series of e^x', 'exp']),
  g(DI, 'definite-integral', 'Definite integral', t`${math`\int_{a}^{b} f(x)\,dx`}: the signed area between ${math`y = f(x)`} and the ${math`x`} axis from ${math`a`} to ${math`b`}, the limit of sums of thin strips. Parts below the axis count negatively.`, t`${math`\int_{${0}}^{${1}} x^{${2}}\,dx = ${q(1, 3)}`}, while ${math`\int_{${-1}}^{${1}} x\,dx = ${0}`}.`, ['integral', 'area under a curve', 'fundamental theorem of calculus']),
  g(DI, 'antiderivative', 'Antiderivative', t`A function ${math`F`} with ${math`F' = f`}. Any two differ by a constant, and ${math`\int_{a}^{b} f = F(b) - F(a)`} for continuous ${math`f`}.`, t`${math`\frac{x^{${3}}}{${3}}`} and ${math`\frac{x^{${3}}}{${3}} + ${5}`} are both antiderivatives of ${math`x^{${2}}`}.`, ['indefinite integral', 'primitive', 'integration']),
  g(IBP, 'integration-by-parts', 'Integration by parts', t`${math`\int_{a}^{b} uv'\,dx = \left[uv\right]_{a}^{b} - \int_{a}^{b} u'v\,dx`}: the product rule, integrated. Choose ${math`u`} to become simpler when differentiated.`, t`${math`\int xe^{x}\,dx = xe^{x} - \int e^{x}\,dx = (x - ${1})e^{x} + c`}.`, ['by parts', 'parts']),
  g(SI, 'log-integral', 'Logarithmic integral', t`${math`\int \frac{f'(x)}{f(x)}\,dx = \ln|f(x)| + c`} on an interval where ${math`f \ne ${0}`}: when the top is the derivative of the bottom, the integral is a logarithm.`, t`${math`\int \frac{${2}x}{x^{${2}} + ${1}}\,dx = \ln(x^{${2}} + ${1}) + c`}, and ${math`\int \frac{${1}}{x}\,dx = \ln|x| + c`}.`, ["f'/f", 'integration by inspection', 'ln|x|']),
  g(SU, 'substitution', 'Integration by substitution', t`${math`\int_{\alpha}^{\beta} f(g(u))g'(u)\,du = \int_{g(\alpha)}^{g(\beta)} f(x)\,dx`}: change the variable, ${math`dx`}, and the limits together. It is the chain rule read backwards.`, t`With ${math`u = x^{${2}}`}, ${math`\int_{${0}}^{${1}} ${2}xe^{x^{${2}}}\,dx = \int_{${0}}^{${1}} e^{u}\,du = e - ${1}`}.`, ['change of variable in an integral', 'u-substitution']),
  g(SY, 'king-property', 'Reflection trick for integrals', t`${math`\int_{${0}}^{a} f(x)\,dx = \int_{${0}}^{a} f(a - x)\,dx`}. Adding the two forms often simplifies: ${math`\int_{${0}}^{a} \frac{f(x)}{f(x) + f(a - x)}\,dx = \frac{a}{${2}}`}.`, t`${math`\int_{${0}}^{\frac{\pi}{${2}}} \frac{\cos x}{\cos x + \sin x}\,dx = \frac{\pi}{${4}}`}.`, ['king property', 'x to a - x', 'reflect and add', 'odd function', 'even function']),
  g(ID, 'implicit-differentiation', 'Implicit differentiation', t`Differentiating an equation in ${math`x`} and ${math`y`} term by term, with ${math`\frac{d}{dx}g(y) = g'(y)\frac{dy}{dx}`}, then solving for ${math`\frac{dy}{dx}`}.`, t`${math`x^{${2}} + y^{${2}} = ${25}`} gives ${math`${2}x + ${2}y\frac{dy}{dx} = ${0}`}, so the gradient at ${math`(${3}, ${4})`} is ${q(-3, 4)}.`, ['implicit', 'logarithmic differentiation', 'parametric differentiation']),
  g(SO, 'separable-equation', 'Separable differential equation', t`${math`\frac{dy}{dx} = f(x)g(y)`}: solved by ${math`\int \frac{dy}{g(y)} = \int f(x)\,dx + C`}, plus any constant solutions where ${math`g(y) = ${0}`}.`, t`${math`\frac{dy}{dx} = ${2}y`} gives ${math`\ln|y| = ${2}x + C`}, so ${math`y = Ae^{${2}x}`}.`, ['separation of variables', 'separable ODE', 'differential equation']),
  g(SO, 'ode-particular-solution', 'Particular solution', t`The one solution of a differential equation that also meets a given condition, found by fixing the constant in the general solution.`, t`${math`y = Ae^{${2}x}`} with ${math`y(${0}) = ${3}`} gives ${math`y = ${3}e^{${2}x}`}.`, ['initial condition', 'general solution', 'boundary condition']),
  g(II, 'improper-integral', 'Improper integral', t`${math`\int_{a}^{\infty} f(x)\,dx = \lim_{R \to \infty}\int_{a}^{R} f(x)\,dx`}; it converges when the limit is a real number and diverges otherwise.`, t`${math`\int_{${1}}^{\infty} \frac{dx}{x^{${2}}} = ${1}`}, while ${math`\int_{${1}}^{\infty} \frac{dx}{x}`} diverges.`, ['integral to infinity', 'convergent integral', 'divergent integral']),
];
