/**
 * Glossary entries of the Part V group C topics, kept in their own file so the four Part V
 * branches each add one line to glossary.ts. Same rules as glossary.ts: computed numbers
 * only, one or two plain sentences.
 */
import type { GlossaryEntry } from './glossary';
import { q } from './math';
import { math, t, type Rich } from './rich';

const g = (topic: string, id: string, term: string, definition: Rich, example: Rich, aliases?: readonly string[]): GlossaryEntry =>
  (aliases === undefined ? { id, term, definition, example, topic } : { id, term, definition, example, topic, aliases });

const PM = 'prob.point-mass-spaces';
const GE = 'prob.geometric-distribution';
const RV = 'rv.random-variables';
const EG = 'rv.expectation-general';
const IN = 'rv.independence';
const CV = 'rv.covariance';
const CE = 'rv.conditional-expectation';
const BN = 'rv.bivariate-normal';
const MC = 'ineq.markov-chebyshev';
const JE = 'ineq.jensen';

export const GLOSSARY_PARTV_C: readonly GlossaryEntry[] = [
  g(PM, 'point-mass', 'Point mass', t`The probability ${math`p_{\omega} = \mathbb{P}(\{\omega\})`} given to a single outcome. On a countable ${math`\Omega`}, the point masses determine every probability.`, t`A fair die has point mass ${q(1, 6)} at each face.`, ['probability mass', 'mass']),
  g(PM, 'countable-probability-space', 'Probability space on a countable set', t`A countable ${math`\Omega`} with point masses ${math`p_{\omega} \ge ${0}`} adding to ${1}, and ${math`\mathbb{P}(A) = \sum_{\omega \in A} p_{\omega}`} for every subset ${math`A`}.`, t`${math`p_{k} = ${q(1, 2)}^{k}`} on ${math`\{${1}, ${2}, \ldots\}`}: the even outcomes have probability ${q(1, 3)}.`, ['discrete probability space', 'countable sample space']),
  g(GE, 'geometric-distribution', 'Geometric distribution', t`The wait for the first success in independent trials with success probability ${math`p`}: ${math`\mathbb{P}(X = r) = (${1} - p)^{r - ${1}} p`} counting the trials, or ${math`(${1} - p)^{k} p`} counting the failures before it. The mean number of trials is ${math`${1}/p`}.`, t`Rolling a die until a six: ${math`\mathbb{P}(X = ${2}) = ${q(5, 36)}`}, and the mean is ${6} rolls.`, ['Geo(p)', 'geometric', 'waiting time']),
  g(GE, 'geometric-memoryless', 'Memoryless property of the geometric distribution', t`${math`\mathbb{P}(X > m + n \mid X > m) = \mathbb{P}(X > n)`}: having waited ${math`m`} trials without success, the remaining wait has the same distribution as a fresh one.`, t`After ${2} rolls without a six, three more without one still has probability ${q(125, 216)}.`, ['memoryless', 'lack of memory', 'no memory']),
  g(RV, 'random-variable', 'Random variable', t`A function ${math`X: \Omega \to \mathbb{R}`}: a number that depends on the outcome. Its probabilities come from those of ${math`\Omega`}.`, t`On two dice, the total ${math`S(a, b) = a + b`} is a random variable, with ${math`\mathbb{P}(S = ${4}) = ${q(1, 12)}`}.`, ['r.v.', 'discrete random variable', 'variable']),
  g(RV, 'rv-distribution', 'Distribution of a random variable', t`The probabilities ${math`\mathbb{P}(X = x) = \mathbb{P}(\{\omega : X(\omega) = x\})`} for every value ${math`x`}: what is left of the probability space when only ${math`X`} is observed.`, t`The number of heads in two fair tosses has distribution ${q(1, 4)}, ${q(1, 2)}, ${q(1, 4)} on ${math`${0}, ${1}, ${2}`}.`, ['probability mass function', 'pmf', 'law']),
  g(EG, 'expectation-general', 'Expectation on a countable space', t`${math`\mathbb{E}(X) = \sum_{x} x\,\mathbb{P}(X = x)`}, defined when ${math`\sum_{x} |x|\,\mathbb{P}(X = x)`} converges. A nonnegative ${math`X`} may have ${math`\mathbb{E}(X) = +\infty`}.`, t`A fair die has ${math`\mathbb{E}(X) = \frac{${1} + ${2} + \cdots + ${6}}{${6}} = ${q(7, 2)}`}; ${math`\mathbb{P}(X = ${2}^{k}) = ${2}^{-k}`} has ${math`\mathbb{E}(X) = +\infty`}.`, ['expectation', 'expected value', 'mean', 'E(X)']),
  g(EG, 'expectation-of-function', 'Expectation of a function of a random variable', t`${math`\mathbb{E}(g(X)) = \sum_{x} g(x)\,\mathbb{P}(X = x)`}, when the sum converges absolutely: no need to find the distribution of ${math`g(X)`}.`, t`For a fair die, ${math`\mathbb{E}(X^{${2}}) = \frac{${1} + ${4} + \cdots + ${36}}{${6}} = ${q(91, 6)}`}, while ${math`\mathbb{E}(X)^{${2}} = ${q(49, 4)}`}.`, ['E(g(X))', 'law of the unconscious statistician', 'LOTUS']),
  g(IN, 'independent-random-variables', 'Independent random variables', t`${math`X`} and ${math`Y`} are independent if ${math`\mathbb{P}(X = x, Y = y) = \mathbb{P}(X = x)\mathbb{P}(Y = y)`} for all values ${math`x, y`}. Then ${math`\mathbb{E}(XY) = \mathbb{E}(X)\mathbb{E}(Y)`}, but that equation alone does not imply independence.`, t`The scores on two separately thrown dice are independent: each of the ${36} pairs has probability ${math`${q(1, 6)} \cdot ${q(1, 6)} = ${q(1, 36)}`}.`, ['independence of random variables', 'independent variables']),
  g(IN, 'iid', 'Independent and identically distributed', t`A sequence of independent random variables that all have the same distribution: repeated runs of the same experiment.`, t`The scores of ${10} throws of a fair die are i.i.d., each uniform on ${math`${1}, \ldots, ${6}`}.`, ['i.i.d.', 'iid', 'independent copies']),
  g(CV, 'covariance', 'Covariance', t`${math`\operatorname{cov}(X, Y) = \mathbb{E}\left((X - \mathbb{E}X)(Y - \mathbb{E}Y)\right) = \mathbb{E}(XY) - \mathbb{E}(X)\mathbb{E}(Y)`}: positive when the variables tend to be large together, negative when one tends to be large as the other is small.`, t`For the score ${math`X`} of a fair die, ${math`\operatorname{cov}(X, ${7} - X) = -\operatorname{var}(X) = -${q(35, 12)}`}.`, ['cov', 'cov(X, Y)']),
  g(CV, 'correlation-coefficient', 'Correlation coefficient', t`${math`\rho(X, Y) = \operatorname{cov}(X, Y)/\sqrt{\operatorname{var}(X)\operatorname{var}(Y)}`}: covariance without units, always between ${math`-${1}`} and ${1}, and ${math`\pm ${1}`} only for a linear relation.`, t`${math`\rho(X, ${2}X + ${3}) = ${1}`} and ${math`\rho(X, -X) = -${1}`}.`, ['correlation', 'rho']),
  g(CE, 'conditional-distribution', 'Conditional distribution', t`The distribution of ${math`X`} once ${math`Y = y`} is known: ${math`\mathbb{P}(X = x \mid Y = y) = \mathbb{P}(X = x, Y = y)/\mathbb{P}(Y = y)`}.`, t`Two fair dice with total ${4}: the first die is ${1}, ${2}, or ${3}, each with conditional probability ${q(1, 3)}.`, ['distribution given Y', 'conditional pmf']),
  g(CE, 'conditional-expectation', 'Conditional expectation', t`${math`\mathbb{E}(X \mid Y = y) = \sum_{x} x\,\mathbb{P}(X = x \mid Y = y)`}, the mean of the conditional distribution. As ${math`y`} varies it defines the random variable ${math`\mathbb{E}(X \mid Y)`}, a function of ${math`Y`}.`, t`Two fair dice: the first die's mean given the total ${math`T`} is ${math`T/${2}`}, so given a total of ${4} it is ${2}.`, ['E(X | Y)', 'conditional mean']),
  g(CE, 'tower-law', 'Tower law', t`${math`\mathbb{E}(\mathbb{E}(X \mid Y)) = \mathbb{E}(X)`}: average the conditional means, weighted by the probabilities of the conditions.`, t`Toss a coin ${math`N`} times, ${math`N`} uniform on ${math`\{${1}, ${2}, ${3}\}`}: the mean number of heads is ${math`\mathbb{E}(N/${2}) = ${1}`}.`, ['law of total expectation', 'iterated expectation', 'E(E(X | Y))']),
  g(BN, 'bivariate-normal', 'Bivariate normal distribution', t`The joint distribution of ${math`X = \mu_{X} + \sigma_{X}Z_{${1}}`} and ${math`Y = \mu_{Y} + \sigma_{Y}(\rho Z_{${1}} + \sqrt{${1} - \rho^{${2}}}Z_{${2}})`} for independent standard normals ${math`Z_{${1}}, Z_{${2}}`}: normal margins, correlation ${math`\rho`}.`, t`With ${math`\rho = ${q(1, 2)}`} and standard margins, both are positive with probability ${q(1, 3)}.`, ['jointly normal', 'bivariate Gaussian', 'two-dimensional normal']),
  g(BN, 'normal-independence', 'Uncorrelated jointly normal variables are independent', t`If ${math`(X, Y)`} is bivariate normal and ${math`\operatorname{cov}(X, Y) = ${0}`}, then ${math`X`} and ${math`Y`} are independent. It fails for normal variables that are not jointly normal.`, t`For independent standard normals ${math`X, Y`}, the sum and difference have covariance ${math`${1} - ${1} = ${0}`}, so ${math`X + Y`} and ${math`X - Y`} are independent.`, ['independent iff uncorrelated', 'zero covariance normals']),
  g(MC, 'markov-inequality', "Markov's inequality", t`For ${math`X \ge ${0}`} and ${math`a > ${0}`}: ${math`\mathbb{P}(X \ge a) \le \mathbb{E}(X)/a`}. A nonnegative variable cannot often be much larger than its mean.`, t`If the mean wait is ${3} minutes, a wait of at least ${12} minutes has probability at most ${q(1, 4)}.`, ['Markov', 'Markov bound']),
  g(MC, 'chebyshev-inequality', "Chebyshev's inequality", t`${math`\mathbb{P}(|X - \mu| \ge c) \le \sigma^{${2}}/c^{${2}}`}: a variable is rarely many standard deviations from its mean, whatever its distribution.`, t`At least ${math`${1} - ${q(1, 4)} = ${q(3, 4)}`} of any distribution lies within ${2} standard deviations of its mean.`, ['Chebyshev', 'Chebyshev bound', 'Tchebychev']),
  g(JE, 'convex-function', 'Convex function', t`A function lying below its chords: ${math`f(tx + (${1} - t)y) \le tf(x) + (${1} - t)f(y)`} for ${math`t \in [${0}, ${1}]`}. A function with ${math`f'' \ge ${0}`} is convex.`, t`${math`x^{${2}}`}, ${math`e^{x}`}, and ${math`${1}/x`} on ${math`(${0}, \infty)`} are convex; ${math`\log x`} is concave.`, ['convex', 'convexity', 'concave']),
  g(JE, 'jensen-inequality', "Jensen's inequality", t`For convex ${math`f`}: ${math`\mathbb{E}(f(X)) \ge f(\mathbb{E}(X))`}. For concave ${math`f`} the inequality reverses.`, t`${math`X`} equally likely ${1} or ${3}: ${math`\mathbb{E}(X^{${2}}) = ${5}`}, while ${math`\mathbb{E}(X)^{${2}} = ${4}`}.`, ['Jensen']),
  g(JE, 'am-gm', 'AM-GM inequality', t`For positive numbers, the geometric mean is at most the arithmetic mean: ${math`(x_{${1}} \cdots x_{n})^{${1}/n} \le (x_{${1}} + \cdots + x_{n})/n`}, with equality only when all are equal.`, t`${math`\sqrt{${4} \cdot ${9}} = ${6} \le \frac{${4} + ${9}}{${2}} = ${q(13, 2)}`}.`, ['AM/GM', 'arithmetic-geometric mean inequality', 'AM-GM']),
];
