/**
 * Knowledge graph for the probability and statistics MVP slice: pre-A-level roots up to
 * IA Probability "Basic concepts" and "Axiomatic approach".
 *
 * Every `source.section` is the heading as printed in the cited document; `note` says
 * which line of the section the topic comes from, or why a topic the section does not
 * name is here. Encompass weights: about 0.6 to 0.7 when the topic exercises the
 * prerequisite in every problem, about 0.3 to 0.5 when it leans on it in some steps.
 */
import type { Topic } from '@learnhub/mastery';

/** Source documents cited by `source.doc`. */
export const SOURCE_DOCS = {
  'dfe-gcse-maths-2013': {
    title: 'Mathematics GCSE subject content and assessment objectives (DfE, November 2013, DFE-00233-2013)',
    url: 'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/254441/GCSE_mathematics_subject_content_and_assessment_objectives.pdf',
  },
  'step-spec-2026': {
    title: 'STEP Mathematics Specifications for Examinations from June 2026 onwards, version 1.3 (OCR)',
    url: 'https://www.ocr.org.uk/Images/696329-step-specification-2026.pdf',
  },
  'tripos-schedules-2026-27': {
    title: 'Schedules of Lecture Courses and Form of Examinations for the Mathematical Tripos 2026-27 (revised 19 August 2026)',
    url: 'https://www.maths.cam.ac.uk/undergrad/files/schedules.pdf',
  },
} as const;

type Doc = keyof typeof SOURCE_DOCS;
const GCSE: Doc = 'dfe-gcse-maths-2013';
const STEP: Doc = 'step-spec-2026';
const TRIPOS: Doc = 'tripos-schedules-2026-27';

// Section headings, exactly as printed (the STEP spec nests a heading under a paper and section).
const GCSE_NUMBER = 'Number: Structure and calculation';
const GCSE_ALGEBRA = 'Algebra: Notation, vocabulary and manipulation';
const GCSE_SEQUENCES = 'Algebra: Sequences';
const GCSE_PROB = 'Probability';
const M1_PURE = 'Section A: Pure Mathematics';
const M1_PROB = 'Section B: Mechanics and Probability/Statistics';
const STEP_SS = `${M1_PURE}, Sequences and series`;
const IA_BASIC = 'Basic concepts';
const IA_AXIOMATIC = 'Axiomatic approach';
const IA_LIMITS = 'Limits and convergence';

const STEP_SUPPORT_6 = 'External check: STEP Support Programme Foundation Assignment 6 (arrangements and probability).';

export const topics: Topic[] = [
  // ---------------------------------------------------------------- number and algebra
  {
    id: 'pre.fractions',
    title: 'Fractions and ratios',
    summary: 'Add, multiply, and simplify fractions, and read a ratio as parts of a whole.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 2 and 8 (fraction arithmetic); ratio from "Ratio, proportion and rates of change", items 3 to 8.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'pre.algebraic-manipulation',
    title: 'Expanding, factorising, and simplifying',
    summary: 'Expand brackets, factorise, collect like terms, and simplify algebraic fractions.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_ALGEBRA, note: 'Item 4.', verified: true },
    estMinutes: 20,
  },
  {
    id: 'pre.indices',
    title: 'Laws of indices',
    summary: 'Multiply, divide, and raise powers, including zero, negative, and fractional indices.',
    level: 'pre-a-level',
    area: 'number-and-algebra',
    prereqs: [],
    encompasses: {},
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Items 6 and 7; laws of indices also in Algebra item 4.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.exp-and-ln',
    title: 'The exponential function and natural logarithm',
    summary: 'Use e^x and ln x as inverse functions and apply the laws of logarithms.',
    level: 'a-level',
    area: 'number-and-algebra',
    prereqs: ['pre.indices'],
    encompasses: { 'pre.indices': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Exponentials and logarithms`, verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- sequences and series
  {
    id: 'pre.sequences',
    title: 'Sequences and nth term rules',
    summary: 'Generate a sequence from a term-to-term or position-to-term rule and find its nth term.',
    level: 'pre-a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.algebraic-manipulation'],
    encompasses: { 'pre.algebraic-manipulation': 0.2 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_SEQUENCES, note: 'Items 23 to 25.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.sigma-notation',
    title: 'Sigma notation',
    summary: 'Read and write sums with sigma notation, and shift or split the index.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['pre.sequences'],
    encompasses: { 'pre.sequences': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.arithmetic-series',
    title: 'Arithmetic series',
    summary: 'Find the nth term and the sum of the first n terms of an arithmetic sequence.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.sequences': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-series',
    title: 'Finite geometric series',
    summary: 'Sum a finite geometric series with the formula a(1 - r^n)/(1 - r).',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.sigma-notation', 'pre.indices'],
    encompasses: { 'alg.sigma-notation': 0.5, 'pre.indices': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.geometric-sum-to-infinity',
    title: 'Sum to infinity of a geometric series',
    summary: 'Sum a geometric series to infinity when |r| < 1, and see why it fails otherwise.',
    level: 'a-level',
    area: 'sequences-and-series',
    prereqs: ['alg.geometric-series'],
    encompasses: { 'alg.geometric-series': 0.6 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
    estMinutes: 15,
  },
  {
    id: 'alg.proof-by-induction',
    title: 'Proof by induction',
    summary: 'Prove a statement for every natural number from a base case and an inductive step.',
    level: 'step',
    area: 'sequences-and-series',
    prereqs: ['alg.arithmetic-series'],
    encompasses: { 'alg.arithmetic-series': 0.3, 'alg.sigma-notation': 0.4, 'pre.algebraic-manipulation': 0.4 },
    source: {
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PURE}, Proof`,
      note: 'Level step: DfE A level Mathematics leaves induction to Further Mathematics. Also IA Numbers and Sets, "The integers".',
      verified: true,
    },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- calculus
  {
    id: 'calc.derivatives',
    title: 'Differentiating powers, e^x, and ln x',
    summary: 'Differentiate x^n, e^(kx), and ln x, with sums and constant multiples.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['alg.exp-and-ln', 'pre.algebraic-manipulation'],
    encompasses: { 'alg.exp-and-ln': 0.5, 'pre.indices': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Differentiation`, verified: true },
    estMinutes: 25,
  },
  {
    id: 'calc.definite-integrals',
    title: 'Definite integrals and the fundamental theorem',
    summary: 'Evaluate a definite integral from an antiderivative and read it as an area.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.derivatives'],
    encompasses: { 'calc.derivatives': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Integration`, verified: true },
    estMinutes: 20,
  },
  {
    id: 'calc.integration-by-parts',
    title: 'Integration by parts',
    summary: 'Integrate a product by reversing the product rule, for example the integral of ln x.',
    level: 'a-level',
    area: 'calculus',
    prereqs: ['calc.definite-integrals'],
    encompasses: { 'calc.definite-integrals': 0.6, 'calc.derivatives': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PURE}, Integration`, verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- analysis
  {
    id: 'an.sequence-limits',
    title: 'Limits of sequences',
    summary: 'Say what x_n tends to a means and find simple limits such as 1/n and r^n.',
    level: 'step',
    area: 'analysis',
    prereqs: ['pre.sequences'],
    encompasses: { 'pre.sequences': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'The limit-of-a-sequence line is a STEP addition (bold italics).', verified: true },
    estMinutes: 15,
  },
  {
    id: 'an.epsilon-limit',
    title: 'The epsilon definition of convergence',
    summary: 'Prove that a sequence converges straight from the definition, using |x_n - a| < epsilon.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.sequence-limits'],
    encompasses: { 'an.sequence-limits': 0.5 },
    source: { doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Covers the modulus inequalities the definition needs, rather than a separate topic.', verified: true },
    estMinutes: 25,
  },
  {
    id: 'an.limit-algebra',
    title: 'Limits of sums, products, and quotients',
    summary: 'Combine limits of sequences under sums, products, and quotients, with proofs.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.epsilon-limit'],
    encompasses: { 'an.epsilon-limit': 0.6 },
    source: { doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Schedule: "Sums, products and quotients."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'an.monotone-convergence',
    title: 'Bounded monotone sequences converge',
    summary: 'An increasing sequence that is bounded above converges to its least upper bound.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.epsilon-limit'],
    encompasses: { 'an.epsilon-limit': 0.5 },
    source: { doc: TRIPOS, course: 'IA Numbers and Sets', section: 'The real numbers', note: 'Schedule: "convergence of bounded monotonic sequences".', verified: true },
    estMinutes: 20,
  },
  {
    id: 'an.series-convergence',
    title: 'Convergence of an infinite series',
    summary: 'Define the sum of a series as the limit of its partial sums.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.limit-algebra', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'an.limit-algebra': 0.4, 'alg.geometric-sum-to-infinity': 0.5, 'alg.sigma-notation': 0.3 },
    source: { doc: TRIPOS, course: 'IA Analysis I', section: IA_LIMITS, note: 'Schedule: "Sequences and series in R and C."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'an.nonnegative-series',
    title: 'Series of nonnegative terms',
    summary: 'A nonnegative series converges if its partial sums are bounded; compare and reorder freely.',
    level: 'tripos-ia',
    area: 'analysis',
    prereqs: ['an.series-convergence', 'an.monotone-convergence'],
    encompasses: { 'an.series-convergence': 0.5, 'an.monotone-convergence': 0.5 },
    source: {
      doc: TRIPOS,
      course: 'IA Analysis I',
      section: IA_LIMITS,
      note: 'Schedule lists "Comparison and ratio tests". That a nonnegative series has the same sum in any order is not named; countable additivity needs it.',
      verified: true,
    },
    estMinutes: 20,
  },
  {
    id: 'an.exp-series',
    title: 'The exponential series',
    summary: 'Use e^x = sum of x^k/k! over k from 0, for example to sum Poisson probabilities.',
    level: 'step',
    area: 'analysis',
    prereqs: ['alg.exp-and-ln', 'comb.factorial', 'alg.geometric-sum-to-infinity'],
    encompasses: { 'alg.exp-and-ln': 0.3, 'comb.factorial': 0.3, 'alg.geometric-sum-to-infinity': 0.2 },
    source: { doc: STEP, course: 'STEP Mathematics 2', section: 'Section A: Pure Mathematics, Further algebra and functions', note: 'Spec: "Recognise and use the series expansion of e^x."', verified: true },
    estMinutes: 15,
  },
  {
    id: 'an.exp-limit',
    title: 'The limit of (1 + x/n)^n',
    summary: 'Show (1 + x/n)^n tends to e^x by taking logs and using the derivative of ln at 1.',
    level: 'step',
    area: 'analysis',
    prereqs: ['calc.derivatives', 'an.sequence-limits'],
    encompasses: { 'calc.derivatives': 0.4, 'alg.exp-and-ln': 0.4, 'an.sequence-limits': 0.4 },
    source: {
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PURE}, Exponentials and logarithms`,
      note: 'The spec names "the use of e in continuous compound interest", which is this limit; the limit itself is not stated.',
      verified: true,
    },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- sets
  {
    id: 'pre.set-notation',
    title: 'Sets and Venn diagrams',
    summary: 'Use set notation for union, intersection, and complement, and draw them as Venn diagrams.',
    level: 'pre-a-level',
    area: 'sets',
    prereqs: [],
    encompasses: {},
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 6 (Venn diagrams); set notation also in Algebra item 22.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'sets.countable-unions',
    title: 'Countable sets and countable unions',
    summary: 'Recognise countable sets and work with unions and intersections of a sequence of sets.',
    level: 'tripos-ia',
    area: 'sets',
    prereqs: ['pre.set-notation', 'pre.sequences'],
    encompasses: { 'pre.set-notation': 0.5, 'pre.sequences': 0.2 },
    source: { doc: TRIPOS, course: 'IA Numbers and Sets', section: 'Countability and uncountability', note: 'Unions and intersections from "Sets, relations and functions".', verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- counting
  {
    id: 'pre.product-rule',
    title: 'The product rule for counting',
    summary: 'Count outcomes of a sequence of choices by multiplying the number of options at each step.',
    level: 'pre-a-level',
    area: 'counting',
    prereqs: [],
    encompasses: {},
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_NUMBER, note: 'Item 5: "systematic listing strategies including use of the product rule for counting".', verified: true },
    estMinutes: 15,
  },
  {
    id: 'comb.factorial',
    title: 'Factorials and arranging n objects',
    summary: 'Count the orderings of n distinct objects as n!, with 0! = 1.',
    level: 'a-level',
    area: 'counting',
    prereqs: ['pre.product-rule'],
    encompasses: { 'pre.product-rule': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec: "the notations n! and nCr ... and their algebraic definitions".', verified: true },
    estMinutes: 15,
  },
  {
    id: 'comb.permutations',
    title: 'Permutations of r objects from n',
    summary: 'Count ordered selections of r objects from n as n!/(n - r)!.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.factorial'],
    encompasses: { 'comb.factorial': 0.6, 'pre.product-rule': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec, in bold italics: "Use n! and nCr in the context of permutations and combinations."', verified: true },
    estMinutes: 15,
  },
  {
    id: 'comb.combinations',
    title: 'Combinations and the binomial coefficient',
    summary: 'Count unordered selections of r objects from n as n!/(r!(n - r)!).',
    level: 'a-level',
    area: 'counting',
    prereqs: ['comb.factorial', 'pre.fractions'],
    encompasses: { 'comb.factorial': 0.6, 'pre.product-rule': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'A level states the nCr notation and definition; its use in counting is the bold STEP line.', verified: true },
    estMinutes: 20,
  },
  {
    id: 'comb.repeated-arrangements',
    title: 'Arrangements with repeated objects',
    summary: 'Count arrangements of a word with repeated letters as n! divided by the repeats.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.combinations'],
    encompasses: { 'comb.combinations': 0.6, 'comb.factorial': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: STEP_SUPPORT_6, verified: true },
    estMinutes: 20,
  },
  {
    id: 'comb.binomial-identities',
    title: 'Symmetry and Pascal\'s rule',
    summary: 'Prove nCr = nC(n - r) and Pascal\'s rule both by algebra and by counting.',
    level: 'step',
    area: 'counting',
    prereqs: ['comb.combinations', 'pre.algebraic-manipulation'],
    encompasses: { 'comb.combinations': 0.7, 'pre.fractions': 0.3, 'pre.algebraic-manipulation': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, verified: true },
    estMinutes: 20,
  },
  {
    id: 'comb.binomial-theorem',
    title: 'The binomial theorem',
    summary: 'Expand (a + b)^n for a positive integer n and read off sums such as the total 2^n.',
    level: 'a-level',
    area: 'counting',
    prereqs: ['comb.combinations', 'pre.indices', 'pre.algebraic-manipulation'],
    encompasses: { 'comb.combinations': 0.6, 'pre.indices': 0.3, 'pre.algebraic-manipulation': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: STEP_SS, note: 'Spec: "the binomial expansion of (a + bx)^n for positive integer n".', verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- elementary probability
  {
    id: 'pre.probability-scale',
    title: 'Probability of equally likely outcomes',
    summary: 'Give a probability on the 0 to 1 scale as favourable over total, and use P(not A) = 1 - P(A).',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.fractions'],
    encompasses: { 'pre.fractions': 0.3 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Items 2 to 4.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'pre.sample-spaces',
    title: 'Sample spaces for combined experiments',
    summary: 'List or tabulate every outcome of two or more experiments and count the favourable ones.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.probability-scale', 'pre.product-rule'],
    encompasses: { 'pre.probability-scale': 0.5, 'pre.product-rule': 0.4 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 7.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'pre.mutually-exclusive',
    title: 'Mutually exclusive events',
    summary: 'Add probabilities of events that cannot happen together; an exhaustive set sums to one.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.probability-scale', 'pre.set-notation'],
    encompasses: { 'pre.probability-scale': 0.4, 'pre.set-notation': 0.3 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 4.', verified: true },
    estMinutes: 10,
  },
  {
    id: 'pre.tree-diagrams',
    title: 'Tree diagrams',
    summary: 'Multiply along branches and add across them, with and without replacement.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.sample-spaces'],
    encompasses: { 'pre.sample-spaces': 0.5, 'pre.fractions': 0.3 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 8.', verified: true },
    estMinutes: 20,
  },
  {
    id: 'pre.two-way-tables',
    title: 'Conditional probability from tables and Venn diagrams',
    summary: 'Find a probability given that an event happened by restricting a table or diagram to it.',
    level: 'pre-a-level',
    area: 'elementary-probability',
    prereqs: ['pre.tree-diagrams', 'pre.set-notation'],
    encompasses: { 'pre.tree-diagrams': 0.4, 'pre.set-notation': 0.3 },
    source: { doc: GCSE, course: 'GCSE Mathematics', section: GCSE_PROB, note: 'Item 9.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.addition-rule',
    title: 'The addition rule for two events',
    summary: 'Use P(A or B) = P(A) + P(B) - P(A and B) for any two events.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.mutually-exclusive'],
    encompasses: { 'pre.mutually-exclusive': 0.5, 'pre.set-notation': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.inclusion-exclusion-three',
    title: 'Inclusion-exclusion for three events',
    summary: 'Find P(A or B or C) by adding singles, subtracting pairs, and adding back the triple.',
    level: 'step',
    area: 'elementary-probability',
    prereqs: ['prob.addition-rule'],
    encompasses: { 'prob.addition-rule': 0.7, 'pre.set-notation': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, note: 'The spec states the two-event formula; the three-event case extends it.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.independent-events',
    title: 'Independent events',
    summary: 'Test and use independence of two events through P(A and B) = P(A)P(B).',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.tree-diagrams'],
    encompasses: { 'pre.tree-diagrams': 0.5 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.conditional-formula',
    title: 'The conditional probability formula',
    summary: 'Compute P(A | B) = P(A and B)/P(B) and rearrange it as a multiplication rule.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.two-way-tables'],
    encompasses: { 'pre.two-way-tables': 0.5, 'pre.tree-diagrams': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Probability`, verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.counting-probability',
    title: 'Probability by counting',
    summary: 'Find probabilities of equally likely outcomes by counting with permutations and combinations.',
    level: 'step',
    area: 'elementary-probability',
    prereqs: ['comb.permutations', 'comb.combinations', 'pre.sample-spaces'],
    encompasses: { 'comb.combinations': 0.6, 'comb.permutations': 0.5, 'pre.sample-spaces': 0.4 },
    source: {
      doc: STEP,
      course: 'STEP Mathematics 1',
      section: `${M1_PROB}, Probability`,
      note: `Spec, in bold italics: "Use combinatorial arguments, including the use of n! and nCr in the context of calculating probabilities." ${STEP_SUPPORT_6}`,
      verified: true,
    },
    estMinutes: 20,
  },
  {
    id: 'prob.discrete-distributions',
    title: 'Discrete probability distributions',
    summary: 'Describe a discrete random variable by a table of values and probabilities that sum to one.',
    level: 'a-level',
    area: 'elementary-probability',
    prereqs: ['pre.sample-spaces'],
    encompasses: { 'pre.sample-spaces': 0.4, 'pre.probability-scale': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Statistical distributions`, verified: true },
    estMinutes: 15,
  },

  // ---------------------------------------------------------------- distributions
  {
    id: 'prob.binomial-distribution',
    title: 'The binomial distribution',
    summary: 'Model the number of successes in n independent trials and compute B(n, p) probabilities.',
    level: 'a-level',
    area: 'distributions',
    prereqs: ['prob.discrete-distributions', 'comb.combinations', 'prob.independent-events'],
    encompasses: { 'comb.combinations': 0.5, 'prob.independent-events': 0.5, 'prob.discrete-distributions': 0.4, 'pre.tree-diagrams': 0.3 },
    source: { doc: STEP, course: 'STEP Mathematics 1', section: `${M1_PROB}, Statistical distributions`, verified: true },
    estMinutes: 20,
  },
  {
    id: 'prob.poisson-distribution',
    title: 'The Poisson distribution',
    summary: 'Compute Poisson probabilities e^(-lambda) lambda^k/k! and check they sum to one.',
    level: 'step',
    area: 'distributions',
    prereqs: ['prob.discrete-distributions', 'an.exp-series'],
    encompasses: { 'an.exp-series': 0.5, 'prob.discrete-distributions': 0.4 },
    source: { doc: STEP, course: 'STEP Mathematics 2', section: 'Section C: Probability/Statistics, Probability distributions', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.geometric-distribution',
    title: 'The geometric distribution',
    summary: 'Model the wait for the first success in independent trials, in both common conventions.',
    level: 'tripos-ia',
    area: 'distributions',
    prereqs: ['prob.point-mass-spaces', 'prob.independence'],
    encompasses: { 'prob.point-mass-spaces': 0.5, 'alg.geometric-sum-to-infinity': 0.5, 'prob.independence': 0.4 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Binomial, Poisson and geometric distributions."', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.poisson-binomial-limit',
    title: 'The Poisson limit of the binomial',
    summary: 'Prove that B(n, lambda/n) probabilities tend to Poisson(lambda) probabilities as n grows.',
    level: 'tripos-ia',
    area: 'distributions',
    prereqs: ['prob.binomial-distribution', 'prob.poisson-distribution', 'an.exp-limit', 'prob.point-mass-spaces'],
    encompasses: { 'an.exp-limit': 0.6, 'prob.binomial-distribution': 0.5, 'prob.poisson-distribution': 0.5, 'an.limit-algebra': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Relation between Poisson and binomial distributions."', verified: true },
    estMinutes: 25,
  },

  // ---------------------------------------------------------------- IA Probability, Basic concepts
  {
    id: 'prob.classical-probability',
    title: 'Classical probability on a finite sample space',
    summary: 'Model an experiment as a finite set of equally likely outcomes, with events as subsets.',
    level: 'tripos-ia',
    area: 'ia-basic-concepts',
    prereqs: ['prob.counting-probability', 'pre.set-notation'],
    encompasses: { 'prob.counting-probability': 0.5, 'pre.sample-spaces': 0.3, 'pre.set-notation': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_BASIC, note: 'Schedule: "Classical probability, equally likely outcomes."', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.sampling-models',
    title: 'Ordered and unordered samples, with and without replacement',
    summary: 'Count samples of size k from n in all four cases, including k from n with repetition.',
    level: 'tripos-ia',
    area: 'ia-basic-concepts',
    prereqs: ['prob.classical-probability', 'comb.repeated-arrangements'],
    encompasses: { 'comb.repeated-arrangements': 0.5, 'comb.permutations': 0.5, 'comb.combinations': 0.5, 'prob.classical-probability': 0.4 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_BASIC, note: 'Schedule: "Combinatorial analysis, permutations and combinations."', verified: true },
    estMinutes: 25,
  },
  {
    id: 'prob.stirling-log',
    title: 'Asymptotics of log n!',
    summary: 'Prove log n! is asymptotic to n log n by bounding the sum of log k with integrals.',
    level: 'tripos-ia',
    area: 'ia-basic-concepts',
    prereqs: ['calc.integration-by-parts', 'comb.factorial', 'an.limit-algebra'],
    encompasses: { 'calc.integration-by-parts': 0.5, 'calc.definite-integrals': 0.4, 'comb.factorial': 0.4, 'an.limit-algebra': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_BASIC, note: 'Schedule: "Stirling\'s formula (asymptotics for log n! proved)." Defines a_n ~ b_n here.', verified: true },
    estMinutes: 25,
  },
  {
    id: 'prob.stirling-formula',
    title: 'Stirling\'s formula',
    summary: 'Use n! ~ sqrt(2 pi n)(n/e)^n, for example to estimate the central binomial coefficient.',
    level: 'tripos-ia',
    area: 'ia-basic-concepts',
    prereqs: ['prob.stirling-log', 'comb.combinations'],
    encompasses: { 'prob.stirling-log': 0.6, 'comb.combinations': 0.3, 'comb.factorial': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_BASIC, note: 'The schedule proves only the log asymptotics; the full formula is stated and used.', verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- IA Probability, Axiomatic approach
  {
    id: 'prob.axioms',
    title: 'The axioms of probability, countable case',
    summary: 'State the axioms for a countable sample space, including countable additivity.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.classical-probability', 'sets.countable-unions', 'an.nonnegative-series'],
    encompasses: { 'prob.classical-probability': 0.4, 'sets.countable-unions': 0.4, 'an.nonnegative-series': 0.4 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Axioms (countable case)."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'prob.point-mass-spaces',
    title: 'Probability spaces on a countable set',
    summary: 'Build a probability space from point masses p(w) that sum to one, with P(A) the sum over A.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axioms', 'prob.discrete-distributions'],
    encompasses: { 'prob.axioms': 0.6, 'an.nonnegative-series': 0.4, 'prob.discrete-distributions': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Probability spaces."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'prob.axiom-consequences',
    title: 'First consequences of the axioms',
    summary: 'Prove the complement rule, monotonicity, and the two-event addition rule from the axioms.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axioms', 'prob.addition-rule'],
    encompasses: { 'prob.axioms': 0.6, 'prob.addition-rule': 0.5 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Not named in the schedule; the standard first results from "Axioms".', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.inclusion-exclusion',
    title: 'The inclusion-exclusion formula',
    summary: 'Prove and apply the general inclusion-exclusion formula for n events.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences', 'prob.inclusion-exclusion-three', 'alg.proof-by-induction', 'comb.binomial-theorem'],
    encompasses: { 'prob.inclusion-exclusion-three': 0.7, 'prob.axiom-consequences': 0.5, 'alg.proof-by-induction': 0.4, 'comb.binomial-theorem': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Inclusion-exclusion formula." The binomial theorem gives the counting check that each outcome is counted once.', verified: true },
    estMinutes: 25,
  },
  {
    id: 'prob.continuity',
    title: 'Continuity of probability measures',
    summary: 'For increasing events, P(A_n) tends to the probability of their union, and dually for decreasing.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences'],
    encompasses: { 'prob.axiom-consequences': 0.5, 'prob.axioms': 0.5, 'an.monotone-convergence': 0.4, 'sets.countable-unions': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Continuity and subadditivity of probability measures."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'prob.subadditivity',
    title: 'Countable subadditivity',
    summary: 'Prove P of a countable union is at most the sum of the probabilities (the union bound).',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.axiom-consequences'],
    encompasses: { 'prob.axiom-consequences': 0.5, 'prob.axioms': 0.5, 'an.nonnegative-series': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Continuity and subadditivity of probability measures."', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.independence',
    title: 'Independence of several events',
    summary: 'Define mutual independence of a family of events and tell it apart from pairwise independence.',
    level: 'tripos-ia',
    area: 'ia-axiomatic',
    prereqs: ['prob.independent-events', 'prob.axiom-consequences'],
    encompasses: { 'prob.independent-events': 0.6, 'prob.axiom-consequences': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Independence."', verified: true },
    estMinutes: 20,
  },

  // ---------------------------------------------------------------- conditioning
  {
    id: 'prob.conditional-probability',
    title: 'Conditional probability as a probability measure',
    summary: 'Show P(. | B) satisfies the axioms and use the multiplication rule for several events.',
    level: 'tripos-ia',
    area: 'conditioning',
    prereqs: ['prob.conditional-formula', 'prob.axiom-consequences'],
    encompasses: { 'prob.conditional-formula': 0.6, 'prob.axioms': 0.4 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Conditional probability."', verified: true },
    estMinutes: 20,
  },
  {
    id: 'prob.total-probability',
    title: 'The law of total probability',
    summary: 'Split P(A) over a finite or countable partition as the sum of P(A | B_i)P(B_i).',
    level: 'tripos-ia',
    area: 'conditioning',
    prereqs: ['prob.conditional-probability'],
    encompasses: { 'prob.conditional-probability': 0.6, 'prob.axioms': 0.3, 'pre.tree-diagrams': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Not named in the schedule; it is the step Bayes\'s formula needs.', verified: true },
    estMinutes: 15,
  },
  {
    id: 'prob.bayes-formula',
    title: 'Bayes\'s formula',
    summary: 'Reverse a conditional probability with Bayes\'s formula, for example in a diagnostic test.',
    level: 'tripos-ia',
    area: 'conditioning',
    prereqs: ['prob.total-probability'],
    encompasses: { 'prob.total-probability': 0.6, 'prob.conditional-probability': 0.5, 'prob.conditional-formula': 0.3 },
    source: {
      doc: TRIPOS,
      course: 'IA Probability',
      section: IA_AXIOMATIC,
      note: 'Schedule: "Bayes\'s formula." External check: STEP Support Foundation Assignment 6 (the prosecutor\'s fallacy).',
      verified: true,
    },
    estMinutes: 20,
  },
  {
    id: 'prob.simpsons-paradox',
    title: 'Simpson\'s paradox',
    summary: 'See how a comparison that holds in every group can reverse when the groups are pooled.',
    level: 'tripos-ia',
    area: 'conditioning',
    prereqs: ['prob.total-probability'],
    encompasses: { 'prob.total-probability': 0.7, 'prob.conditional-probability': 0.4, 'pre.two-way-tables': 0.3 },
    source: { doc: TRIPOS, course: 'IA Probability', section: IA_AXIOMATIC, note: 'Schedule: "Examples, including Simpson\'s paradox."', verified: true },
    estMinutes: 15,
  },
];
